### ISSUE TITLE
What is the role of the route layer

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#100]
Hello

I try to understand the yolov2.cfg model configuration, and I founded that there are a layer whose name is route, can you please explin to me what is the role of this layout

Thanks

**Comment by apisutilis** [comment]
See the paragraph on "fine grained features" at the end of page 3 of the YOLO9000 paper: https://arxiv.org/pdf/1612.08242.pdf (it is called "passthrough" there instead of "route"). It basically reuses activations from earlier in the network by concatenating them to activations later in the network.
