### ISSUE TITLE
Invalid SOS parameters for sequential JPEG 

### ISSUE THREAD

**Issue by alishibli97** [thtrieu/darkflow#1002]
I'm trying to train on a personal dataset with some images taken by phone, but I get this warning
Invalid SOS parameters for sequential JPEG.

**Comment by Wanderish** [comment]
Hey, @alishibli97 were you able to resolve the issue? Coz I'm having the same trouble.
Would you mind pointing me to the solution in case you got it resolved? 
Thanks in advance..
