### ISSUE TITLE
Can't make a prediction

### ISSUE THREAD

**Issue by IhorKosovych** [thtrieu/darkflow#1012]
Thanks for your awesome code share and explanation!

I trained the model. The performance was good.
```

step 10 - loss 119.7686767578125 - moving ave loss 119.82690792130654
Finish 10 epoch(es)
Checkpoint at step 10
Parsing cfg/yolov2.cfg
Loading None ...
Finished in 5.650520324707031e-05s

```
And then I tried to predict another image.
But after

`print(tfnet.return_predict(original_img))
`

The result is:

`[]`

But instead of empty brackets should be image prediction.

Can somebody help me?

**Comment by IhorKosovych** [comment]
The solution is to increase number of epochs. In previous case I set epoch - 100, in next case - I changed epochs to 2500 to get more then 10000 steps in result. If you get more then 10000 steps you will receive image prediction.

**Comment by mssudarsan** [comment]
Can you Suggest me how you have resolved this issue?

**Comment by ankitAMD** [comment]
> The solution is to increase number of epochs. In previous case I set epoch - 100, in next case - I changed epochs to 2500 to get more then 10000 steps in result. If you get more then 10000 steps you will receive image prediction.

@IhorKosovych 
i am training on 1 custom image detection with epoch 1500 loss becomes 1.05 something .
when i put threshold value 0.3 or 0.5 or 0.7 there is no detection .
so i change threshold value 0.03 ,0.01 on different image then it detect but properly detect.
so what i can do for better result.....please guide me.
