### ISSUE TITLE
Did the code use the K-mean

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#102]
Hello 

I am confusing about the code, I readed the article "https://arxiv.org/pdf/1612.08242.pdf" "Page 3" and I was surprised that the author mentioned the k-means algorithms for generating the bounding box, and it's was mentionned that it is better than generate bouding box by hand

My question is where is situated the part that implement the k-mean

Thanks

**Comment by thtrieu** [comment]
K-mean is used to calculate anchors, which is already provided in `.cfg` files, so if you had your `.cfg` files (which `darkflow` assumes); then there is no need to re-compute the anchors and thus, use k-mean.

**Comment by jjjjohnson** [comment]
Hi @thtrieu  Could you explain what the `anchors = 0.57273, 0.677385 ...` in `.cfg files` mean for bonding box? For example, what is anchors = 1, 1 corresponding to the size in the real image for YOLOv2 416X416.
