### ISSUE TITLE
Different working after converting on custom dataset

### ISSUE THREAD

**Issue by JaeongTaehun** [thtrieu/darkflow#1028]
hi i tried to convert .weights file to .pb to use my custom dataset. but after the convert with darkflow following on -savepb. it .weight and .pb is different working. you can see my photo.
why is that working? anybody can help me?

i used learning on darknet. and then try to convert on darkflow.

what was i wrong?

![1](https://user-images.githubusercontent.com/47021165/56480880-1bf12900-64f7-11e9-8225-9670611a9d9c.PNG)
![2](https://user-images.githubusercontent.com/47021165/56480884-1f84b000-64f7-11e9-8352-1c59391286fd.PNG)
![3](https://user-images.githubusercontent.com/47021165/56480885-214e7380-64f7-11e9-8365-f21a253dd802.PNG)

**Comment by crbothe** [comment]
Hi, did you solved the problem? Recently I also got the same behavior from .pb file, I have used only darkflow for training and converting, not darknet. It was working fine before sometime, and suddenly this started happening. I could trace back the env-revisions through conda, but no luck. 
Any help would be appreciated.

**Comment by JaeongTaehun** [comment]
> Hi, did you solved the problem? Recently I also got the same behavior from .pb file, I have used only darkflow for training and converting, not darknet. It was working fine before sometime, and suddenly this started happening. I could trace back the env-revisions through conda, but no luck.
> Any help would be appreciated.

Hi, yes i solved this problem. please try to set random option when you training yolov2.

**Comment by crbothe** [comment]
Thanks for your answer, but It is not clear what option you are talking about?

Did you mean? this:
flow --model cfg/tiny-yolo-4c.cfg --train --dataset imgs/ --annotation anns/ --epoch 1000 --save 100 --summary log/  --lr 1e-5 --load -1

Nothing much to set, or is there anything?

I could test with (works fine):
flow --imgdir sample_img/ --model cfg/tiny-yolo-4c.cfg --load -1 --threshold 0.1

Then I saved the weights in .pb file and test (does not do the same as before):
flow --model cfg/tiny-yolo-4c.cfg --load -1 --savepb
flow --pbLoad built_graph/tiny-yolo-4c.pb --metaLoad built_graph/tiny-yolo-4c.meta --imgdir sample_img/ --threshold 0.1
