### ISSUE TITLE
from darkflow.net.build import TFNet - This line is throwing error.

### ISSUE THREAD

**Issue by pavanyekabote** [thtrieu/darkflow#1035]
AttributeError                            Traceback (most recent call last)
<ipython-input-3-61a70a0c6d56> in <module>
----> 1 from darkflow.net.build import TFNet
      2 import cv2
      3 
      4 options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1}
      5 

~/darkflow/darkflow/net/build.py in <module>
      5 from .ops import op_create, identity
      6 from .ops import HEADER, LINE
----> 7 from .framework import create_framework
      8 from ..dark.darknet import Darknet
      9 import json

~/darkflow/darkflow/net/framework.py in <module>
----> 1 from . import yolo
      2 from . import yolov2
      3 from . import vanilla
      4 from os.path import basename
      5 

~/darkflow/darkflow/net/yolo/__init__.py in <module>
      1 from . import train
----> 2 from . import predict
      3 from . import data
      4 from . import misc
      5 import numpy as np

~/darkflow/darkflow/net/yolo/predict.py in <module>
      5 import os
      6 import json
----> 7 from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
      8 
      9 def _fix(obj, dims, scale, offs):

~/darkflow/darkflow/cython_utils/cy_yolo_findboxes.cpython-37m-x86_64-linux-gnu.so in init darkflow.cython_utils.cy_yolo_findboxes()

AttributeError: type object 'darkflow.cython_utils.cy_yolo_findboxes.array' has no attribute '__reduce_cython__'

-----------------------------------------------------------------------------------------------------------------------
Packages of following versions are used.
1. numpy - 1.16. 3
2. Cython - 0.29.7
3. tensorflow - 1.13.1

**Comment by ProtossDragoon** [comment]
solved?

**Comment by biranchi2018** [comment]
> solved?

Nope..

**Comment by kyriosabbes** [comment]
solved ?
