### ISSUE TITLE
What is m['num'] ?

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#105]
Hello 

I am reading the yolov2/train.py and in the loss function there m['num'] parameter, what it's for ?

Thanks,

**Comment by Dhruv-Mohan** [comment]
If I'm not wrong the m['num'] parameter represents the number of bounding boxes the network predicts at each cell in the output feature map. Look in the "Direct location prediction" section of the Yolo9000 paper.
