### ISSUE TITLE
How The process of prediction work ??

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#106]
Hello 

Currently, I am reading the "Yolo9000" Paper, and I have a lot of questions about this article, 
  1- First the how the anchor boxes work ?, 
  2- in the paper the author said that he used K-mean to generate them,  and I don't understand Why ?, for me the anchor boxes is only : boxes with many scales that are generated to better wrap the objects that have different scales in the images

**Comment by jcarletgo** [comment]
Try reading: https://groups.google.com/forum/#!topic/darknet/qrcGefJ6d5g
