### ISSUE TITLE
Training Yolo on new dataset with smaller label set

### ISSUE THREAD

**Issue by adiyoss** [thtrieu/darkflow#108]
Hey,
I'm trying to train Yolo on a new dataset
I annotated the data as requested and changed the labels.txt and .cfg file, but I still get an error regarding the input shape. I don't fully understand all the shape parameters in the config file.

This is the error:
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 215475 values, but the requested shape requires a multiple of 8450
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](output, Reshape/shape)]]
	 [[Node: mul_30/_195 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_2480_mul_30", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Help anyone?

**Comment by thtrieu** [comment]
Maybe https://github.com/thtrieu/darkflow/issues/107#issuecomment-289797117 can help
