### ISSUE TITLE
Xin tài liệu.

### ISSUE THREAD

**Issue by TanLocc** [thtrieu/darkflow#1091]
Chào thtrieu!
Em đang làm đồ án tốt nghiệp liên quan đến yolo, anh có thể cho em xin ít tài liệu liên quan đến yolo như: nguyên tắc hoạt động của mạng, cánh tạo ra các hộp giới hạn...
Nếu được anh command ở dưới hoặc gửi của email: lephantanloc299@gmail.com.
Cảm ơn anh.

**Comment by Tanmay-Kulkarni101** [comment]
Hey @TanLocc , you can find out more about yolo in the following link-
https://pjreddie.com/darknet/yolo/

It should everything you want to know about yolo.

**Comment by TanLocc** [comment]
Thank @Tanmay-Kulkarni101 .
