### ISSUE TITLE
No such file or directory: 'cfg/new-yolo.cfg'

### ISSUE THREAD

**Issue by pxoo** [thtrieu/darkflow#110]
When I followed the example instruction given in the README, it shows an error that FileNotFound error.

# 1. Load yolo-tiny.weights
./flow --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights

# 2. To completely initialize a model, leave the --load option
./flow --model cfg/yolo-new.cfg

# 3. It is useful to reuse the first identical layers of tiny for `yolo-new`
./flow --model cfg/yolo-new.cfg --load bin/yolo-tiny.weights
# this will print out which layers are reused, which are initialized

Is it that we should manually create yolo-new.cfg?

**Comment by borasy** [comment]
I think it's obvious that yolo-new.cfg is a new model created by you. It might be similar to yolo-tiny in some parts, that's why the author want you to initialize weights that are from identical layers.
