### ISSUE TITLE
ImportError: No module named contrib.slim

### ISSUE THREAD

**Issue by GoyalAnkit16** [thtrieu/darkflow#1101]
I'm getting this error
ImportError: No module named contrib.slim
![image](https://user-images.githubusercontent.com/54926326/69723690-3d2a8f80-1140-11ea-9a6a-5d88b805e0e2.png)

**Comment by hanouel** [comment]
Try to use tensorflow 1.14

**Comment by GoyalAnkit16** [comment]
Yeah. It worked.
Thanks

**Comment by ankitAMD** [comment]
Closes #1101

**Comment by ankitAMD** [comment]
****Please Close the issue .
