### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LuvRC** [thtrieu/darkflow#1107]
I used  class=1(solar panel ) and changes filters =30 for custom object detection training.
i am using VMware15.05 and i installed RHEL 6  on VMware.   
I am given size 400 GB for RHEL 6   on VMware
I am using yolo.cfg configuration file and yolo.weights  weights  file for training.
i use class=1 and filter =30
i changes in label.txt i.e. contain only  "solar_panel" .

After Executing this Command :
        
        python flow  --model cfg/yolo-1c.cfg --load bin/yolo.weights --train --annotation new_model_data/annotations --dataset new_model_data/images  --epoch 400

Process are failed and  this is Last line after executing above Command .

      0219-12-19 03:45:00.680721: I tensorflow/core/common_runtime/bfc_allocator.cc:816] Sum 
      Total of in-use chunks: 2.80GiB
      2019-12-19 03:45:00.680729: I tensorflow/core/common_runtime/bfc_allocator.cc:818]  
      total_region_allocated_bytes_: 3011067904 memory_limit_: 3011067904 available bytes: 0 
      curr_region_allocation_bytes_: 4294967296
      2019-12-19 03:45:00.680748: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats: 
    Limit:                  3011067904
    InUse:                  3011067904
    MaxInUse:               3011067904
    NumAllocs:                    1574
    MaxAllocSize:            830704384

    2019-12-19 03:45:00.680786: W tensorflow/core/common_runtime/bfc_allocator.cc:319] 
    **************************x**********************************x**************************************
     2019-12-19 03:45:00.689879: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES 
    failed at mkl_util.h:1026 : Resource exhausted: OOM when allocating tensor with 
    shape[189267968] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator 
     mklcpu
     Segmentation fault (core dumped)

Problem Images ...........................

![image](https://user-images.githubusercontent.com/59053129/71173610-313a7500-2289-11ea-8e69-2c699607acc4.png)

![image](https://user-images.githubusercontent.com/59053129/71173575-1d8f0e80-2289-11ea-921f-6d1fa7b7d3fb.png)

![image](https://user-images.githubusercontent.com/59053129/71173533-005a4000-2289-11ea-83f3-f5a114e71b7e.png)

![image](https://user-images.githubusercontent.com/59053129/71173498-e4569e80-2288-11ea-857e-6d4dde714291.png)

![image](https://user-images.githubusercontent.com/59053129/71173443-c25d1c00-2288-11ea-8f3c-c0688359908f.png)

![image](https://user-images.githubusercontent.com/59053129/71173375-917ce700-2288-11ea-8599-bb6a73d7c098.png)

Please help me to solve this Problem .................................Thank you

**Comment by LuvRC** [comment]
@thtrieu, please help. Thanks a lot in advance.

**Comment by LuvRC** [comment]
@ankitAMD please help.

**Comment by ankitAMD** [comment]
Everything is fine you done well ........use any another configuration file (like tiny-yolo.cfg) which have less layers ........yolo.cfg contain more than 22 convolution layers so it wants more memory .....that's why your this error comes .

In future if you provide sufficient amount of memory for yolo.cfg configuration file for training but your speed is slow if you uses CPU ..........because CPU have very less processing power.

**Comment by ankitAMD** [comment]
A

> Everything is fine you done well ........use any another configuration file (like tiny-yolo.cfg) which have less layers ........yolo.cfg contain more than 22 convolution layers so it wants more memory .....that's why your this error comes .
> 
> In future if you provide sufficient amount of memory for yolo.cfg configuration file for training but your speed is slow if you uses CPU ..........because CPU have very less processing power.

Always use yolo-1c.cfg a new copy of yolo.cfg configuration file.   Don't edit the yolo.cfg.

**Comment by LuvRC** [comment]
thank you Ankit.

> Everything is fine you done well ........use any another configuration file (like tiny-yolo.cfg) which have less layers ........yolo.cfg contain more than 22 convolution layers so it wants more memory .....that's why your this error comes .
> 
> In future if you provide sufficient amount of memory for yolo.cfg configuration file for training but your speed is slow if you uses CPU ..........because CPU have very less processing power.

          Thank you @ankitAMD this helps me to solve this error. Thank you again
