### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by ankitAMD** [thtrieu/darkflow#1108]
I am using Ubuntu 16.04 on VMware .
I have do custom image detection on class solar_images.
I alreaday installed tensorflow (required version tensorflow for this project).
I carefully Installed OPencv, Anaconda jupyter.
I run this project creating environment. 
But executing below command for training .........the first error comes is (given below link)

            https://github.com/thtrieu/darkflow/issues/1107 

for solving this error 
i read blogs and stackoverflow and they suggested to reinstall tensorflow.
 i have done reinstalling tensorflow but still not working.

so i remove the current tensorflow and installed the tensorflow of previous version.
after executing below command we get error which are shown in Pic. 

I executing this command  
      
         python flow  --model cfg/yolo-1c.cfg --load bin/yolo.weights --train --annotation new_model_data/annotations --dataset new_model_data/images --epoch 400

this error comes out.

![image](https://user-images.githubusercontent.com/17083641/71254899-61017f80-2352-11ea-856e-340bf6a6c13c.png)

**Comment by Rishabh-Maheshwari** [comment]
Wasn't able to reproduce the error. May be the issue is with libstdc++ or its version. Try following steps:

Firstly, install:
sudo apt-get install libstdc++6
This should already be installed by default, but try it anyway. 

If it doesn't solve it, just do the following:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade

If it still doesn't. run the following command:
sudo apt-get dist-upgrade

**Comment by ankitAMD** [comment]
> Wasn't able to reproduce the error. May be the issue is with libstdc++ or its version. Try following steps:
> 
> Firstly, install:
> sudo apt-get install libstdc++6
> This should already be installed by default, but try it anyway.
> 
> If it doesn't solve it, just do the following:
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get upgrade
> 
> If it still doesn't. run the following command:
> sudo apt-get dist-upgrade

                                   Thank you for reply .................
