### ISSUE TITLE
Lacking memory, how to reduce

### ISSUE THREAD

**Issue by traw1234** [thtrieu/darkflow#111]
I am attempting to run darkflow on the Jetson TX1 which is limited to 4g of ram, so anytime I try to run tiny yolo, I get a runtime error saying that it can't allocate 2.29g of memory. Any suggestions for slimming the model down even more? If it helps, my only detection needed is people.

**Comment by Dhruv-Mohan** [comment]
Traw, can you post your initialisation command ?

**Comment by traw1234** [comment]
`python3 flow --model cfg/tiny-yolo-voc.c-load bin/tiny-yolo-voc.weights --gpu .5 --demo camera`

I've tried many different combinations for the GPU percentage, this gives me the highest FPS I've gotten of 1.56

**Comment by Dhruv-Mohan** [comment]
Framerate should see an increase as per #113

**Comment by traw1234** [comment]
@Dhruv-Mohan I just pulled the latest branch, keep getting this error. 

`
Traceback (most recent call last):

File "flow", line 3, in <module>
    from net.build import TFNet
File "/home/ubuntu/git/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
File "/home/ubuntu/git/darkflow/net/framework.py", line 2, in <module>
    from . import yolov2
File "/home/ubuntu/git/darkflow/net/yolov2/__init__.py", line 2, in <module>
    from . import test
File "/home/ubuntu/git/darkflow/net/yolov2/test.py", line 9, in <module>
    from cython_utils.cy_yolo2_findboxes import box_constructor
`

Not quite sure why this is happening.

**Comment by thtrieu** [comment]
Please see the **Dependencies** part in README for compiling cython code.

**Comment by traw1234** [comment]
I definitely see a huge improvement, got up to 3.5FPS. However, I would still like to get a faster model. Any tips for training my own model (as I said, only on people) to improve the speed? I can just play with the hyperparams but I would love any suggestions if available.
