### ISSUE TITLE
Updating label set - inconsistency between labels.txt and cfg file

### ISSUE THREAD

**Issue by dkarmon** [thtrieu/darkflow#112]
Hi,
I'm trying to run yolo v2 on a vehicle dataset that includes only 4 classes. However, after modifying both the labels.txt file and the cfg file (copied the original yolo cfg file and updated num of classes to 4), I get an inconsistency between both files error. What am I missing?

Also, I looked for similar past issues, most of them suggest modifying other parameters as well (e.g. the output size of the last FC layer). However, such parameters do not exist in v2.

Please advise,
Thanks

**Comment by thtrieu** [comment]
In v2, you should change the filter number of last convolution.
Specifically: filter = num * (5 + classes)
where num and classes can be found in `[region]`

**Comment by dkarmon** [comment]
Still same problem.

**labels.txt:**
car
truck
bus
motor

**new-yolo.cfg:**
...
[convolutional]
size=1
stride=1
pad=1
**filters=45**
activation=linear

[region]
anchors = 0.738768,0.874946,  2.42204,2.65704,  4.30971,7.04493,  10.246,4.59428,  12.6868,11.8741
bias_match=1
**classes=4**
coords=4
**num=5**
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh=.3
random=0

**Comment by thtrieu** [comment]
Any trailing white spaces / line breaks in `labels.txt`?

**Comment by dkarmon** [comment]
No, none. only one class at a line with no trailing line breaks.

**Comment by thtrieu** [comment]
Mine:
```
[convolutional]
size=1
stride=1
pad=1
filters=45
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=4
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh=.6
random=0
```

labels:
```
```

**Comment by thtrieu** [comment]
Please post the command that leads to this error.

**Comment by dkarmon** [comment]
Your example works fine. 
It seems that there were apparently some invisible trailing white spaces/line breaks. 

Thank you very much!
