### ISSUE TITLE
Tutorial for training with YOLO

### ISSUE THREAD

**Issue by Mikkochu** [thtrieu/darkflow#1123]
Hi,

I'm a beginner programmer. I just finished installing darknet successfully. 
My goal is to detect playing cards from a videostream. However unlike the youtube video below I my cards are static, since there will be no overlapping (online poker). 
https://www.youtube.com/watch?v=pnntrewH0xg

How should I proceed creating the testing data? So far I have pictures of different playing card in black&white and in color.  This is an example of a test picture https://ibb.co/rd3tmt8

Currently I'm looking for a clear tutorial on how to use my own data on darknet

**Comment by ankitAMD** [comment]
Read this github..........              
              
              https://github.com/ankitAMD/Darkflow-object-detection
Please close the issue ....if  solved.
