### ISSUE TITLE
How can I train with my own dataset? help wanted

### ISSUE THREAD

**Issue by Mikkochu** [thtrieu/darkflow#1126]
I'm trying to train darkflow with my own dataset.

I have installed darkflow, created test images and made annotations (Pascal VOC & YOLO).
If I have understood correctly the darkflow training requires Pascal VOC?

My problem is that I don't know how to start the training. Am I supposed to get weights as a result of training?

**Comment by ankitAMD** [comment]
Change Class name in labels.txt file.
Creating XML Annotations file of all images separately which class they belong.
You have lot of options of configuration and weight file. like yolo.cfg , tiny-yolo.cfg.
Changes in some code.
Follow this github and read it.
https://github.com/ankitAMD/Darkflow-object-detection

**Comment by Mikkochu** [comment]
> Change Class name in labels.txt file.
> Creating XML Annotations file of all images separately which class they belong.
> You have lot of options of configuration and weight file. like yolo.cfg , tiny-yolo.cfg.
> Changes in some code.
> Follow this github and read it.
> https://github.com/ankitAMD/Darkflow-object-detection

Thank you so much. I will read the tutorial! I managed to complete the training, but now I'm having problems with testing. https://github.com/thtrieu/darkflow/issues/1127

**Comment by ankitAMD** [comment]
Training complete, but can't test the neural net #1127 #1128

**Comment by ankitAMD** [comment]
Please close this issue if you have completed.
