### ISSUE TITLE
Getting this error while running 'setup.py' file!!

### ISSUE THREAD

**Issue by snehitvaddi** [thtrieu/darkflow#1142]
`import setup, find_packages
 ModuleNotFoundError: No module named 'find_packages'`

**Comment by ankitAMD** [comment]
are you solved this issue please close down this issue.

**Comment by ankitAMD** [comment]
> `import setup, find_packages ModuleNotFoundError: No module named 'find_packages'`
Please write how you solve this issue its helps other person. thank you

**Comment by snehitvaddi** [comment]
It worked after installing setuptools of version 41.0.0
command : `pip install setuptools==40.0.0`
