### ISSUE TITLE
What is correct input for --dataset parameter? 

### ISSUE THREAD

**Issue by pxoo** [thtrieu/darkflow#115]
Could anyone give me more instruction about this "Training is simple as you only have to add option --train. Training set and annotation will be parsed if this is the first time a new configuration is trained. To point to training set and annotations, use option --dataset and --annotation." 

I have created a training.txt file which contains the path of all training images and set the --dataset point to the text file's path but it showed an error about "Dataset of 0 instance(s)" 

I also tried just set the --dataset point to the images' directory but still got same error.

Is anyone know what is correct format for the dataset input? Thanks.

**Comment by kamelbouyacoub** [comment]
you need to give the folder that contain the images ".jpg" to --dataset

**Comment by pxoo** [comment]
Should I store the annotation into XML files or text files?

**Comment by kamelbouyacoub** [comment]
xml files, you need to generate them in a correct format, like in the pascalVOC2007 and the pass the folder that contain the annotation to --annotation argument

**Comment by pxoo** [comment]
Thanks for your answer. I have tried this way by using the PASCAL VOC 2008 and the command is " ./flow --model cfg/yolo-new.cfg --load bin/tiny-yolo.weights --train --dataset /VOCdevkit/VOC2008/JPEGImages --annotation /VOCdevkit/VOC2008/Annotations " and it still gave me the same error that "Dataset of 0 instance(s) and zero division exception".

**Comment by HolyGuacamole** [comment]
@pxoo I've had a similar situation where the previously parsed annotations were loaded.  (see issue #121)
Deleting the file `net/yolo/parse-history.txt` fixed it for me.

**Comment by borasy** [comment]
hey guys, so it only accepts .jpg extension only?
