### ISSUE TITLE
Assertion error: cannot capture camera

### ISSUE THREAD

**Issue by ramarajan09** [thtrieu/darkflow#123]
Hi,

I am trying to run the demo on a video file on windows setup.

python ./flow --model cfg/yolo-new.cfg --load bin/yolo-new.weights --demo videofile.avi

I get an assertion error: cannot capture camera.
However, the demo on images work well.
![error](https://cloud.githubusercontent.com/assets/26741040/24576713/9f9a200a-16b0-11e7-9cf0-83a6c37d3b10.png)

**Comment by Prakash19921206** [comment]
put full path of video within double quotes

**Comment by ramarajan09** [comment]
Still get the same error even after providing full path within quotes :(

**Comment by Prakash19921206** [comment]
did u replace backward slash with forward slash
also try providing other(.mp4) videos formats..

**Comment by ramarajan09** [comment]
I tired with the forward, backward slash and also on a avi file. it does not work. When looked into the code, it looks like it requires a webcam input and the code is not modified to take a video input.

def camera(self, file):
    camera = cv2.VideoCapture(0)
    self.say('Press [ESC] to quit demo')
    assert camera.isOpened(), \
    'Cannot capture source'

**Comment by ramarajan09** [comment]
I think this has been fixed in the latest commits. Hence closing the issue.

**Comment by phantomrider24** [comment]
how does one fix this issue
