### ISSUE TITLE
ImportError: No module named cy_yolo2_findboxes

### ISSUE THREAD

**Issue by zgq91** [thtrieu/darkflow#125]
hi:
   when  I execute  ./flow --model tiny-yolo-voc.cfg --load tiny-yolo-voc.weights --savepb  command when an "from cython_utils.cy_yolo2_findboxes import box_constructor ImportError: No module named cy_yolo2_findboxes" error  occurs.  my environments  anancoda2  and opencv3.1

**Comment by Dhruv-Mohan** [comment]
Hey! you'll have to build the cython function first use 
```
cd ./cython_utils
python3 setup.py build_ext --inplace
cd ..
```

**Comment by zgq91** [comment]
Hey!   
when  I have to  build the cython function ,but still does not work .  when  I execute " ./flow --model tiny-yolo-voc.cfg --load tiny-yolo-voc.weights --savepb" command  still the error  " from cython_utils.cy_yolo2_findboxes import box_constructor ImportError: No module named cy_yolo2_findboxes "

**Comment by Dhruv-Mohan** [comment]
Can you post the output of the cython build command?

**Comment by jingjingwang** [comment]
I had the same issue, it's probably because that you also had python2 installed. Try `#! /usr/bin/env python3` in `flow`.

**Comment by zgq91** [comment]
Thank you very much for having solved this problem;  I execute " python2 setup.py build_ext --inplace " command . Probably because of my environmental (anaconda2 and opencv3.1) problems

**Comment by rakeen** [comment]
Ran into similar problem   
```
File "cython_utils/cy_yolo2_findboxes.pyx", line 59, in cython_utils.cy_yolo2_findboxes.box_constructor (cy_yolo2_findboxes.c:2575)
    double[:] anchors = np.asarray(meta['anchors'])
AttributeError: 'module' object has no attribute 'asarray'
```
I'm using python 3.4
While building `cython_utils` I get this:
`Warning: Extension name 'nms' does not match fully qualified name 'cython_utils.nms' of 'nms.pyx'`

**Comment by cory8249** [comment]
@rakeen I have same problem. But I think it's because path setting is wrong.
Just `cd ./cython_utils` and run `python3 setup.py build_ext --inplace` will work.

**Comment by ilopezfr** [comment]
I'm also having similar issue when trying to run the yolo-tiny
`./flow --imgdir sample_img/ --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights --gpu 1.0`

I was able to previously run `python3 setup.py build_ext --inplace` in darknet folder with no problem.

I'm using python 3.5. Any thoughts?

<img width="674" alt="screen shot 2017-06-02 at 7 28 21 pm" src="https://cloud.githubusercontent.com/assets/11858780/26749037/afd57498-47c9-11e7-888f-9167c914e18b.png">
