### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by jaidmin** [thtrieu/darkflow#128]
Hi,

I have a problem when trying to train/finetune on a custom dataset.

I use the newest master version (just recloned) and tensorflow 1.0.1

I have recreated the PASCAL VOC structure with having one jpegimages folder with all the images and an annotation folder that contain one xml file for every image. The XML file is the same structure as the VOC files. In labels I have all my labels, one per line and i changed the number of classes in my cfg, as well as the filters in the last convolutional layer (num * (5 + classes)) as I read in another issue.

Now whenever I try to train the model (it doesn't matter whether I include "--load WEIGHTFILE") I get the following error.

Enter training ...
Dataset of 9963 instance(s)
Traceback (most recent call last):
  File "./flow", line 55, in <module>
    print('Enter training ...'); tfnet.train()
  File "/home/jaidmin/Software/Sources/darkflow/net/flow.py", line 37, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/jaidmin/Software/Sources/darkflow/net/yolo/data.py", line 146, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "/home/jaidmin/Software/Sources/darkflow/net/yolov2/data.py", line 27, in _batch
    img = self.preprocess(path, allobj)
  File "/home/jaidmin/Software/Sources/darkflow/net/yolo/test.py", line 98, in preprocess
    result = imcv2_affine_trans(im)
  File "/home/jaidmin/Software/Sources/darkflow/utils/im_transform.py", line 19, in imcv2_affine_trans
    h, w, c = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

From what I understand I suspect there is some problem with opening the images (hence "NoneType"), but I have no idea how to fix it.

When I try to train on the VOC dataset it works just fine.

Does anybody know how to fix it?

Thanks for any help

**Comment by thtrieu** [comment]
Please specify the steps and command you use that lead to this error (number them will be even better).

**Comment by jaidmin** [comment]
Thanks for the (very!) quick answer.

I did the following things:

1. verify that everything works with the PASCAL VOC dataset (I downloaded it after the instructions on https://pjreddie.com/darknet/yolo/) with the following command
`./flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --train --dataset ../VOC/VOCdevkit/VOC2007/JPEGImages --annotation ../VOC/VOCdevkit/VOC2007/Annotations`
(the yolo-voc.cfg is from the darknet repository, because the one in this repo gave me the over-read error)
-> the training starts without any errors

2. make a copy of the cfg file and change the number of output classes to 8 and the number of filters in the last conv layer to 65 (I read the number of filters should be 'num' * (5+classes))

3. edit the labels.txt and put in my labels like this:
ALB 
BET
DOL
LAG
NoF
OTHER
SHARK
YFT

4. prepare my dataset to match the PASCAL VOC format: 
..1. all images are in a folder called jpeg_images
..2. all annotations are in xml files (one per image)

here is one xml file for example:
```
<annotation>
  <folder>fisheries</folder>
  <filename>img_00014.jpg</filename>
  <path>/home/jaidmin/Software/Sources/fisheries/jpeg_imagesimg_00014.jpg</path>
  <source>
    <database>Kaggle Fisheries</database>
    <annotation>kaggle forums</annotation>
    <image>nature of conservancy fishing</image>
  </source>
  <owner>
    <name>Us government</name>
  </owner>
  <size>
    <width>1280</width>
    <height>974</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>YFT</name>
    <pose>unknown</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>360</xmin>
      <ymin>312</ymin>
      <xmax>570</xmax>
      <ymax>478</ymax>
    </bndbox>
  </object>
</annotation>
```

It has all the tags that the original voc annotations have. (I added pose, truncated and difficult tags later but they didnt change anything)

5. Now I ran the following command:
`./flow --model cfg/custom-yolo.cfg --load bin/yolo-voc.weights --train --dataset ../fisheries/jpeg_images  --annotation ../fisheries/annotations`
where custom-yolo.cfg is the changed config with the correct number of classes and filters.
I get the following result:

```
(tensorflow) ➜  darkflow git:(master) ✗ ./flow --model cfg/custom-yolo.cfg --load bin/yolo-voc.weights --train --dataset ../fisheries/jpeg_images  --annotation ../fisheries/annotations
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Parsing ./cfg/yolo-voc.cfg
Parsing cfg/custom-yolo.cfg
Loading bin/yolo-voc.weights ...
Successfully identified 202704260 bytes
Finished in 0.024626970291137695s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 26, 26, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 26, 26, 64)
 Load  |  Yep!  | local flatten 2x2                | (?, 13, 13, 256)
 Load  |  Yep!  | concat [27, 24]                  | (?, 13, 13, 1280)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 65)
-------+--------+----------------------------------+---------------
Running entirely on CPU
cfg/custom-yolo.cfg loss hyper-parameters:
	H       = 13
	W       = 13
	box     = 5
	classes = 8
	scales  = [1.0, 5.0, 1.0, 1.0]
Building cfg/custom-yolo.cfg loss
Building cfg/custom-yolo.cfg train op
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.367
pciBusID 0000:02:00.0
Total memory: 3.94GiB
Free memory: 3.56GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:02:00.0)
Finished in 5.100748538970947s

Enter training ...
Dataset of 9963 instance(s)
Traceback (most recent call last):
  File "./flow", line 55, in <module>
    print('Enter training ...'); tfnet.train()
  File "/home/jaidmin/Software/Sources/darkflow/net/flow.py", line 37, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/jaidmin/Software/Sources/darkflow/net/yolo/data.py", line 146, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "/home/jaidmin/Software/Sources/darkflow/net/yolov2/data.py", line 27, in _batch
    img = self.preprocess(path, allobj)
  File "/home/jaidmin/Software/Sources/darkflow/net/yolo/test.py", line 61, in preprocess
    result = imcv2_affine_trans(im)
  File "/home/jaidmin/Software/Sources/darkflow/utils/im_transform.py", line 19, in imcv2_affine_trans
```

So it seems the model loads normally and then somehow instead of an image it gets a "NoneType" object. 

I will try to find more about the problem and post it here.

Thanks for your help

**Comment by thtrieu** [comment]
Looking at your `xml` I can clearly see the reason:
```
  <filename>img_00014.jpg</filename>
  <path>/home/jaidmin/Software/Sources/fisheries/jpeg_imagesimg_00014.jpg</path>
```
Original PASCAL VOC format says the file should be `../fisheries/imagesimg_00014.jpg` as in the `<filename>` tag, but then there is `<path>` tag saying that the name has `jpeg_` prefix.

So I suggest modifying the code here https://github.com/thtrieu/darkflow/blob/master/utils/pascal_voc_clean_xml.py#L59 a bit, instead of `[[jpg, [w, h, all]]]`, it should be `[['jpeg_' + jpg, [w, h, all]]]`.

**Comment by jaidmin** [comment]
Turned out you were right (your message is not displayed here? i'm quite new to github).

I didn't modify source, I modified the annotations

For anybody reading this later:

1. make sure you have the same format as pascal voc
2. the filename should be a relative path from your annotation to the image that it annotates
3. it might be necessary (it was for me) to delete `darkflow/net/yolo/parse-history.txt` to "notify" darkflow of the changed format

thanks for the quick help, I will read more of the source and if I have time and feel confident I will create a PR for darkflow to fail gracefully in case it cannot open the images.

cheers

**Comment by function1983** [comment]
Hi, thank you for your great project.

I am having the same issue while trying to train YOLOv2 with VOC2007.

1. Content of my trainVOC.py file:
> from darkflow.darkflow.defaults import argHandler #Import the default arguments
> import os
> from darkflow.darkflow.net.build import TFNet
> 
> FLAGS = argHandler()
> FLAGS.setDefaults()
> 
> FLAGS.model = "darkflow/cfg/tiny-yolo-voc-3c.cfg" # tensorflow model
> FLAGS.load = "darkflow/bin/tiny-yolo-voc.weights" # tensorflow weights
> FLAGS.threshold = 0.5 # threshold of decetion confidance (detection if confidance > threshold )
> FLAGS.gpu = 0.5 #how much of the GPU to use (between 0 and 1) 0 means use cpu
> FLAGS.annotation = "darkflow/VOC2007/Annotations"
> FLAGS.dataset = "darkflow/VOC2007/JPEGImages"
> 
> tfnet = TFNet(FLAGS)
> tfnet.train()

2. Run trainVOC.py and this is the output I got:
> Parsing darkflow/cfg/tiny-yolo-voc.cfg
> Parsing darkflow/cfg/tiny-yolo-voc-3c.cfg
> Loading darkflow/bin/tiny-yolo-voc.weights ...
> Successfully identified 63471556 bytes
> Finished in 0.005514621734619141s
> 
> Building net ...
> Source | Train? | Layer description                | Output size
> -------+--------+----------------------------------+---------------
>        |        | input                            | (?, 416, 416, 3)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
>  Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
>  Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 30)
> -------+--------+----------------------------------+---------------
> GPU mode with 0.5 usage
> 2017-12-08 02:02:26.603301: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> 2017-12-08 02:02:27.037288: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
> name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.468
> pciBusID: 0000:09:00.0
> totalMemory: 4.00GiB freeMemory: 3.33GiB
> 2017-12-08 02:02:27.037420: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
> Finished in 3.25093936920166s
> 
> Enter training ...
> Traceback (most recent call last):
>   File ".\train.py", line 20, in <module>
>     print('Enter training ...'); tfnet.train()
>   File "C:\darkflow\darkflow\net\flow.py", line 33, in train
>     loss_ph = self.framework.placeholders
> AttributeError: 'YOLOv2' object has no attribute 'placeholders'

The content of tiny-yolo-voc-3c.cfg is from your README. I tried to trace back to your net/yolov2/train.py then I got stuck. What do you think I did wrong here. I am on Windows 10, Python 3.6 if that helps. Thank you for your time.

**Comment by GuimExc** [comment]
I'm having the same problem as @function1983

**Comment by function1983** [comment]
@GuimExc I moved to linux and set GPU limit. I THINK that solved my error (not 100% sure, cause I did lot of thing than that). So first try to set the GPU limit param. Good luck.

**Comment by GuimExc** [comment]
You mean the GPU usage? I lowered it and that didn't solve the problem, unfortunately.

**Comment by marcunzueta** [comment]
I had the same problem as @function1983 when trying to use the code he posted to run everything from a Jupyter notebook. Found that `FLAG.train = True` is needed

**Comment by vinceparis95** [comment]
It only looks like i have one xml file, should my annotations folder have 100 .jpgs?
