### ISSUE TITLE
Train custom data

### ISSUE THREAD

**Issue by dewival** [thtrieu/darkflow#129]
How to train network my custom dataset? I have one class, 300 images in dataset and annotations in YOLO format (0 0.743243 0.585051 0.0579150 0.0773195). This is my first experience of NN, please help

**Comment by thtrieu** [comment]
You may want to read the README and point out which part you don't understand then people will be able to help you out.

**Comment by DanMossa** [comment]
@thtrieu Maybe I'm blind, but I don't see a place in the README that explains how to go about using your own custom images in YOLO format
