### ISSUE TITLE
Re-train model on new dataset: bbox necessary ?

### ISSUE THREAD

**Issue by MatthiasRMS** [thtrieu/darkflow#131]
Hi !

I'm working on retraining this model on a new dataset to extract attributes from clothes (e.g sleeves type, neck type etc). 

I have a set with images and for each image the attributes, but I don't have the bound boxes of each attribute on the image as it is in the PASCAL VOC dataset.

Do I need the bound boxes to retrain it ?

**Comment by AndreaPisoni** [comment]
This is a network to detect and put bounding boxes on objects in an image. If you are not interested about bounding boxes, then probably this is not the net you are looking for. If you want to have bounding boxes on the output but do not have them on your training dataset, then you have to label your dataset correctly first.
