### ISSUE TITLE
cannot run test with PNG images

### ISSUE THREAD

**Issue by ramarajan09** [thtrieu/darkflow#133]
Is this a known issue. I try to run with bunch of PNG images it says no file found. however jpg images works just fine.

**Comment by thtrieu** [comment]
Might have been resolved in https://github.com/thtrieu/darkflow/commit/80f5798d7dcce94969577b585cd26aa0f0c74602

Can you pull new code & confirm that it works?

**Comment by ramarajan09** [comment]
great it works and hence closing the issie
