### ISSUE TITLE
cannot run test on 100 images

### ISSUE THREAD

**Issue by ramarajan09** [thtrieu/darkflow#134]
I tried to run the test on 100 images however it works only for 96 images. I think this has to do with 16 forwarding inputs?

**Comment by thtrieu** [comment]
I'm fixing this ASAP.

**Comment by thtrieu** [comment]
Hope this works https://github.com/thtrieu/darkflow/commit/d8f37aa226924b3e4bc26f7d893ff35ae5301eaa

**Comment by ramarajan09** [comment]
Perfect. It works. I was about to change the same. Thanks. closing the issue.
