### ISSUE TITLE
video processing

### ISSUE THREAD

**Issue by ramarajan09** [thtrieu/darkflow#135]
Hi, is there a way to provide fps value when running demo on a video file and also how to store the bounding box value on each frame?

**Comment by thtrieu** [comment]
FPS is displayed in the console. Bounding box value for each frame is not supported, but currently you can modify code in https://github.com/thtrieu/darkflow/blob/master/net/help.py#L68 to do that.

Specifically, replace `self.framework.postprocess()` in https://github.com/thtrieu/darkflow/blob/master/net/help.py#L106 with `self.return_predict()` is a good option.
