### ISSUE TITLE
What is the utility of the .parsed file

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#136]
Hello 

Evervy time I start a new training, a .parsed file is generated, can you please tell me, what is the pupose of this files 

Thanks,

**Comment by ahmedbaracat** [comment]
Would love to know that as well :) 

I couldn't find the part of the codebase responsible for generating the `.parsed` file.

**Comment by thtrieu** [comment]
`.parsed` is a cache of parsed annotation (from XML to easier to manage form), to avoid parsing the same thing every time `--train` is used. However there are several downsides of managing the `parsed` files and this approach of caching is not used anymore in newer versions.
