### ISSUE TITLE
Include training images with no annotations?

### ISSUE THREAD

**Issue by stephaniedebats** [thtrieu/darkflow#137]
Is it possible to include images with no annotations in the training data set (i.e. images with no objects of interest), so the model learns what not to detect? In the VOC dataset, each image appears to have at least one annotation.

**Comment by Dhruv-Mohan** [comment]
Interesting but I don't think the framework of the network allows for or even needs a negative image set.  During training the network takes into account the cells which have objects and which don't. Please refer to training section of the the you look only once paper [https://arxiv.org/abs/1506.02640](url)

**Comment by thtrieu** [comment]
You can surely do that, simply add images with appropriate annotations to your dataset (no `object` tag).
