### ISSUE TITLE
Convert opencv_annotation tool based annotations to YOLO format

### ISSUE THREAD

**Issue by SarthakYadav** [thtrieu/darkflow#138]
Hello

I have a single object detection task at hand, with multiple occurrences of the object in a given image. 
I have the data-set annotated using the opencv_annotation tool. 

I need help converting those annotations to a format fit for YOLO. Can you please help me out?

**Comment by jaidmin** [comment]
What format are the annotations in? I just wrote a small json to xml parser for the kaggle fisheries dataset and had some troubles too:

https://github.com/thtrieu/darkflow/issues/128

Maybe you could post an example of an annotation.

**Comment by SarthakYadav** [comment]
here is the format

`/home/sarthak/haartraining/positives/pos_0/1007.jpg 6 182 250 97 89 228 335 96 115 315 357 99 110 315 357 99 110 414 357 84 139 280 217 149 131
/home/sarthak/haartraining/positives/pos_0/1011.jpg 5 232 107 115 113 156 215 105 123 113 318 118 128 85 437 91 113 275 220 135 117
/home/sarthak/haartraining/positives/pos_0/1017.jpg 7 234 31 127 126 383 68 131 114 405 173 136 115 371 379 113 125 274 343 117 124 183 342 104 124 247 470 141 145
`

**Comment by SarthakYadav** [comment]
The number right next to the filename is the number of objects. Then, there are 4 points corresponding to each object, which I believe are in the following notation: top, bottom, left, and right

**Comment by SarthakYadav** [comment]
you're competing on NCFM as well?
Gosh. The things I've tried for that competition!

**Comment by SarthakYadav** [comment]
Is the annotation format used by YOLO the same as the PASCAL VOC format???

**Comment by jaidmin** [comment]
Yes, but I didn't had much time for the competition :( looking forward to the sea lion competition. 
Yes it is the same format, if you could make the image of the example available in original resolution I can write a small gist when I get home (~6 hours) if you still need it then.

**Comment by SarthakYadav** [comment]
I suppose YOLO only takes input images in 448x448 size?? Or does it resize the image on its own?

PS: The annotations I have are for images resized to 640x640 format. 

I think I'll rather download some tool and re-annotate the images, since I have only 160 images annotated (yet) and I'll have to get the rest done anyway. 
Do you know of any such tool? That annoates images and outputs them to PASCAL VOC format?

**Comment by jaidmin** [comment]
Darkflow takes the size of the image and the coordinated of the corner of the boxes like Pascal voc. The images get resized and the annotations adjusted automatically by darkflow, so I would recommend labeling the original images.

**Comment by jcarletgo** [comment]
I found it easier to write a file similar to utils/pascal_voc_clean_xml.py for the data I'm using, than trying to get it to VOC xml. The .parsed is a list of lists (dumps). The detections(all/current) are formatted as [class, xmin, ymin, xmax, ymax].

**Comment by SarthakYadav** [comment]
Thanks!!! I'll report once I get stuff working!
