### ISSUE TITLE
weights file after training

### ISSUE THREAD

**Issue by luvalenz** [thtrieu/darkflow#139]
I've been using training darkflow with my own data, but I can't see where the `.weights`  is saved after training process has finished. I get a bunch of `.profile` files in the ckpt folder, but no `.weights` file. Shouldn't this file be generated somewhere? Could someone tell me where is it stored?
Thanks!

**Comment by jcarletgo** [comment]
See Issue #77

**Comment by luvalenz** [comment]
Thanks!
