### ISSUE TITLE
Understand net/yolov2/train.py

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#140]
Hello 

Currently I am trying to understand the code but unfortunately, I don't understand many things spécialy in the train.py file, please if anyone can advice me for documentation or can explain me the code please help me

Thanks,

**Comment by ryansun1900** [comment]
# https://github.com/thtrieu/darkflow/issues/104

Current version is implemented by referring darkflow yolo V1 & Yolo 9000 paper.
If you want to research the training process, I suggest you read the original darknet C code directly.

**Comment by kamelbouyacoub** [comment]
I don't understand, YOLO 9000 isn't the YOLOV2 in the code ?

**Comment by ryansun1900** [comment]
YES. But current implementation is not translated from darknet source code directly. There is a bug as mentioned on #104.
