### ISSUE TITLE
new tiny-yolo.cfg Network structure  saving .pb  AssertionError: Over-read tiny-yolo.weights

### ISSUE THREAD

**Issue by zgq91** [thtrieu/darkflow#141]
Hi:
   I modify the tiny-yolo.cfg network and to retrain. when I execute the " ./flow --model tiny-yolo.cfg --load tiny-yolo.weight  --savepb " command,  "AssertionError: over-read tiny-yolo.weights" error occurs.    
![02](https://cloud.githubusercontent.com/assets/18069515/24744762/afc51f5a-1ae5-11e7-854d-96a4dcccaf7d.png)

**Comment by abagshaw** [comment]
Maybe there's been an update to the `.weights` and/or `.cfg` file. I tried downloading the latest versions of both just now and running `--savepb` on them and I get an error `Layer "button" aria-label not implemented`

Looks like a new update on that specific model uses a type of layer that isn't yet implemented in darkflow (my best guess at why this isn't working).

**Comment by abagshaw** [comment]
**Edit:** Please ignore what I said previously.

I downloaded the most recent tiny-yolo.weights file and tiny-yolo.cfg from https://pjreddie.com/darknet/yolo/ and generating a .pb worked fine. Please try downloading the files again and see if you still get the error.
