### ISSUE TITLE
How to execute flow file  

### ISSUE THREAD

**Issue by beebrain** [thtrieu/darkflow#144]
i can't execute flow file 
i try to change to python file
and run command "python flow.py" but it not work
I have yoloweight in bin folder but i can't see yolo-tiny.cfg in cfg folder.

**Comment by kinhunt** [comment]
show errors

**Comment by abagshaw** [comment]
Are you missing dependencies? (you need Python3, tensorflow 1.0, numpy and opencv 3). Please post any errors you are seeing.

**Comment by beebrain** [comment]
I have yolo weight in bin folder, I try to excute shown in figure
![image](https://cloud.githubusercontent.com/assets/10016227/24805248/530d85ee-1bdb-11e7-83ed-fea538a65f20.png)
how to fix it , I saw many cfg file but it don't have yolo-tiny.cfg file. How do I get cfg file?

**Comment by abagshaw** [comment]
The pre-trained weights along with their .cfg files provided with darknet can be found here https://pjreddie.com/darknet/yolo/

**Comment by beebrain** [comment]
Thank you i fixed it.
but i have some error
when i train new model i got this message
![image](https://cloud.githubusercontent.com/assets/10016227/24809267/2da3e8ee-1be9-11e7-8b4d-067b44d31da2.png)

**Comment by beebrain** [comment]
Thank you every one. Now I can fixed it. I create folder cfg in net\yolo. It's can train a data set.
Thank you very much.
