### ISSUE TITLE
Problem with batch_norm()

### ISSUE THREAD

**Issue by natanielruiz** [thtrieu/darkflow#15]
Hey, I tried loading various models and I always get this error. For example when I run: ./flow --model cfg/v1.1/tiny-yolov1.cfg

I get the following.

> Parsing cfg/v1.1/tiny-yolov1.cfg
> Loading None ...
> Finished in 7.70092010498e-05s
> 
> Building net ...
> Source | Train? | Layer description                | Output size
> -------+--------+----------------------------------+---------------
> Traceback (most recent call last):
>   File "./flow", line 41, in <module>
>     tfnet = TFNet(FLAGS)
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/build.py", line 50, in __init__
>     self.build_forward()
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/build.py", line 70, in build_forward
>     state = op_create(*args)
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/ops/__init__.py", line 25, in op_create
>     return op_types[layer_type](*args)
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/ops/baseop.py", line 42, in __init__
>     self.forward()
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/ops/convolution.py", line 66, in forward
>     temp = self.batchnorm(self.lay, temp)
>   File "/home/nataniel/Documents/gatech/research/darkflow/net/ops/convolution.py", line 78, in batchnorm
>     is_training = layer.h['is_training'])
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
>     return func(*args, **current_args)
> TypeError: batch_norm() got an unexpected keyword argument 'initializers'
> 

I am using TF version 0.12.0-rc0 and python 2.7

Thanks !

**Comment by thtrieu** [comment]
for 0.12.0-rc0, `initializers` should be `param_initializers`

**Comment by natanielruiz** [comment]
Awesome it works ! Thanks. Also congratz on your work.

**Comment by thtrieu** [comment]
Nice to meet you Nataniel,

It is 425 = 5 x (5 + 80) = num x (coords + 1 + classes).
You can see that in the darknet source code even though the paper has not
been published yet.
