### ISSUE TITLE
inference results not right

### ISSUE THREAD

**Issue by vscv** [thtrieu/darkflow#155]
Here some test I used:

`./flow` --test test/ --model cfg/tiny-yolo-voc.cfg --load `bin/tiny-yolo-voc.weights`
![dog](https://cloud.githubusercontent.com/assets/18000764/24849008/28c82fe6-1dfc-11e7-9199-755e7de0f080.jpg)

`./flow --test test/ --model cfg/v1.1/tiny-yolov1.cfg --load bin/tiny-yolo-v1.1.weights`
![dog](https://cloud.githubusercontent.com/assets/18000764/24849016/3bb7cdb4-1dfc-11e7-9bca-ad1bd5c9f644.jpg)

`./flow --test test/ --model cfg/v1.1/tiny-yolov1.cfg --load bin/tiny-yolo-v1.1.weights --gpu 0.5`
![dog](https://cloud.githubusercontent.com/assets/18000764/24849038/566f2b98-1dfc-11e7-9916-94995b6ac489.jpg)

I just clone `git clone https://github.com/thtrieu/darkflow` and down weights from this repo. Did I miss something? 
Thanks for your help.

**Comment by thtrieu** [comment]
There is a bug in latest commit, I fixed it. Please re-pull, sorry for this inconvenience.

**Comment by vscv** [comment]
Thank you, it works now :)
