### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by johnsonice** [thtrieu/darkflow#157]
Seems there is a small bug in net.build.py while running prediction process in python. 

`
  File "/Users/huang/Dev/projects/darkflow_all/darkflow/net/build.py", line 109, in setup_meta_ops
    self.writer = tf.summary.FileWriter(self.FLAGS.summary + 'train')
`

**Comment by thtrieu** [comment]
So `self.FLAGS.summary` is `NoneType`?
What is the steps & commands that lead to this error?

**Comment by johnsonice** [comment]
I was just trying out the sample code in python:
```
from net.build import TFNet
import cv2
options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1}
tfnet = TFNet(options)
imgcv = cv2.imread("./test/test.jpg")
result = tfnet.return_predict(imgcv)
print(result)
```

I just tried get rid of self.FLAGS.summary, runs fine.

**Comment by Abhi001vj** [comment]
How did you get rid of self.FLAGS.summary.

**Comment by abagshaw** [comment]
Yeah this is probably a bug. When I added the ability to use darkflow from another python app I put a dictionary of default FLAGS in build.py. If any new flags are added and necessary for operation their default values need to be added here, https://github.com/thtrieu/darkflow/blob/master/net/build.py#L41

**Comment by Abhi001vj** [comment]
Thank you that solved the problem.Can we use this in python 2.7 app.
