### ISSUE TITLE
็How to limit check point file

### ISSUE THREAD

**Issue by beebrain** [thtrieu/darkflow#158]
I have many check point file in check point folder.
How to limit check point file?

**Comment by imian00** [comment]
you can find many options by typing python flow --help
and maybe --keep [MAX_NUM_OF_CKPT_FILES] options will do that
for example,
python flow --train --model cfg/your_model.cfg --load bin/your_weights.weights ...other options... --keep 5
will keep your checkpoint files no more than 5

**Comment by beebrain** [comment]
Thank you
