### ISSUE TITLE
Problem with my prediction

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#159]
Hello

Currently I am testing my training, and I noticed a stranges behaviors:
1- I have 2 images with the same objects, except that the object in the first image is not at the same location in the second images, the result is taht in the first image it detect the object and in the second it does't detect the object

How can I explain that ??

Thanks,

**Comment by thtrieu** [comment]
If you are using YOLOv1, this is possible since YOLOv1 is not fully convolutional, hence translation invariance is not a property of YOLOv1.

**Comment by kamelbouyacoub** [comment]
Hello

No, I am using YOLOV2 not V1, that's why I don''t understand, but why you said that YOLOV1 is not convolutional, I saw the architecture of YOLOV1 and I saw that it contain some Convolutional neural network, and in the literature this layers help us to detect the pixels in differents positions, can you give me some more informations 

Thanks
