### ISSUE TITLE
How Yolo calculate P(Object) 

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#160]
Hello

I am newbie in image processing 

In the Paper I understand that the image is splited in 13X13 boxes and in each boxes we calculate P(Object), but How can we calculate that, how can the model know if there is an object in this boxe or not, please I need help to understand that

Thanks,

**Comment by shamanez** [comment]
Can anyone explain this. Specially how to calculate P(object) and P(class/object)

**Comment by thtrieu** [comment]
All these values are decoded from the output volume of YOLO net. You can look at the post-processing implementation in this repo to understand the details.
