### ISSUE TITLE
Parsing network output in C++

### ISSUE THREAD

**Issue by luketg8** [thtrieu/darkflow#164]
This is a great repository and has performed well for me with the Python API. I am however also interested in using this with C++ and I have managed to load my image and feed it to the network, however I was wondering if anybody had already taken the time to parse the output received to actually obtain the bounding boxes?
(I am using a protobuf file that I generated from the tiny-yolo.cfg and standard weights)

**Comment by abagshaw** [comment]
Just an idea, you might be able to use some of the existing C code (from the original darknet repository) to do your post processing. See: https://github.com/pjreddie/darknet/blob/e610c7de9aa90dbaa6a4ec14189ac45c8058a495/src/detection_layer.c

**Comment by thtrieu** [comment]
Or you can look at cython implementation in this repo https://github.com/thtrieu/darkflow/tree/master/darkflow/cython_utils

**Comment by luketg8** [comment]
Thank you! I will have a look at that today, I haven't had much experience with calling Cython from C++ before but I'll definitely look into it today. Thanks again!

**Comment by mrjc1400** [comment]
@luketg8 Did you ever parse the output from this?

**Comment by Fattouh92** [comment]
@luketg8 I know this is pretty old but did you manage to parse the output and how was the output shape in c++ I have the same problem and was thinking of following cython implementation
