### ISSUE TITLE
the accuracy of comparing darknet with darkflow

### ISSUE THREAD

**Issue by gerori** [thtrieu/darkflow#165]
I use the darkent to detect my video. I can find darknet can recognize all the person, but the darkflow can not when the person is smaller than other person. 
ps: the same conf file and weight file

**Comment by gerori** [comment]
I use the darknet to detect my video. I find that darknet can recognize all the person, but the darkflow can not when the person is smaller than other person.
ps: the same cfg file and weight file

**Comment by jcarletgo** [comment]
Maybe related to Issue #147   
Did you try messing with the threshold value?

**Comment by thtrieu** [comment]
Please refer to https://github.com/thtrieu/darkflow/issues/147
