### ISSUE TITLE
Trained model fails to detect anything

### ISSUE THREAD

**Issue by traw1234** [thtrieu/darkflow#167]
I trained a model with one class (people) and changed the classes and filters accordingly (1, 30) but when I attempt to run the model, it never detects anything. I have played with the threshold but there is still no change. During training, the loss fluctuated between 2.7 and 0.5 and the moving ave loss stayed right at about 2. It definitely seemed to converge. Command I tried to run is:

`python3 flow --model cfg/tiny.cfg --load 4250 --gpu 0.3 --demo camera --threshold .001`

**update**
I have tried retraining yolo-tiny-voc with a trainer and from the previously defined weights and it still fails to recognize anything. I also changed the number of classes to see if having only one class was the issue but still nothing. Is there an issue with yolo training? I get this error once it completes the training:
`Checkpoint at step 21400
Training finished
Exception ignored in: <bound method BaseSession.__del__ of
<tensorflow.python.client.session.Session object at 0x7f4727dc88>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 582, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
`

**Comment by thtrieu** [comment]
You may want to look at https://github.com/thtrieu/darkflow/issues/80 and continue the thread there. For one class, I believe a loss of 2.0 is still too big to be called convergence. Try reduce learning rate and continue training for more.

**Comment by fogonthedowns** [comment]
Whats the point of the overfitting exercise? Has training changed since this was last closed/answered?

**Comment by fogonthedowns** [comment]
Also, at what loss is typical of "convergence"? I ran 1000 epochs which resulted in very very low loss ~0.1% However my bounding boxes were only drawn around images the model had previously seen - I suspect either my training set of data isn't large enough or that the model is way overfit and it will only match images it has already seen. 

1. Whats an acceptable size of training images to use? I believe I have 200
2. At what loss does "convergence" typically take place?
3. Does this library divide my training images into Test, Train and Verify directories? How can I fight against overfitting?
