### ISSUE TITLE
yolo9000 failed on predict

### ISSUE THREAD

**Issue by pczzy** [thtrieu/darkflow#169]
use tfnet = TFNet(options)
options = {"model": BASE+"/cfg/yolo9000.cfg", "load": BASE+"/bin/yolo9000.weights", "threshold": 0.4}
and object detect return nothing.

**Comment by abagshaw** [comment]
YOLO9000 is not yet supported in darkflow. Hopefully it will be soon! Stay tuned here: https://github.com/thtrieu/darkflow/issues/49

**Comment by abagshaw** [comment]
@thtrieu This can be closed - we'll consolidate to one issue on YOLO9000.
