### ISSUE TITLE
ImageNet Dataset Not Compatible? 

### ISSUE THREAD

**Issue by borasy** [thtrieu/darkflow#174]
Hey guys,
I try to use Imagenet dataset to train but i got error of "Data of 0 instances". 
I believe .xml annotations of imagenet and pascal voc are the same, but why it still doesn't work?
The only different i noticed is in imagenet the files are something like: 'n03343560_69.xml' and 'n03343560_149.xml', while in VOC it's very neatly like: '000001.xml','000002.xml'. Does ordering the files really matter?

**Comment by borasy** [comment]
Nvm, i've solved it. 
For someone who might face the same problem.
in Imagenet dataset, the filename tag in .xml files don't contain file extension while VOC do.
Ex: Imagenet: <filename>n03343560_149</filename>
VOC: <filename>000001.jpg</filename>
Just add '.jpg' to the filename tag in imagenet set and it should work

**Comment by bjornamr** [comment]
@borasy 
Hi, would it be possible to upload your weights and cfg for this?
I tried, but it did not spit out anything for me.

**Comment by borasy** [comment]
@bjornamr i used the yolo.weights uploaded by this git author [here](https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU). 
For the cfg i just change the final layer to the desired number of categories that u want.

...
[convolutional]
size=1
stride=1
pad=1
**filters=35**
activation=linear

[region]
anchors = 0.738768,0.874946,  2.42204,2.65704,  4.30971,7.04493,  10.246,4.59428,  12.6868,11.8741
bias_match=1
**classes=2**
coords=4
num=5
softmax=1
jitter=.2
rescore=1
...

**Comment by bjornamr** [comment]
@borasy 
Did you only train for 2 classes, not the whole 200 classes in imagenet-det?

**Comment by borasy** [comment]
@bjornamr I only trained on 2 classes not 200. So I don't have checkpoints for that. Sorry

**Comment by lusiliang93** [comment]
How did you modify the xml so that it can add ".jpg" in each name? Thanks  a lot！ @borasy

**Comment by lusiliang93** [comment]
Hi, I put all the annotations together inside the folder called "annotations" and all the images together inside the folder called "image", which is also inside the folder "annotations". Then, for each .xml, the field of "folder" is changed into "image" and the field of "filename" is changed into "the image number. JPEG". However, I still get the 'NoneType' object has no attribute 'shape'. Could you give me some insights? The command I have is "flow --model cfg/tiny-yolo-voc-7c.cfg --load bin/tiny-yolo-voc.weights --train --annotation annotations/ --dataset annotations/Image" Thanks a lot!
