### ISSUE TITLE
ModuleNotFoundError: No module named 'cython_utils.cy_yolo_findboxes'

### ISSUE THREAD

**Issue by anonym24** [thtrieu/darkflow#175]
Hi, I get an error  `ModuleNotFoundError (No module named 'cython_utils.cy_yolo_findboxes')` when running:

```
$ ./flow --model cfg/yolo-voc.cfg --load bin/yolo-voc.weights --savepb --verbalise=True
Traceback (most recent call last):
  File "./flow", line 3, in <module>
    from net.build import TFNet
  File "/home/osboxes/Desktop/tensorflow-master/yolo-test/darkflow-master/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/home/osboxes/Desktop/tensorflow-master/yolo-test/darkflow-master/net/framework.py", line 1, in <module>
    from . import yolo
  File "/home/osboxes/Desktop/tensorflow-master/yolo-test/darkflow-master/net/yolo/__init__.py", line 2, in <module>
    from . import test
  File "/home/osboxes/Desktop/tensorflow-master/yolo-test/darkflow-master/net/yolo/test.py", line 6, in <module>
    from cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'cython_utils.cy_yolo_findboxes'

```

How to solve it?

**Comment by beebrain** [comment]
Try to build the cython function.
```
cd ./cython_utils
python3 setup.py build_ext --inplace
cd ..
```

**Comment by anonym24** [comment]
yeah, I should have read/find better

**Comment by ahkarami** [comment]
Dear @anonym24 & @beebrain, 
I have faced your problem. Would you please kindly help me to address it?
I have used the below command for installation of _darkflow_:
`pip3 install --upgrade -e .`
But the `ModuleNotFoundError: No module named 'cython_utils.cy_yolo_findboxes` error occurred for me. 
And in the `cython_utils` directory there isn't any `setup.py` file for installing it inplace.

**Comment by ahkarami** [comment]
Note: I have also installed _darkflow_ with `python3 setup.py build_ext --inplace`, but the error is remained.

**Comment by beebrain** [comment]
Do you have cython package?
Install cython package and build it.
Let me know if you get the error message while building.

**Comment by ahkarami** [comment]
@beebrain, 
Yes, I have installed cython successfully via `pip3 install --upgrade Cython`.
But the error is remained.

**Comment by beebrain** [comment]
Could you run setup.py on root darkflow directory ( you can see setup.py )

**Comment by wahabrind** [comment]
after i run pip instal -e . in cython_utils folder i get following error.
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: E:\artificial intelligence\darkflow\darkflow\cython_utils

**Comment by ControlPlusGit** [comment]
Estou enfrentando o mesmo problema: ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'.
Alguém, por gentileza poderia me ajudar? Agradeço de antemão!
