### ISSUE TITLE
Crash after install

### ISSUE THREAD

**Issue by rtrahms** [thtrieu/darkflow#18]
Hi -
I have some experience using Darknet/YOLO, and was excited to learn that you have reimplemented it using TensorFlow.  I have TensorFlow 0.12rc1 installed, and Python2.7.  TF examples work.

I cloned your repository, and grabbed cfg and weights for tiny-yolo.  When I attempted to run it using your instructions, however, I get an error:

rob@skynet1:~/darkflow$ ./flow --model yolo-voc.cfg --load yolo-voc.weights
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.8.0 locally
Parsing yolo-voc.cfg
Loading yolo-voc.weights ...
Successfully identified 268632452 bytes
Finished in 0.0848739147186s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/rob/darkflow/net/build.py", line 49, in __init__
    self.build_forward()
  File "/home/rob/darkflow/net/build.py", line 69, in build_forward
    state = op_create(*args)
  File "/home/rob/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/home/rob/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/home/rob/darkflow/net/ops/convolution.py", line 66, in forward
    temp = self.batchnorm(self.lay, temp)
  File "/home/rob/darkflow/net/ops/convolution.py", line 78, in batchnorm
    is_training = layer.h['is_training'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
TypeError: batch_norm() got an unexpected keyword argument 'initializers'
rob@skynet1:~/darkflow$ 

I am trying to determine if this is a TF bug or otherwise.  Any clues?
Thanks,
Rob

**Comment by kanishkg** [comment]
I got the same error with Python 3

**Comment by thtrieu** [comment]
@rtrahms @kanishkg  Clearly you guys did not search for this issue. People has reported about it for a couple of times in my issue track :D. Answer: For your TF version, `initializers` should be `param_initializers`.

Maybe I'll do something about it

**Comment by thtrieu** [comment]
Since I am using python 2, the syntax might need a little bit adjustment. I'll work on that too

**Comment by thtrieu** [comment]
The `thresh` problem is something I'm scratching my head with!  It is very trivial but the only I was able to solve it is to look into the `.cfg` file, look for the line that says `thresh : 0.6` or something similar, delete all excess spaces. E.g. `thresh   :    0.6` would turn to `thresh:0.6`. This should be solved by a single python `strip`, but I tried and I didnot work as expected, So I decided to just fix the `cfg` file.

**Comment by thtrieu** [comment]
P/S this repo needs a lot of fixing and I'm working on that. Thanks for your ping

**Comment by rtrahms** [comment]
That is a weird parser bug - it did move me forward.  Thanks for the info.
The test did segfault out, but managed to create the output images with bounding boxes - so I am calling this a qualified success!

**Comment by rtrahms** [comment]
Forwarding 8 inputs ...
Total time = 2.15256094933s / 8 inps = 3.71650335964 ips
Post processing 8 inputs ...
Total time = 0.418047189713s / 8 inps = 19.1365955731 ips
Segmentation fault (core dumped)
rob@skynet1:~/darkflow$

**Comment by thtrieu** [comment]
`tensorflow` is using up too much space I guess, but 8 images a time and segmentation fault is something I would not expect, even on my CPU.
With my normal CPU, I would be able to process up to 64 images per batch, and even **run a demo** with 7FPS ...

**Comment by CoderEugene** [comment]
when I run --demo camera on my GPU(GTX 860), I can only get 6 fps on darkflow(yolo v2),  but original darknet can get up to 13fps

**Comment by thtrieu** [comment]
This can happen because of inefficient implementation of post-processing (my responsibility). Working on that at the moment, preferably will transfer this part to `C` but will not be in this week, really sorry for that. 

In the mean time, please update the code since I've updated my manual implementation of `reorg` to `tensorflow`'s built-in `extract_image_patches`, hope that helps a little (hint: not help at all on my CPU though).

**Comment by CoderEugene** [comment]
Thank you for your comments, I updated the code, looks still no help, but I'm looking forward to your update

**Comment by rtrahms** [comment]
Thanks for the explanation of the camera performance issue - I also look forward to the update!
By the way, its great that you've made this port - very much appreciated.
