### ISSUE TITLE
add note to origial yolo-tiny.cfg

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [thtrieu/darkflow#182]
I think a simple link to https://github.com/cvjena/darknet/blob/master/cfg/yolo-tiny.cfg would be very helpful to avoid some more google debugging.

**Comment by thtrieu** [comment]
Thanks.
`.cfg` in this repo and `.weights` in google drive (see README) matches perfectly. Other than that, I give no guarantee of correspondence.
