### ISSUE TITLE
Extract anchors from .pb

### ISSUE THREAD

**Issue by sh3raawii** [thtrieu/darkflow#184]
I managed to generate protobuff (.pb) model using the --savepb option, but i don't know if the anchors defined in the config file (.cfg) are saved somewhere in the .pb since it's saved in binary format, 
and how to extract them ? instead of the ugly hack of saving the anchors in a separate text file, Thanks for this awesome work.

**Comment by abagshaw** [comment]
No, the anchors are not currently saved in the `.pb` file as far as I know. I was looking into something similar, see https://github.com/thtrieu/darkflow/issues/143#issuecomment-292794853

It would be great if somehow the variables I mentioned in that post could be embedded in the the `.pb` file and then extracted later on to make things easier (and have single file portability). Exporting all `meta` information to a file and the re-loading it seems like the second-best option to me. I'm working on implementing that right now (and also enabling loading from a `.pb` in darkflow)

**Comment by abagshaw** [comment]
When https://github.com/thtrieu/darkflow/pull/191 is pulled then running `--savepb` will also generate a `.meta` file alongside the `.pb` file. This `.meta` file is a JSON dump of everything in the `self.meta` dictionary that contains anchors, labels and other info necessary for post-processing. You can parse the `.meta` file and pull in whatever you need to do post processing on your own. Ideally everything in the `.meta` file could be embedded in the `.pb` file and then extracted when needed, but I'm not sure how to do that/if that can be done.

**Comment by sh3raawii** [comment]
Great, hope to see #191 pulled anytime soon.
i will look into embedding everything in the .pb file in my free time.

**Comment by thtrieu** [comment]
Close since the PR is merged
