### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'net/yolo/parse-history.txt'

### ISSUE THREAD

**Issue by wcy0319** [thtrieu/darkflow#185]
Hello.
I run the comma './flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --train --dataset ./data/VOC2012/JPEGImages --annotation ./data/VOC2012/Annotations' ,then get the error.how can i get the 'net/yolo/parse-history.txt'?

**Comment by abagshaw** [comment]
Can you see if `parse-history.txt` exists in `./darkflow/net/yolo/` because it's possible I forgot to update the path for that when putting everything in the `./darkflow/` folder.

**Comment by thtrieu** [comment]
Clearly it is not updated in https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolo/data.py#L17

**Comment by wcy0319** [comment]
thanks for @abagshaw @thtrieu
