### ISSUE TITLE
--threshold option does not do anything

### ISSUE THREAD

**Issue by johnsonice** [thtrieu/darkflow#190]
I am just trying out some sample command. 
./flow --test test/ --model cfg/yolo.cfg --load bin/yolo.weights --threshold .1

the --threshold option doesn't seems to do anything. it predicts the same bounding box no matter what value I put as threshold. 

I changed "thresh = " in cfg file, it works fine. 

are we disabling --threshold option?

**Comment by mastersplinter** [comment]
I'm able to replicate the issue. 

I think issue is that threshold in the cy_yolo_2_findpoxes.pyx file, in the box_constructor function the threshold is obtained from meta:
`float  threshold = meta['thresh']`
but in the __init__ of build.py, the threshold set in flags isn't set to be used in place of the thresh from the config file:
`		self.meta = darknet.meta
		self.FLAGS = FLAGS`

A workaround is to set the threshold in the cfg file using thresh, but not explicitly setting it when you call ./flow may cause unexpected behaviour too.

**Comment by thtrieu** [comment]
This might be solved in https://github.com/thtrieu/darkflow/commit/945749cec6102bc6e4ae9c492205398efde9ccd9

The solution is simply overwrite `meta['thresh']` if `FLAGS.threshold` is used with a positive threshold (default to negative)
