### ISSUE TITLE
Heights and Widths of tensors get flipped in Route layer

### ISSUE THREAD

**Issue by oulutan** [thtrieu/darkflow#192]
This can be reproduced by changing the input shape into any shape that is not a square(i.e. h != w) and using any configuration files. In my case I am using the original YOLO configuration with height:720, width:1280 and the [assert](https://github.com/thtrieu/darkflow/blob/22ac87a3cb1b585d62c5106aab2f203ead4b445f/darkflow/utils/process.py#L299) fails in cfg_yielder while trying to combine 22x40x1024 with 40x22x256 tensor.

**Comment by EdgarsGars** [comment]
Having same issue with 640x320 w and h are flipped. Commenting assert or fliping them manualy - later fails with shape mismatch.

**Comment by thtrieu** [comment]
Thank you, I fixed this in https://github.com/thtrieu/darkflow/commit/83fc75128cb57186566263114bb86e39953b02b3
