### ISSUE TITLE
No guidelines for training own model

### ISSUE THREAD

**Issue by nitish11** [thtrieu/darkflow#193]
Ref :  https://github.com/thtrieu/darkflow#training-new-model

For training new model, we can use option --dataset and --annotation. 

But, there are two important questions, which are not well documented.
1. What should be the format of annotation file?
2. What should be the folder structure of dataset path?

For each image in training dataset, we need class as well as bounding box coordinates. We need to have some format as below.

`{"image_path"="dataset/a.jpg", "label": "dog", "topleft": {"x": 71, "y": 263}, "bottomright": {"x": 193, "y": 353}}`

**Comment by beebrain** [comment]
Hi i try to train yolo with my own data.
It have 2 classes. I push all my image  in folder and edit dataset to that folder. For annotation i create xml file with boundbox program and put it into annotation folder.

**Comment by nitish11** [comment]
@beebrain : Hey, thanks for the reply.
Could you please share a sample of xml file used by you.

**Comment by beebrain** [comment]
`<annotation>
	<folder>VOC2007</folder>
	<filename>000010.jpg</filename>
	<source>
		<database>The VOC2007 Database</database>
		<annotation>PASCAL VOC2007</annotation>
		<image>flickr</image>
		<flickrid>227250080</flickrid>
	</source>
	<owner>
		<flickrid>genewolf</flickrid>
		<name>whiskey kitten</name>
	</owner>
	<size>
		<width>354</width>
		<height>480</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>horse</name>
		<pose>Rear</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>87</xmin>
			<ymin>97</ymin>
			<xmax>258</xmax>
			<ymax>427</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>133</xmin>
			<ymin>72</ymin>
			<xmax>245</xmax>
			<ymax>284</ymax>
		</bndbox>
	</object>
</annotation>
`

**Comment by mastersplinter** [comment]
I was was planning on updating the readme, but thought it might be useful to get you started.

The XML needs to be in the same format as the Pascal VOC dataset.

From your home directory, if you download the Pascal VOC dataset:
`curl -O https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar`

This should allow you to initiate the training using something like:
./flow --model cfg/yolo.cfg --train --dataset "~/VOCdevkit/VOC2007/JPEGImages" --annotation "~/VOCdevkit/VOC2007/Annotations"

The annotations that come with VOC look like this:
`<annotation>
	<folder>VOC2007</folder>
	<filename>000001.jpg</filename>
	<source>
		<database>The VOC2007 Database</database>
		<annotation>PASCAL VOC2007</annotation>
		<image>flickr</image>
		<flickrid>341012865</flickrid>
	</source>
	<owner>
		<flickrid>Fried Camels</flickrid>
		<name>Jinky the Fruit Bat</name>
	</owner>
	<size>
		<width>353</width>
		<height>500</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>dog</name>
		<pose>Left</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>48</xmin>
			<ymin>240</ymin>
			<xmax>195</xmax>
			<ymax>371</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Left</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>8</xmin>
			<ymin>12</ymin>
			<xmax>352</xmax>
			<ymax>498</ymax>
		</bndbox>
	</object>
</annotation>
`

**Comment by mastersplinter** [comment]
@nitish11 I have updated the readme with part of my above example and raised a pull request #194.
@thtrieu I think this can be closed if you're happy with the changes in #194

**Comment by nitish11** [comment]
@mastersplinter  : thanks :+1:
