### ISSUE TITLE
Don't have Image with box in out folder

### ISSUE THREAD

**Issue by beebrain** [thtrieu/darkflow#196]
I train with my own data set. and test with this command.
`flow --test test/ --model cfg/yolo-hand.cfg --load -1 --gpu 0.8 --json`
but it have json file only in test/out folder.
How to config for write the output image?

**Comment by beebrain** [comment]
Sorry for my Question. I have an answer. When I have a json flag darkflow script write json output file only. And if you want have an output image you can remove json flag from command script.
But, how to config for write all both output?

**Comment by bousejin** [comment]
With the json flag, my otput json files have just ']' character on them and without json flag my output images are just copies of test images file with no bounding box on them. Am I doing it wrong? I have used this command: 
./flow --test test/ --model cfg/tiny-yolo-voc.cfg --json

**Comment by beebrain** [comment]
Hi bousejin

**Comment by bousejin** [comment]
Hi beebrain, Thank you. I forgot to load weights. With the command below, now json output files have something in it.
./flow --test test/ --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --json

**Comment by benn94** [comment]
@beebrain, i encountered the same problem when i train a small dataset of 15 pictures (udacity autti dataset) and test on the same dataset. I used tiny-yolo-voc.cfg and tiny-yolo-voc.weights. Classes = 3, Filters = 40; width=416 and height = 416. 

training cmd
```
python3.5 flow
--model cfg/tiny-yolo-voc-3c.cfg
--load bin/tiny-yolo-voc.weights
--train
--annotation dataset/autti/autti_sample_annotations
--dataset dataset/autti/autti_sample_images
--gpu 0.8
```

testing cmd
```
python3.5 flow
--imgdir dataset/autti/autti_sample_images
--model cfg/tiny-yolo-voc-3c.cfg
--load bin/tiny-yolo-voc.weights
--gpu 0.8
```
