### ISSUE TITLE
Object detection problem 

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#197]
Hello 

I am trying to detect some componant that are composed with other sub-componant, the problem is sometimes in test detection, instead to detect the componant it's only detect the sub componant, for exmaple: i have 2 classes, a forest and eyes of a tree and most of the case, when I give to the program an image of a tree, it display to me that the tree is a forest, is it a problem related to the amount of the images training ? I need some helps and advices about this situation 

Thanks,

**Comment by mastersplinter** [comment]
per your comment:
>  is it a problem related to the amount of the images training ?

This is probably the issue, or it's something to do with the parameters of the net you've trained, or maybe to do with the threshold you're setting.

I don't think this is an issue with darkflow - maybe take this discussion to stackoverflow?

**Comment by thtrieu** [comment]
Close due to inactivity.
