### ISSUE TITLE
Training custom data problem

### ISSUE THREAD

**Issue by karta0807913** [thtrieu/darkflow#199]
Hello
I tried to train my data with the following command

`./flow --model cfg/yolo-new.cfg --annotation data/xml --dataset data/image/ --gpu 0 --batch 16 --train`

and I got an error

Traceback (most recent call last):
  File "./flow", line 56, in <module>
    print('Enter training ...'); tfnet.train()
  File "/home/e419/darkflow/darkflow/net/flow.py", line 50, in train
    fetched = self.sess.run(fetches, feed_dict)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [40,169,5,2] vs. [16,169,5,2]
         [[Node: Maximum = Maximum[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](sub, _recv_Placeholder_5_0)]]

Caused by op u'Maximum', defined at:
  File "./flow", line 45, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/e419/darkflow/darkflow/net/build.py", line 63, in __init__
    self.setup_meta_ops()
  File "/home/e419/darkflow/darkflow/net/build.py", line 106, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "/home/e419/darkflow/darkflow/net/help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "/home/e419/darkflow/darkflow/net/yolov2/train.py", line 78, in loss
    intersect_upleft   = tf.maximum(floor, _upleft)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1313, in maximum
    result = _op_def_lib.apply_op("Maximum", x=x, y=y, name=name)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [40,169,5,2] vs. [16,169,5,2]
         [[Node: Maximum = Maximum[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](sub, _recv_Placeholder_5_0)]]

I notice that when I increase the batch size to 40, the error 

Incompatible shapes: [40,169,5,2] vs. [16,169,5,2] => Incompatible shapes: [100,169,5,2] vs. [40,169,5,2]

P.S. The cfg/yolo-new.cfg  file is the same as the cfg/yolo-voc.cfg  file

**Comment by beebrain** [comment]
Try to reduce batch size.

**Comment by karta0807913** [comment]
thanks for your answer!
I change my batch size to 1 then I get another error 

> Traceback (most recent call last):
>   File "./flow", line 56, in <module>
>     print('Enter training ...'); tfnet.train()
>   File "/home/e419/darkflow/darkflow/net/flow.py", line 50, in train
>     fetched = self.sess.run(fetches, feed_dict)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
>     run_metadata_ptr)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
>     feed_dict_string, options, run_metadata)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
>     target_list, options, run_metadata)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 21125 values, but the requested shape requires a multiple of 8450
>          [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]
> 
> Caused by op u'Reshape', defined at:
>   File "./flow", line 45, in <module>
>     tfnet = TFNet(FLAGS)
>   File "/home/e419/darkflow/darkflow/net/build.py", line 63, in __init__
>     self.setup_meta_ops()
>   File "/home/e419/darkflow/darkflow/net/build.py", line 106, in setup_meta_ops
>     if self.FLAGS.train: self.build_train_op()
>   File "/home/e419/darkflow/darkflow/net/help.py", line 15, in build_train_op
>     self.framework.loss(self.out)
>   File "/home/e419/darkflow/darkflow/net/yolov2/train.py", line 56, in loss
>     net_out_reshape = tf.reshape(net_out, [-1, H, W, B, (4 + 1 + C)])
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2510, in reshape
>     name=name)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/home/e419/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
>     self._traceback = _extract_stack()
> 
> InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 21125 values, but the requested shape requires a multiple of 8450
>          [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]

Is my data problem?

**Comment by karta0807913** [comment]
I change my data to VOC 
get the same error 

`python3 flow --model cfg/yolo-new.cfg --annotation VOC2012/Annotations/ --dataset VOC2012/JPEGImages/ --gpu 0 --batch 1 --train`

**Comment by beebrain** [comment]
Please show your cfg.
Try to change level, amount fillter. Drakflow cant assign tensor to your memory(out of memory).

**Comment by karta0807913** [comment]
The cfg file
[https://drive.google.com/open?id=0B3CjQXDi2Di-V0dqUFRXcXBzdkE](url) 

`cat /proc/meminfo`

> MemTotal:       16342192 kB
> MemFree:          321872 kB
> MemAvailable:    7398468 kB

GPU and etc
> name: GeForce GTX 1080
> major: 6 minor: 1 memoryClockRate (GHz) 1.898
> pciBusID 0000:02:00.0
> Total memory: 7.92GiB
> Free memory: 7.81GiB
> 2017-04-30 22:42:03.726955: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x5527bb0
> 2017-04-30 22:42:03.946517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 1 with properties:
> name: GeForce GTX 1080
> major: 6 minor: 1 memoryClockRate (GHz) 1.898
> pciBusID 0000:01:00.0
> Total memory: 7.92GiB
> Free memory: 1.21GiB
> 2017-04-30 22:42:03.947288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 1
> 2017-04-30 22:42:03.947304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y Y
> 2017-04-30 22:42:03.947311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 1:   Y Y
> 2017-04-30 22:42:03.947320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
> 2017-04-30 22:42:03.947326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
> Finished in 11.498409509658813s
> 
> Enter training ...
> Dataset of 22263 instance(s)
> Training statistics:
>         Learning rate : 1e-05
>         Batch size    : 1
>         Epoch number  : 1000
>         Backup every  : 2000
> Traceback (most recent call last):
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
>     return fn(*args)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
>     status, run_metadata)
>   File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
>     next(self.gen)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 21125 values, but the requested shape requires a multiple of 8450
>          [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "flow", line 56, in <module>
>     print('Enter training ...'); tfnet.train()
>   File "/home/e419/darkflow/darkflow/net/flow.py", line 50, in train
>     fetched = self.sess.run(fetches, feed_dict)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
>     run_metadata_ptr)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
>     feed_dict_string, options, run_metadata)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
>     target_list, options, run_metadata)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 21125 values, but the requested shape requires a multiple of 8450
>          [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]
> 
> Caused by op 'Reshape', defined at:
>   File "flow", line 45, in <module>
>     tfnet = TFNet(FLAGS)
>   File "/home/e419/darkflow/darkflow/net/build.py", line 63, in __init__
>     self.setup_meta_ops()
>   File "/home/e419/darkflow/darkflow/net/build.py", line 106, in setup_meta_ops
>     if self.FLAGS.train: self.build_train_op()
>   File "/home/e419/darkflow/darkflow/net/help.py", line 15, in build_train_op
>     self.framework.loss(self.out)
>   File "/home/e419/darkflow/darkflow/net/yolov2/train.py", line 59, in loss
>     net_out_reshape = tf.reshape(net_out, [-1, H, W, B, (4 + 1 + C)])
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2510, in reshape
>     name=name)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/home/e419/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
>     self._traceback = _extract_stack()
> 
> InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 21125 values, but the requested shape requires a multiple of 8450
>          [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]

**Comment by beebrain** [comment]
Could i share my experience. I trained mydata with GTX 750 and 2GB. My GPU have a little memory. When I trained my own data i got the message like you in this line
```
Total memory: 1.98GiB
Free memory: 1.68GiB
```
But you have 2 GPU . One of them have Free memory only  1.21GiB. and i don't know why.

**Comment by denisli** [comment]
See #148 

In your .cfg, change your line `filters=125` to `filters=50`, where the 50 comes from #num * (#classes + 5) = 5 * (5 + 5) = 50.

**Comment by nitish11** [comment]
The above solution worked for me also. Follow https://github.com/thtrieu/darkflow/issues/148

In the last conv. layer, filters =  #num * (#classes + 5)
```

[convolutional]
size=1
stride=1
pad=1
filters=40
activation=linear

[region]
anchors = 0.738768,0.874946,  2.42204,2.65704,  4.30971,7.04493,  10.246,4.59428,  12.6868,11.8741
bias_match=1
classes=3
coords=4
num=5
```

For the above example,  filters= 5 * (3+5) = 40

**Comment by karta0807913** [comment]
Oh!
I got it
Thank you very much!!
