### ISSUE TITLE
Edit label.txt, no effect

### ISSUE THREAD

**Issue by turingyizhu** [thtrieu/darkflow#200]
Hi,

Thanks for the tensorflow implementation. I try to adapt the code for my research use as a human detector, so I modify the label.txt to have only one class, which is person. But the predicted image still generates other classes' bounding boxes. Could anyone point out which file I need to change or look at? Thanks.

**Comment by beebrain** [comment]
Check your cfg model and chang class in cfg model to 1. Recalculate the output node again.
