### ISSUE TITLE
What is a problem on my confidence value.

### ISSUE THREAD

**Issue by beebrain** [thtrieu/darkflow#201]
I trained a new dataset. It have only one class.
I test with same dataset ,
The model can detect the object but the confidence value should have between 0 and 1.
This my json file

`[{"label": "Hand","confidence": 1.11,"topleft": {"x": 118, "y": 58},"bottomright": {"x": 427,"y": 537}},]`
`[{"label": "Hand","confidence": 1.03,"topleft": {"x": 173, "y": 47},"bottomright": {"x": 481,"y": 490}},]`

**Comment by thtrieu** [comment]
Yolov1 confidence is produced with no sigmoid activation, and trained using L2-loss. So a confidence bigger than 1.0 is normal. Please refer to the paper for more details.
