### ISSUE TITLE
Using darknet19 pre-trained model fails

### ISSUE THREAD

**Issue by inkrement** [thtrieu/darkflow#202]
I tried to use the pre-trained darknet19 & darknet19_488 models, but I always get 

```
Traceback (most recent call last):
  File "object_detection.py", line 29, in <module>
    result = tfnet.return_predict(img)
  File "....b/python3.6/site-packages/darkflow/net/flow.py", line 73, in return_predict
    im = self.framework.resize_input(im)
AttributeError: 'framework' object has no attribute 'resize_input'
```

Is it somehow possible to use them?

**Comment by thtrieu** [comment]
Currently, `darkflow` only works with YOLOv1 and YOLOv2, meaning the `.cfg` must have the last layer being either `[detection]` or `[region]`. If this is not the case, then the config you are working with is not YOLO, which leads to this unhandled error message.
