### ISSUE TITLE
Readme file needs a section for steps to train on own data

### ISSUE THREAD

**Issue by ahmedbaracat** [thtrieu/darkflow#203]
First, thank you @thtrieu for your efforts. Second, I just spent the last few hours figuring out how to correctly train YOLO on my own dataset (custom # of classes) and would love to create a section in the Readme file with the detailed steps (which I found digging through the issues) if possible.

**Comment by victoryforphil** [comment]
+1

**Comment by st99315** [comment]
+1

**Comment by Prakash19921206** [comment]
or creating a wiki for this repo will be better, so that people who have already tried training their own dataset may update wiki

**Comment by ahmedbaracat** [comment]
I have create a pull request #268
