### ISSUE TITLE
Why are the hyper-parameters defined in .cfg ignored?

### ISSUE THREAD

**Issue by ahmedbaracat** [thtrieu/darkflow#204]
Hi,

Why do LR, batch size, etc. defined in `.cfg` files ignored and overwritten by the flags in `flow.py` even if none were passed while issuing the command through terminal?

**Comment by st99315** [comment]
I have the same question, too.

**Comment by thtrieu** [comment]
For convenience. Suppose you want to automate experimenting with different LR, batch size, etc, then a `.sh` with various values for these flags would be better than many different `.cfg` files. 

This might be a bad feature, but my experience shows otherwise.

**Comment by ahmedbaracat** [comment]
@thtrieu Thanks for clarifying that. I think the problem is that the README file doesn't mention this so users would expect that `.cfg` has the parameters. I think updating the README file would be the way to go.

**Comment by thtrieu** [comment]
Thanks. A lot of people are complaining about README and I am fully responsible for that.

**Comment by ahmedbaracat** [comment]
Can I push some suggested fixes to the README?

**Comment by thtrieu** [comment]
Please do.
