### ISSUE TITLE
Training on Pascal VOC

### ISSUE THREAD

**Issue by bjornamr** [thtrieu/darkflow#205]
After downloading the Pascal dataset i tried to run: 
**python3 flow --model cfg/yolo-new.cfg --train --dataset "~/VOCdevkit/VOC2007/JPEGImages" --annotation "~/VOCdevkit/VOC2007/Annotations"**

But I only get the error: 

  **File "/usr/local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 356, in <module>
    from dateutil import parser as _date_parser
  File "/usr/local/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))**

I tried reinstalling python3-dateutil, with no luck.

Any suggestions?

**Comment by fwahhab89** [comment]
dataset and annotations should be provided separately

**Comment by thtrieu** [comment]
You only post the traceback, where is the error message?  Seems like something's happening with `pandas`, which I remember did not use in darkflow.
