### ISSUE TITLE
yolo forward path speed on GTX 1080

### ISSUE THREAD

**Issue by OmarMAmin** [thtrieu/darkflow#208]
I'm working with Yolo on darkflow, and currently I'm trying to reach real-time detection and tracking, so i skip 10 frames between each detection, but unfortunately the yolo forward pass alone takes around 0.4 seconds, is that normal?

Do you know any way to speed the pipeline up, the yolo weights file I'm using is  269.9 MBs, can i use Yolo v2 on darkflow ?

Thanks in advance

**Comment by thtrieu** [comment]
Did you utilize GPU with `--gpu 1.0`?
You can definitely use v2 on darkflow. Other people reported a much better running time in https://github.com/thtrieu/darkflow/pull/113

**Comment by BabuTango** [comment]
Can you please tell me where to skip the frames
