### ISSUE TITLE
Manually assign which GPU to use

### ISSUE THREAD

**Issue by borasy** [thtrieu/darkflow#209]
Hi,

I have a 4 GPU machine and am trying to train yolo 2. But i wanna assign a specific GPU to train. Is it possible in darkflow?

P.S. In native tensorflow, we can use 
`with tf.device('/gpu:0'):` or `with tf.device('/gpu:1'):` to assign the gpu0 or gpu1 to the task.
I can't find `tf.device()` anywhere in darkflow

@thtrieu

**Comment by thtrieu** [comment]
Hope this can be solved by the new flag `--gpuName` added in https://github.com/thtrieu/darkflow/commit/979027c2a925d55ff6c658a8ed147ca3f8ff7690

**Comment by crazylyf** [comment]
I tried training using arguments `--gpuName` to `"/gpu:7"` and `--gpu 0.1`, but it still run on all devices, even manually modify the `with tf.device(device_name)` to `with tf.device('/gpu:7')` in `darkflow/net/build.py` does not work.

**Comment by Cpruce** [comment]
Bump

**Comment by evilmtv** [comment]
Bump

**Comment by rafajak** [comment]
The --gpuName flag didn't work for me either. What worked however, is passing CUDA_VISIBLE_DEVICES=1 in front of my flow command, as suggested by Borasy in another issue:
 
> Try this instead :
> `CUDA_VISIBLE_DEVICES=1 python3 flow --train . . . `

Cheers,
Raf
