### ISSUE TITLE
KeyError: 'thresh'

### ISSUE THREAD

**Issue by rtrahms** [thtrieu/darkflow#21]
$ ./flow --model yolo-voc.cfg --load yolo-voc.weights --demo camera
...
 Load  |  Yep!  | concat [26, 24]                  | (?, 13, 13, 3072)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 125)
-------+--------+----------------------------------+---------------
Running entirely on CPU
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8475
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.47GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From /home/rob/darkflow/net/build.py:98: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Finished in 8.21734499931s

VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
Press [ESC] to quit demo
Traceback (most recent call last):
  File "./flow", line 49, in <module>
    tfnet.camera(FLAGS.demo)
  File "/home/rob/darkflow/net/help.py", line 78, in camera
    })[0], frame, False))
  File "/home/rob/darkflow/net/yolov2/test.py", line 23, in postprocess
    threshold = meta['thresh']
KeyError: 'thresh'

Not sure why 'thresh' is missing.  Looking into it.

**Comment by thtrieu** [comment]
Running fine on my computer though, can I have a look at your `cfg`?

**Comment by thtrieu** [comment]
I expect it to be the spacing problem again.

**Comment by rtrahms** [comment]
Yes, it was the spacing problem again.  Removing the spaces from the thresh = .6 line in the cfg file fixed the issue.
