### ISSUE TITLE
Do need I to label all the same objects on one image?

### ISSUE THREAD

**Issue by chengs2000** [thtrieu/darkflow#210]
For labeling image, say I have two dogs on one image. 
Do I need to draw two boxes for each dog when I label the image?
If I just draw one box for one of the dogs, during the training process, how many dogs does the model can tell? Two or one? Let's say the model tells two dogs (predicts two boxes, each box for one dog). Then which box is used to calculate the loss?

**Comment by solomondg** [comment]
One box for each dog, otherwise it'll train to think that the dog you didn't box is a background object.

**Comment by thtrieu** [comment]
The model will be confused. 

Except there is a clear visual difference between the dogs (e.g. two species), and annotation across every training image follows this difference, then the model will learn to differentiate these dogs. Otherwise, confusion while predicting is what you probably get.
