### ISSUE TITLE
Adding confidence next to bbox label

### ISSUE THREAD

**Issue by borasy** [thtrieu/darkflow#217]
Can we add the confidence value next to each bbox label? Where can I find how to do it?

**Comment by abagshaw** [comment]
If you are wanting to draw the confidence on the output image you can modify this line: https://github.com/thtrieu/darkflow/blob/22ac87a3cb1b585d62c5106aab2f203ead4b445f/darkflow/net/yolo/test.py#L35

To the following:

`mess = '{0} {1:.2f}'.format(label, max_prob)`

**Comment by borasy** [comment]
@abagshaw Wow it's that simple. Thanks, I just tried it. Works great. 
I also want the letter to be bolder and i wanna put a background behind the text like the original darknet. But i'll try figuring that out myself.

**Comment by off99555** [comment]
I think this should be an option for the `flow` command, not just something user need to adjust the code for.
