### ISSUE TITLE
yolov2 error

### ISSUE THREAD

**Issue by jwnsu** [thtrieu/darkflow#22]
Tried a v2 trained model (own dataset) from the C yolov2 project, got following error:
----Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/ai/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/ai/darkflow/dark/darknet.py", line 16, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/home/ai/darkflow/dark/darknet.py", line 66, in parse_cfg
    else: new = create_darkop(*info)
  File "/home/ai/darkflow/dark/darkop.py", line 61, in create_darkop
    return op_class(ltype, num, *args)
  File "/home/ai/darkflow/dark/layer.py", line 19, in __init__
    size = np.prod(shp)
  File "/home/tensorflow/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2539, in prod
    out=out, **kwargs)
  File "/home/tensorflow/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: cannot perform reduce with flexible type
-----------

Take a quick look at dark/layer.py and could not figure out quickly what went wrong. Running with latest Tensorflow 0.12.

Same model/weight files work very well with YoloV2 C project. Use the command from this website: ./flow --test <test-dir> --model cfg-file --load weight-files

**Comment by thtrieu** [comment]
This seems like a parser bug, it would help a lot if you were able to `print(self._signature, self.wshape)` before `layer.py:19` and post the result here. Thanks.

**Comment by jwnsu** [comment]
It prints large block of network definition. Do you want to see it?

Thanks.

**Comment by jwnsu** [comment]
It's copied from yolo-voc.cfg (v2), only changes I made is classes (to 2)
and filters (to 35).

**Comment by thtrieu** [comment]
I would love to see it. 

P/S It seems like this network architecture is to be kept secret by you, so It's hard for me to debug without actually look at the result. If this is the case, we'll do it the hard way, I tell you what's the potential problem & how to debug yourself :)

**Comment by jwnsu** [comment]
Please give me an email address, I will send you a download link for cfg
and weight file.

**Comment by thtrieu** [comment]
thtrieu@apcs.vn

**Comment by thtrieu** [comment]
P/S @jwnsu  since this look like a parser bug, you would not need to send the weights file, config `cfg` is enough.

**Comment by jwnsu** [comment]
The parsing bug is now gone, after taking care of param_initilizers for
tensorflow 0.12, now got following error:
--
Forwarding 9 inputs ...
Total time = 34.4114341736s / 9 inps = 0.261540973695 ips
Post processing 9 inputs ...
Traceback (most recent call last):
  File "./flow", line 60, in <module>
    tfnet.predict()
  File "/home/dsu/ai/darkflow/net/flow.py", line 103, in predict
    os.path.join(inp_path, all_inp[i]))
  File "/home/dsu/ai/darkflow/net/yolov2/test.py", line 23, in postprocess
    threshold = meta['thresh']
KeyError: 'thresh'
--

Checked directory out and saw no output images. We are very close!

Appreciate your project and efforts.

**Comment by thtrieu** [comment]
did you following all of my instructions, including the 'thresh' one? I
think I mentioned it in the previous email.

**Comment by jwnsu** [comment]
Good one! It seems I only deleted space after "=", now I saw there is a
space before "=". After I deleted it too, it now works fine!

Thanks a lot.

ps: original yolo-voc.cfg (v2) has spaces around "=" for that line too.

**Comment by thtrieu** [comment]
I fix all these parser bug in a new commit, including the param_initializers and all TF 0.12 warnings.

**Comment by jwnsu** [comment]
Thanks, I pulled the changes.

One question: I checked images generated in out directory, there is no
class mark/bound-box. What to expect in predicted images?

**Comment by thtrieu** [comment]
what do you mean by no class mark/boundbox ?

**Comment by jwnsu** [comment]
I saw predicted images in test/out directory, after I checked the images,
there is nothing added compared with original images in test directory.
Expecting a class label with bound box in the predicted images in test/out
directory, like yolo project.

**Comment by thtrieu** [comment]
Is the original model running fine? If yes then it is probably because of the post-processing. Please pull new code and try to lower `thresh` inside your `.cfg`, (down to 0.3 instead of .6 maybe?)

**Comment by jwnsu** [comment]
I pulled latest changes, still no object detected in the predicted images
(dropped thresh down to 0.02). The model/weight are highly accurate ones,
in C based yolov2, it detected many objects >0.7.

**Comment by thtrieu** [comment]
Please try my new commit & tell me if it works

**Comment by jwnsu** [comment]
Great, label and bound-box started to show up in some images. But accuracy
level is way off rom yolov2 C project. It only recognizes about 40 to 50%
of objects compared with C version of yolov2.

Anyway, it's big improvement from earlier today, so hopefully will get
there soon.

**Comment by thtrieu** [comment]
A lot of things need to be improved. Including the speed, I'm planning on moving to `C` code for post-processing part. The two repositories cannot match performance because of internal numerical handling of Tensorflow is different than that of Darknet. Just a little difference can be amplified greatly to later layers, since the model weights are trained with Darknet, it is expected to be worse running on Tensorflow. I will spend more time looking into this as well. But it's not going to be any time soon since Im a bit busy lately.

Thanks for test cases from you.

**Comment by MarynaLongnickel** [comment]
I'm getting the same error :< Any new updates?
