### ISSUE TITLE
Loading ckpt files with python application

### ISSUE THREAD

**Issue by dddevo26** [thtrieu/darkflow#220]
So I'm trying to use the checkpoints that were made from a training sessions I did. I use :  
 options1 = {"model": "cfg/test.cfg", "load": -1, "threshold": 0.9, "gpu": 0.8}
 tfnet1 = TFNet(options1)
In my terminal it outputs:
Parsing cfg/test.cfg
Loading None ...
Finished in 0.0s
So i assume its not loading the checkpoints correctly. 
Any insight into this problem would be greatly appreciated.

**Comment by jcarletgo** [comment]
Try:
options1 = {"model": "cfg/test.cfg", "load": -1, "threshold": 0.9, "gpu": 0.8, "backup":"ckpt/"} or similar

**Comment by dddevo26** [comment]
I tried with the backup flag, and it isn't throwing any errors but it still says: 
Parsing cfg/test.cfg
Loading None ...
Finished in 0.0s

**Comment by thtrieu** [comment]
Loading None meaning it does not load from weights file. If you are anticipating a loading from ckpt message, look for it after the table of layers.
