### ISSUE TITLE
Can't set threshold?

### ISSUE THREAD

**Issue by adamzjk** [thtrieu/darkflow#222]
when I use command 

` python3 flow --test test/ --model cfg/yolo-voc.cfg  --threshold 0.5 --load bin/yolo-voc.weights`, 

and add print(FLAGS. threshold) in both `flow` file and function `process_box` which is defined in `test.py`

 I got outputs 0.5 from flow and 0.6 from `process_box`. no matter what value I set to thereshold the threshold value in `process_box`  is still 0.6.

Even when I manually set threshold = 0 by adding a line threshold = 0 in  function `process_box`, I got the same output images...(I use default examples in test folder)

**Comment by adamzjk** [comment]
Issue resolved when I update to the latest version of darkflow

**Comment by Muntasir-mn** [comment]
@adamzjk  what was your solution?
