### ISSUE TITLE
problem with train own imageset 

### ISSUE THREAD

**Issue by wflijunnan** [thtrieu/darkflow#227]
## Problem：
Traceback (most recent call last):
  File "./flow", line 56, in <module>
    print('Enter training ...'); tfnet.train()
  File "/home/ljn/darkflow/darkflow/net/flow.py", line 37, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/ljn/darkflow/darkflow/net/yolo/data.py", line 113, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "/home/ljn/darkflow/darkflow/net/yolov2/data.py", line 27, in _batch
    img = self.preprocess(path, allobj)
  File "/home/ljn/darkflow/darkflow/net/yolo/test.py", line 61, in preprocess
    result = imcv2_affine_trans(im)
  File "/home/ljn/darkflow/darkflow/utils/im_transform.py", line 19, in imcv2_affine_trans
    h, w, c = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by dimaxano** [comment]
Hi! Is this error appeared from the very beginnig of the training process or after some time?

**Comment by wflijunnan** [comment]
Thanks for the answer, at the begining.
And I found that in the xml file created by LabelImg, the <filename> doesn't has ".jpg", so I add it, the error is missed, but  I'm not sure。

my imageset on yolo-voc.cfg on the step with 1500 : loss nan - moving ave loss nan

**Comment by thtrieu** [comment]
For NaN issue: please see https://github.com/thtrieu/darkflow/issues/151. Hope this helps.

**Comment by zacharynevin** [comment]
Maybe it's possible that the loss gets so stupidly high that it overflows the maximum value for a float (~3E38). When I was training darkflow on a new dataset I had my learning rate at `1E-3`, but the loss would sometimes quickly spike to several million, or just go straight to `NaN` with *no errors* (so, not the `sqrt` thing you see in other issues). 

When I turned it down back to `1E-5` everything was fine and I never had any issues with exploding losses or `NaN`.
