### ISSUE TITLE
Training my own net

### ISSUE THREAD

**Issue by hungnguyen0606** [thtrieu/darkflow#228]
I want to train my own net but I don't know the format of the images & annotations.
Do I have to convert all the annotation to VOC format or something?

**Comment by ck196** [comment]
1. Dataset
- The easiest way, you will convert your dataset to VOC format.
2. Net
You can change net (graph) in cfg/yolo.cfg or other files. You can write your net with the same format.

**Comment by hungnguyen0606** [comment]
Thank you for your answer.
Do you know any tool to annotate images & save them under VOC format?

**Comment by ck196** [comment]
This is very good tool to annotate and save to VOC format.
- https://github.com/tzutalin/labelImg
I

**Comment by hungnguyen0606** [comment]
Thank you so much.
You've made my day. :D
