### ISSUE TITLE
Setting up CI

### ISSUE THREAD

**Issue by abagshaw** [thtrieu/darkflow#229]
@thtrieu This is just an idea - and I'm sure you're super busy so no problem getting onto this right away. As this project it getting more attention I'm thinking it may be a good idea to setup some CI system (https://travis-ci.org/ probably the best option...) to help with the growing number of PRs and testing them.

As I don't have the sufficient privileges to set this up...this would have to be something you'd setup - but I'd love to help in any way I can in setting up the tests (I can help write the `pytest` file).

Running tests on a pre-trained model to verify that the prediction system is working fine shouldn't be too hard to setup. Setting up some tests for the training pipeline, on the other hand, will probably be more of a challange. Obviously the CI environment isn't handled for ML training...maybe there is a way just to train on a handful of images and even though the resulting model will be absolutely terrible - it can be used to verify that the training is indeed working?

Let me know your thoughts. Thanks!

**Comment by thtrieu** [comment]
Will discuss in #240
