### ISSUE TITLE
Guidelines on training for PascalVOC data?

### ISSUE THREAD

**Issue by rtrahms** [thtrieu/darkflow#23]
Hi -
I can successfully run darkflow in demo mode with the camera.  Great!
I am trying to start a training run with PascalVOC dataset, and having trouble.
I have the VOC2012 set downloaded. 
Question:  I need to create the labels files from the VOC Annotations folder, does darkflow do that automatically with the --annotation <path_to_VOC_Annotations> flag as part of the training, or do I call it before running with the --train flag?

Any guidelines on setup here would be appreciated. 
Thanks,
Rob

**Comment by thtrieu** [comment]
It will handle the parsing itself. Hope there's no bug.

**Comment by rtrahms** [comment]
Thanks.  I think I found the issue.  I had a labels.txt file with all 20 classes in it, and needed to use the yolo-full.cfg file.  Once I entered the line below, things moved along into training nicely (including the parsing at the beginning):

./flow --model cfg/v1/yolo-full.cfg --dataset /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/JPEGImages/ --annotation /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/Annotations/ --backup yolo_backup --train

Since my version of TF is built with CUDA support, I assume I don't need to call --gpu 1.0 explicitly to use the GPU for training, correct?

**Comment by thtrieu** [comment]
You **do** have to

**Comment by rtrahms** [comment]
Okay.  I do only have 8GB of GPU mem (NVidia GTX 1080), and will need to find a way to trim the memory use down.  When using Caffe/DIGITS, I was able to trim batch sizes, not sure if I can do that here.

**Comment by thtrieu** [comment]
Decreasing batch size by a factor of `2.0` will decrease the standard deviation only by a factor of `sqrt(2.0)`, so it is actually beneficial to trim batch size if you have limited resources, especially when it comes to resource-extensive tools like TF. 

Good luck with the training.

**Comment by rtrahms** [comment]
Hi -
I tried to stop and restart the training, using a saved checkpoint.  I followed the format you specified below:

./flow --train --model cfg/yolo-2c.cfg --load ckpt/yolo-3c-1500

In my case I have a collection of checkpoint files for yolo-4c, the latest of which is 1162.  The following command:

./flow --model cfg/v1/yolo-4c.cfg --dataset /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/JPEGImages/ --annotation /home/rob/Data_PascalVOC/VOCdevkit/VOC2012/Annotations/ --train --load ckpt/yolo-4c-1162 --gpu 1.0

gives an error:
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/rob/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/rob/darkflow/dark/darknet.py", line 12, in __init__
    self.get_weight_src(FLAGS)
  File "/home/rob/darkflow/dark/darknet.py", line 46, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: ckpt/yolo-4c-1162 not found

Am I calling this correctly?

**Comment by thtrieu** [comment]
Looking at the assertion error, clearly `ckpt/yolo-4c-1162` does not exist. Make sure it is there

**Comment by rtrahms** [comment]
There is no file with that prefix only, but checkpoint files seem to have four different types: '00000-of-00001', index, meta and profile.  This is the same for every checkpoint, not just 1162.  1162 has this as you see below.   I tried --load with each of the files below, no go.  Should I be expecting a prefix only file in addition to the four files I see?

rob@skynet1:~/darkflow$ cd ckpt
rob@skynet1:~/darkflow/ckpt$ ls yolo-4c-1162*
yolo-4c-1162.data-00000-of-00001  yolo-4c-1162.index  yolo-4c-1162.meta  yolo-4c-1162.profile

**Comment by rtrahms** [comment]
I figured it out!  I was using the filename, not the iteration number!  All is well now, training resumed after specifying "--load 1162".  Thanks.

**Comment by thtrieu** [comment]
Great, the files you listed are new to me, that must be TF 0.12; nevertheless, good luck with getting back on track.

**Comment by rtrahms** [comment]
Reviewing the yolo code, I noticed that there are thresholds defined for four classes in test.py:
_thresh = dict({
	'person': .2,
	'pottedplant': .1,
	'chair': .12,
	'tvmonitor': .13
})

Do I need to adjust this for the number of classes I have in labels.txt and the .cfg file?  Just curious.

**Comment by thtrieu** [comment]
Actually that was an experiment of mine that I forgot to remove, please
delete that dictionary, or modify it so that each class has its own
threshold, over-riding the threshold specified in `.cfg`, It's up to you
and it does not harm the training process.

**Comment by rtrahms** [comment]
Will do - thanks!

**Comment by hemavakade** [comment]
@rtrahms How did you test after you trained the model. Can you please help me with the command. I have a saved checkpoint in the `ckpt` folder. Should I use this.
