### ISSUE TITLE
training my own class

### ISSUE THREAD

**Issue by whchan** [thtrieu/darkflow#231]
Sorry that I ask questions here since I don't know where is more appropriate. Here is what I'm trying to do:

I've got 1 class of photos from image net, so the image set and annotations are already in VOC format. I would like to train a model such that I can use to do object detection in a python program.

Here is what I did:
0) Modified labels.txt to the class I'm working on.

1) Just copied yolo-voc.cfg for my test and changed this line "classes=1" under "region".
// Is this appropriate? Honestly, I don't know what the parameters in the cfg means.

2) I'm trying it just on my MacBook pro, it trained over 12 and was at around 1900 steps. How many steps will it finish (will it be like indefinite?)? Should I a) tune it (how?) or b) find a GPU machine to run?

Here is the command I used:

```
./flow --model cfg/yolo-voc.cfg --train --dataset ~/Downloads/n02802426/JPEGImages/ --annotation ~/Downloads/n02802426/Annotations/
```

3) As it took too long, I've decided to pause the training and use the latest intermediate steps to test by the following command:

```
./flow --model cfg/yolo-new.cfg --load -1
```

I got nothing in the output images. If I ran it w/ --json, the json output is basically empty (with only '[' in the file).

Could someone tell what I did wrong and whether I'm testing it too early / the training will basically never finish since I'm using cpu..?

Thanks so much!

**Comment by whchan** [comment]
sorry, I actually used yolo-voc.cfg because if I change class to 1, I got the following error.

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 338000 values, but the requested shape requires a multiple of 5070
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](output, Reshape/shape)]]

**Comment by beebrain** [comment]
If you have 1 class in your label.txt. You should config cfg file like this
the classes in region section must be 1, and recompute last converlution filter  =  #numbox(#classes+5 coordinates) ref (https://arxiv.org/abs/1612.08242)
Example if you have 1 class predict 5 boxes lass convolution filter = 5(1+5) = 26 filter 
push 26 filter in last convolution section.

PS.
I suggest monitor with tensorboard if your loss less than 1 .It should have a result in your json file.
Good luck.

**Comment by borasy** [comment]
@beebrain wait? is it not 30? 5+1 = 6 and then 6*5=30 ?? or my calculation is wrong?

**Comment by thtrieu** [comment]
- if you are defining some new configurations, avoid the same name to the old ones.
- now that the name is different, change labels.txt to classes you want to use.
- classes = 1 is not the only part you should change, the last convolutional layer's channel number should be changed to (num * (5 + classes)) too, where num can be found in the [region] layer.

This should be enough.

**Comment by lobbie** [comment]
Hi, sorry to bump this thread.  @thtrieu mentioned in his comments

classes = 1 is not the only part you should change, **the last convolutional layer's channel number should be changed to (num * (5 + classes)) too**, where num can be found in the [region] layer.

Can anyone please advise where is this?  When I look at the yolov2.cfg, the last convolutional layer (just before [region] does not have a channel number parameter.

```
[convolutional]
size=1
stride=1
pad=1
filters=425
activation=linear

[region]
anchors =  0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828
bias_match=1
classes=80
coords=4
num=5
softmax=1
jitter=.3
rescore=1
```

Cheers.

**Comment by beebrain** [comment]
You can change a number of filter at last layer that is a chanel number.

**Comment by lobbie** [comment]
got it.  thank you, @beebrain

**Comment by pandasMX** [comment]
anyone knows how does the model knows which image belongs to which label inside the labels.txt?

**Comment by beebrain** [comment]
The model read the label from annotation xml file.

**Comment by priyamehta01** [comment]
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

I am getting this error when I am running the flow --h command. I am running the code on a CPU. Any fixes?

**Comment by beebrain** [comment]
@priyamehta01  : You can train on CPU but It take very long time, and I don't recommend to do that.
For nvcuda.dll , make sure you installed cuda toolkit on your machine. In general, cuda toolkit is installed in "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA".
