### ISSUE TITLE
Cannot save video file

### ISSUE THREAD

**Issue by beebrain** [thtrieu/darkflow#233]
I try to recorded video with boundingbox prediction. In your instruction suggest "--saveVideo".
I run model with this command and got some error.
"flow --model cfg/tiny-yolo-Bee.cfg --load -1 --saveVideo --demo camera --gpu 0.7"

![image](https://cloud.githubusercontent.com/assets/10016227/26140504/6c4f25b8-3b01-11e7-86f1-0ba9b3cbb334.png)

And I push filename in the command.
flow --model cfg/tiny-yolo-Bee.cfg --load -1 --saveVideo bee.avi --demo camera --gpu 0.7
It can open the camera but it don't record the video (not found "bee.avi" file).

**Comment by adamaulia** [comment]
try this one , 
./flow --model cfg/.cfg file --load bin/.weight file --demo video/camera --gpu 1.0 --saveVideo

**Comment by beebrain** [comment]
@adamaulia sorry,It don't work

![image](https://cloud.githubusercontent.com/assets/10016227/26186220/418676f6-3bba-11e7-9796-d4def92e4d49.png)

**Comment by borasy** [comment]
@beebrain You should update your git to latest. It should work.

**Comment by adamaulia** [comment]
I think there's a little bit miss understanding, 
try this one, 
using video file 
 ./flow --model cfg/yolo.cfg file --load bin/yolo.weight file --demo *your video file goes here* --gpu 1.0 --saveVideo
using camera
./flow --model cfg/yolo.cfg file --load bin/yolo.weight file --demo camera --gpu 1.0 --saveVideo

**Comment by thtrieu** [comment]
Remember to update the code and follow @adamaulia  commands should make it work.

**Comment by johnsonice** [comment]
I am using the most up to date version. still getting the same issue. 
error: 
```
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/Users/huang/Dev/projects/darkflow_all/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/Users/huang/Dev/projects/darkflow_all/darkflow/darkflow/net/help.py", line 90, in camera
    fps = 1 / self._get_fps(frame)
AttributeError: 'TFNet' object has no attribute '_get_fps'
```

**Comment by thtrieu** [comment]
@johnsonice  I am sorry for not being more careful.
This new commit https://github.com/thtrieu/darkflow/commit/ae3ac338fa9e9894f5a8a2f0bbb18b74c52fdc69 should fix the bug

**Comment by krydm** [comment]
@thtrieu I've just cloned the latest, and get the same issue:

> flow --model cfg/yolo.cfg --load ../yolo.weights file --demo ../MVI_0043.AVI --saveVideo
......
Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/notebooks/darkflow/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/notebooks/darkflow/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/notebooks/darkflow/darkflow/darkflow/net/help.py", line 96, in camera
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

**Comment by PBRAOS** [comment]
What are the dimensions of your video ?

**Comment by deksprime** [comment]
I'm having the exact same problem here... 
```Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/deks/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/home/deks/darkflow/darkflow/net/help.py", line 96, in camera
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'
```

I think it is related to opencv version. I have both opencv2 and opencv3 installed, but this function doesn't seem to be present in opencv2, but I don't know how would I use opencv3 if that's the case
