### ISSUE TITLE
How to use the model that own trained

### ISSUE THREAD

**Issue by wflijunnan** [thtrieu/darkflow#235]
I change the classes numbers to 2
./flow --train --model cfg/manhole.cfg --load bin/yolo-voc_final.weights --dataset "/home/ljn/darkflow/pascal/VOCdevkit/IMG" --annotation "/home/ljn/darkflow/pascal/VOCdevkit/ANN" --gpu 0.9

AND,my result :  step 5000 - loss 5.326655387878418 - moving ave loss 5.381603650825245

I test with that ： ./flow  --model cfg/manhole.cfg --load 5000  --test test/
BUT,  the train data also NOT recognized
So，I confused，please someone give me some advice

**Comment by thtrieu** [comment]
See https://github.com/thtrieu/darkflow/issues/80 and https://github.com/thtrieu/darkflow/issues/167
