### ISSUE TITLE
Cannot load weight anymore

### ISSUE THREAD

**Issue by hungnguyen0606** [thtrieu/darkflow#247]
After pulling new version, I couldnt load the weight anymore.
I got the following error.
"
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/net/build.py", line 57, in __init__
    darknet = Darknet(FLAGS)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/ubuntu16/my_user/workspace/thesis/Framework/DavisChallenge/darkflow/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 203934260 bytes, found 269862452
"

This error didn't happen in the old version, which is ee6fd2c.

**Comment by abagshaw** [comment]
@hungnguyen0606 Just trying to narrow down the problem - the `yolo.cfg` file was recently updated in darkflow to match the current `yolo.cfg` and `yolo.weights` available from the darknet repo and pjreddie.com.

Can you try re-downloading the `yolo.weights` (assuming that's the weight file you are using) from here: https://pjreddie.com/media/files/yolo.weights and see if that does anything?

**Comment by hungnguyen0606** [comment]
@abagshaw 
Thank you!
According to the size of your weight file, it makes some sense now. :D 
I will try it.

**Comment by thtrieu** [comment]
New .weights file updated in google drive.

**Comment by lminer** [comment]
I'm having this issue with yolo-tiny-voc.weights. I modify classes to 1 and filters to 30 and get.

```
AssertionError: expect 63082056 bytes, found 63471556
```

**Comment by Rutulpatel7077** [comment]
AssertionError: expect 44948596 bytes, found 44948600

**Comment by Meziwis** [comment]
also having AssertionError: expect 44948596 bytes, found 44948600

**Comment by shubhajitml** [comment]
@thtrieu @abagshaw @hungnguyen0606 Still having the same error after redownloading `yolo.cfg` and `yolo.weights` file.
`AssertionError: expect 63143560 bytes, found 63471556`

**Comment by jembezmamy** [comment]
I have the same error. I use `yolov2-tiny.weights` with `yolov2-tiny.cfg`, both downloaded from https://pjreddie.com/darknet/yolo/. Is it a proper way to do things or should I use darkflow copy of cfg file? Why cfg files are included in this repo and not downloaded from yolo site?

**Comment by shubhajitml** [comment]
@jembezmamy use a different name for '`yolov2-tiny.weights`' as the _**same name for .weights and .cfg file not working**_ when using custom datasets.
In my case, just by changing the name for `tiny-yolo-voc-4c.weights` to **`yolo-tiny-voc-4c.cfg`** and keeping the `yolo-voc-4c.cfg` file name unchanged, made the model go for training.

**Comment by ideaRunner** [comment]
same error.
AssertionError: expect 63820056 bytes, found 63820060

**Comment by lgribeiro** [comment]
> > I'm having this issue with yolo-tiny-voc.weights. I modify classes to 1 and filters to 30 and get.
> > ```
> > AssertionError: expect 63082056 bytes, found 63471556
> > ```
> > Also have the problem with yolo-tiny.cfg/weights
> 
> Did you solve it? I am having the same problem.
You should use the same name for **.weights and **.cfg . I solved this in my case.

**Comment by sen07** [comment]
I get the same assertion error.. tried changing the cfg and weight files' names and all that. Please provide your insights.

**Comment by dc2016bte0006** [comment]
> I'm having this issue with yolo-tiny-voc.weights. I modify classes to 1 and filters to 30 and get.
> 
> ```
> AssertionError: expect 63082056 bytes, found 63471556
> ```
> 
> Also have the problem with yolo-tiny.cfg/weights
