### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by abagshaw** [thtrieu/darkflow#249]
@thtrieu I've been searching through the code coverage logs to see if there is any code that appears to be unused. Here's a few things I've found:

1. https://github.com/thtrieu/darkflow/blob/master/darkflow/net/vanilla/train.py This appears to be referenced [here](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/framework.py#L7-L8) but it doesn't appear that either `constructor` or `loss` are ever used after that as the loss functions specific to the yolo versions in `train.py` are used.

2. Both `_batch()` functions [here](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolo/data.py#L22-L93) and [here](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolov2/data.py#L10-L84) appear to be referenced in their respective places in https://github.com/thtrieu/darkflow/blob/master/darkflow/net/framework.py however they don't appear to ever be used anywhere else.

3. None of this code appears to be used anywhere: https://github.com/thtrieu/darkflow/blob/master/darkflow/utils/box.py#L11-L44

4. This doesn't appear to be used anywhere: https://github.com/thtrieu/darkflow/blob/master/darkflow/utils/loader.py#L81-L95

There's probably more - but those are the few things that I've been able to find at first glance. I may be wrong about some (or all of those) - maybe they are currently in use. If you think they might be of use in the future - than obviously there is no reason to remove them...but if you think some of that is redundant/not useful than maybe we could remove some of that to clean up the code-base?

---

Actually, on the topic of cleaning up code. Is there any benefit to using YOLOv1 over YOLOv2? If there isn't really - than maybe we should consider dropping YOLOv1 support on this repo? It would make the code base a little cleaner. If you don't see much benefit for having YOLOv1 support it would be worth opening an issue to solicit feedback from users of this repo to see if anyone is using YOLOv1 for training or inference.

**Comment by EmmanouelP** [comment]
In the matter of using v2 versus v1,how can one use the yolov1 implementation?Doens it have to do with the configuration file one uses?

**Comment by abagshaw** [comment]
@EmmanouelP Yes there are different models (`.cfg` files) with their weights that either use YOLOv1 or YOLOv2. I'm not super familiar with the technical differences between YOLOv1 and YOLOv2 but I do know that you can tell the `.cfg` files apart by looking at the last layer the `.cfg` file. If it's `[region]` that's YOLOv2. If it's `[detection]` that's YOLOv1. That's how darkflow distinguishes between then at least. See [this code](https://github.com/thtrieu/darkflow/blob/16e3d0804556653997efe2d278d7cd759bf78c0a/darkflow/net/framework.py#L51-L54).

You can find some YOLOv1 models here: https://github.com/thtrieu/darkflow/tree/master/cfg/v1

**Comment by EmmanouelP** [comment]
@abagshaw Thanks for your reply man.I am interested in the differences between these implementations and those that come from the original darknet (specially about how they handle the loss function) so i will just keep poking around :).

**Comment by abagshaw** [comment]
@thtrieu No rush, but have you had a chance to look at this?

**Comment by thtrieu** [comment]
Thanks for pinging me, I am kind of in a hectic situation right now. Hopefully I'll be able to do something during July.

**Comment by abagshaw** [comment]
@thtrieu No problem at all. On the topic of being busy I'd be happy to do some of the basic stuff, merging small PRs and closing old issues that are starting to pile up while you're busy if you're fine giving me the permissions. If you'd rather keep control over this repo - totally understand 😃, just if it would be a help.
