### ISSUE TITLE
MaxPool layer padding inconsistency between Darknet and Darkflow

### ISSUE THREAD

**Issue by oulutan** [thtrieu/darkflow#250]
Darknet seems to be using 'VALID' padding whereas darkflow is currently using 'SAME' padding defined in [here](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/ops/simple.py#L107). This causes an error. This can be reproduced using an input size that is not divisible by 16 in yolo.cfg. Notice the bolded output sizes in the following.

## Darknet produces these output sizes:
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1  1920 x1080 x   3   ->  1920 x1080 x  32
    1 max          2 x 2 / 2  1920 x1080 x  32   ->   960 x 540 x  32
    2 conv     64  3 x 3 / 1   960 x 540 x  32   ->   960 x 540 x  64
    3 max          2 x 2 / 2   960 x 540 x  64   ->   480 x 270 x  64
    4 conv    128  3 x 3 / 1   480 x 270 x  64   ->   480 x 270 x 128
    5 conv     64  1 x 1 / 1   480 x 270 x 128   ->   480 x 270 x  64
    6 conv    128  3 x 3 / 1   480 x 270 x  64   ->   480 x 270 x 128
    7 max          2 x 2 / 2   480 x 270 x 128   ->   240 x 135 x 128
    8 conv    256  3 x 3 / 1   240 x 135 x 128   ->   240 x 135 x 256
    9 conv    128  1 x 1 / 1   240 x 135 x 256   ->   240 x 135 x 128
   10 conv    256  3 x 3 / 1   240 x 135 x 128   ->   240 x **135** x 256
   11 max          2 x 2 / 2   240 x 135 x 256   ->   120 x  **67** x 256
   12 conv    512  3 x 3 / 1   120 x  67 x 256   ->   120 x  67 x 512
   13 conv    256  1 x 1 / 1   120 x  67 x 512   ->   120 x  67 x 256
   14 conv    512  3 x 3 / 1   120 x  67 x 256   ->   120 x  67 x 512
   15 conv    256  1 x 1 / 1   120 x  67 x 512   ->   120 x  67 x 256
   16 conv    512  3 x 3 / 1   120 x  67 x 256   ->   120 x  67 x 512
   17 max          2 x 2 / 2   120 x  67 x 512   ->    60 x  33 x 512
   18 conv   1024  3 x 3 / 1    60 x  33 x 512   ->    60 x  33 x1024
   19 conv    512  1 x 1 / 1    60 x  33 x1024   ->    60 x  33 x 512
   20 conv   1024  3 x 3 / 1    60 x  33 x 512   ->    60 x  33 x1024
   21 conv    512  1 x 1 / 1    60 x  33 x1024   ->    60 x  33 x 512
   22 conv   1024  3 x 3 / 1    60 x  33 x 512   ->    60 x  33 x1024
   23 conv   1024  3 x 3 / 1    60 x  33 x1024   ->    60 x  33 x1024
   24 conv   1024  3 x 3 / 1    60 x  33 x1024   ->    60 x  33 x1024
   25 route  16
   26 conv     64  1 x 1 / 1   120 x  67 x 512   ->   120 x  67 x  64
   27 reorg              / 2   120 x  67 x  64   ->    60 x  33 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    60 x  33 x1280   ->    60 x  33 x1024
   30 conv    425  1 x 1 / 1    60 x  33 x1024   ->    60 x  33 x 425
   31 detection

## And Darkflow produces these:

Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 1080, 1920, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 1080, 1920, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 540, 960, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 540, 960, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 270, 480, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 270, 480, 128)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 270, 480, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 270, 480, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 135, 240, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 135, 240, 256)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 135, 240, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, **135**, 240, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, **68**, 120, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 68, 120, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 68, 120, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 68, 120, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 68, 120, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 68, 120, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 34, 60, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 34, 60, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 34, 60, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | concat [16]                      | (?, 68, 120, 512)
 Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 68, 120, 64)
 Load  |  Yep!  | local flatten 2x2                | (?, 34, 60, 256)
 Load  |  Yep!  | concat [27, 24]                  | (?, 34, 60, 1280)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 34, 60, 1024)
 Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 34, 60, 425)
-------+--------+----------------------------------+---------------

**Comment by thtrieu** [comment]
The code in `darknet` repo seems to be changing constantly. I'll try to catch up on that. It is worth noting that a lot of people are working on older versions and we need support for that too.
