### ISSUE TITLE
No module named cy_yolo_findboxes

### ISSUE THREAD

**Issue by myBestLove** [thtrieu/darkflow#252]
when  I run test ,  like `./flow --model jason/yolo2_voc2007_2017.cfg --load jason/yolo-voc.weights --test sample_img/`
shows:
`Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/jason/code/darkflow/darkflow/cli.py", line 3, in <module>
    from darkflow.net.build import TFNet
  File "/home/jason/code/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/home/jason/code/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/home/jason/code/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/home/jason/code/darkflow/darkflow/net/yolo/predict.py", line 6, in <module>
    from darkflow.cython_utils.cy_yolo_findboxes import yolo_box_constructor
ImportError: No module named cy_yolo_findboxes
`

there has cy_yolo_findboxes.pyx file in cython_utils directory.
how to sovle? thanks

**Comment by abagshaw** [comment]
Have you built the Cython extensions using one of the three methods outlined [here](https://github.com/thtrieu/darkflow#getting-started)?

**Comment by myBestLove** [comment]
I only use 'pip install .'

do I  need to executed  'python3 setup.py build_ext --inplace' ?

**Comment by abagshaw** [comment]
Can you try using `flow` instead of `./flow`

**Comment by myBestLove** [comment]
the same problem . 

and my cython_utils directory like this
---->cython_utils
     ---->cy_yolo2_findboxes.pyx 
     ---->__init__.py   
     ---->nms.pxd
     ---->cy_yolo_findboxes.pyx  
      ---->__init__.pyc 
      ---->nms.pyx
is OK?

**Comment by abagshaw** [comment]
If you install using `pip install .` I don't think the Cython extensions will be built in the same folder - they will be build somewhere else. Try running `pip uninstall darkflow` then run `python3 setup.py build_ext --inplace` and try the `./flow` command again.

**Comment by myBestLove** [comment]
ok
I find that  if using `pip install .`, Cython extensions will be built in the `/usr/local/lib/python2.7/dist-packages/darkflow`.

**Comment by ilopezfr** [comment]
@myBestLove I'm having the same issue, using Python 3.5. I tried @abagshaw suggestion but didn't work for me. Can you share how did you solve it? This is a screenshot of my error: 
<img width="674" alt="screen shot 2017-06-02 at 7 28 21 pm" src="https://cloud.githubusercontent.com/assets/11858780/26750122/917780ce-47e0-11e7-8aa0-2e6aa8575aa4.png">

**Comment by abagshaw** [comment]
@ilopezfr Can you try using `flow` instead of `./flow` and see if that changes anything?

**Comment by ilopezfr** [comment]
@abagshaw I did my installation using `python3 setup.py build_ext --inplace` so it doesn't recognize the command `flow`. 
Did you installed it globally with `pip install .` ? Would that chance anything?
Thanks!

**Comment by ilopezfr** [comment]
@abagshaw In case it helps, this is what I get when trying to install darkflow globally:
<img width="482" alt="screen shot 2017-06-04 at 11 18 31 am" src="https://cloud.githubusercontent.com/assets/11858780/26764226/ef047476-4917-11e7-95b7-f0e6a0ea41a9.png">

**Comment by abagshaw** [comment]
@ilopezfr It may be that just building the Cython extensions in place doesn't work with the import paths (I'll look into that). For now can you try doing `pip install .`.

**Comment by ilopezfr** [comment]
@abagshaw Thanks! It actually fixed it when installing it globally.

**Comment by Chambana** [comment]
For what it's worth, I am using python 2.7 and was having the same issue.  I initially used sudo pip install . to install and had the cy_yolo_findboxes error when using the provided python script to import the darkflow module(s).  I uninstalled darkflow using "sudo pip uninstall darkflow", then reinstalled using:

    python setup.py build_ext --inplace    
    (note: not python3 as described  above).  

I now can run the command line demo using:
    ./flow --model cfg/yolo.cfg --load bin/yolo.weights --demo camera --gpu 1.0

and I can use the python interface as well in python2.7:
    from darkflow.net.build import TFNet
    import cv2

I'm running ubuntu 16.04, python2.7, CUDA installed.  Separate issue, but for whatever reason, the command line demo runs at <1fps.

**Comment by dnacuna** [comment]
Hey,

I had the same issue with the imports from cython code not using fully qualified names. The solution is simply not using "darkflow" as the name for the root folder in the project.

**Comment by liuhantao9** [comment]
I am trying to run codes that I wrote on PyCharm, and I ran into same issue.
Any help will be appreciated
<img width="1435" alt="screen shot 2018-01-26 at 1 55 29 am" src="https://user-images.githubusercontent.com/33992579/35434468-1ac620d6-023c-11e8-90a2-e6475992019f.png">

**Comment by karthickn210** [comment]
@ilopezfr same errors.... i am also faced using in ubuntu can you help me to overcome this problem with your experience...

**Comment by ashokpant** [comment]
cd darkflow/
python setup.py build_ext --inplace
pip install -e .

Works for me (ubuntu16.04, python3.5)

**Comment by BaptisteAmato** [comment]
./flow didn't work for me, but `python flow ...` worked!

**Comment by Haosam** [comment]
after doing all the steps listed, 

- in your conda environment [Either base (if you did not set a virtual environment), OR the virtual environment that you dedicated darkyolo for]
- go the directory where dark-flow master is located
- Run 'python3 setup.py build_ext --inplace' again
OR
'python setup.py build_ext --inplace' (Depending on your set up)

I was using python 3.5.6 in my anaconda virtual environment and after i built it again, it worked.
After it works
run 'python flow -h' to check after installation.

**Comment by GigsyKami** [comment]
i got the same problem but instead `ImportError: No module named cy_yolo_findboxes `
i got `ImportError: No module named cv2`
what should i install?
i already do pip install opencv

**Comment by Haosam** [comment]
Hi GipsyKami. Are you using Conda or the regular python3 for this?

I am assuming you used conda.
There were some issues for me when I installed the packages to link to each other. Somehow for my system, conda installed packages and pip installed packages did not work together. My recommendation when working on yolo for python, is to install all packages on pip. 
So, either remove all the conda packages on the conda environment, or just build a new conda environment and pip install everything.

As for opencv, it is slightly more complicated than pip install opencv
I followed this installation guide. You can look at it
[OpenCV Installation](https://www.youtube.com/watch?v=Fcc_jemaoNU)

**Comment by akashsahu410** [comment]
![screenshot 170](https://user-images.githubusercontent.com/26576455/53389565-d3fdcc00-39b5-11e9-9e00-45fcaf2a9a9f.png)

**Comment by akashsahu410** [comment]
the same problem .

and my cython_utils directory like this
---->cython_utils
---->cy_yolo2_findboxes.pyx
---->**init**.py
---->nms.pxd
---->cy_yolo_findboxes.pyx
---->**init**.pyc
---->nms.pyx
is OK?

**Comment by Wanderish** [comment]
@akashsahu410 Have you tried this?

> ./flow didn't work for me, but `python flow ...` worked!

**Comment by prsntmaurya** [comment]
Copying the files "nms.pxd"  and "nms.pyx" to root darkflow directory worked for me
