### ISSUE TITLE
Cannot build build the Cython extensions in place

### ISSUE THREAD

**Issue by dtosato** [thtrieu/darkflow#254]
### Issue summary
I get an exception building the Cython extensions in place.

### Executed command
python3 setup.py build_ext --inplace

### Output
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

### Type of issue
Compilation/installation error

### Your system configuration
**Operating system**:Ubuntu 16.04.2 LTS
**Python version**: 3.5.2

**Comment by thtrieu** [comment]
Seems like you lack `setuptools`. Try `pip install setuptools`

**Comment by keides2** [comment]
I have a same issue below:

(tensorflow) kei@giga:~/darkflow$ python3 setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Build import cythonize
ImportError: No module named 'Cython'

(tensorflow) kei@giga:~/darkflow$ pip install -e .
Obtaining file:///home/kei/darkflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kei/darkflow/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/kei/darkflow/
