### ISSUE TITLE
Add ckpt folder to .gitignore

### ISSUE THREAD

**Issue by ahmedbaracat** [thtrieu/darkflow#255]
Hi,

I noticed that in `.gitignore` the ckpt folder which is the default folder name for backup is not added. Is there a reason for that?

**Comment by abagshaw** [comment]
Actually I was thinking the same thing. I've already added it in my PR: https://github.com/thtrieu/darkflow/pull/248 (see https://github.com/thtrieu/darkflow/pull/248/files#diff-a084b794bc0759e7a6b77810e01874f2) When that gets pulled the `/ckpt` folder should be ignored.
