### ISSUE TITLE
Where are the new weights stored after training a new model?

### ISSUE THREAD

**Issue by jasag** [thtrieu/darkflow#256]
I trained a new model with my own data and I'm not sure how are stored the new weights and how to use it. Can someone explain it? Thanks in advance!

**Comment by abagshaw** [comment]
When you train a new model you should find the checkpoint `.meta` file in the `/ckpt` folder. Those are your new "weights". There is not a new `.weights` file created. You can load directly from that checkpoint file for testing or you can save the latest checkpoint to a `.pb` protobuf file using `flow --model cfg/yolo.cfg --load -1 --savepb` replacing the model with the one you used.

**Comment by jasag** [comment]
Thanks for your help. But when I execute that command changing to my config name. I'm getting the next output and I don't figure out whats going wrong:

```
flow --model cfg/yolo-new.cfg --load -1 --savepb
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Parsing cfg/yolo-new.cfg
Loading None ...
Finished in 0.00011610984802246094s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 125)
-------+--------+----------------------------------+---------------
Running entirely on CPU
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 1.96GiB
Free memory: 1.48GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
Loading from ./ckpt/yolo-new-800
Finished in 1.4269773960113525s

Rebuild a constant version ...
E tensorflow/core/util/events_writer.cc:131] Failed to flush 1 events to ./summary/train/events.out.tfevents.1495628493.user
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "/home/user/.conda/envs/tf/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/user/test/darkflow/flow", line 63, in <module>
    tfnet.savepb(); exit('Done')
  File "/home/user/test/darkflow/darkflow/net/build.py", line 175, in savepb
    os.makedirs(os.path.dirname(name), exist_ok=True)
  File "/home/user/.conda/envs/tf/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by abagshaw** [comment]
@jasag Are you using the latest version of darkflow? Can you try to re-clone the repo and retry your training? The logs don't seem to suggest you're using the latest version.

**Comment by jasag** [comment]
Thanks! That seems to be the mistake. I'm not getting boxes on predictions but I suppose that is something related with #80. The loss of my model is approximately 1.3 in the last epoch. Probably too bigger to predict something.

**Comment by jasag** [comment]
Could it be because I'm using a pre-trained model (tiny-yolo-voc) and I'm trying to train only one new class instead of 20 classes like the original model? The reason because I did like that is beacuse otherwise I can't use the pre-trained model of tiny-yolo-voc.

Moreover, I'm trying to overfit in two images and the model doesn't fall from 0.4.

**Comment by abagshaw** [comment]
@jasag Ok glad it's sort of working now 😃. Unfortunately I am no real expert on training - so I'll have to leave it to someone else to help you. My best guess would be that it's not a good idea to use a pre-trained model and then change the labels you are training on...but again I really wouldn't know.

**Comment by jasag** [comment]
@abagshaw Thank you very much anyway. You have been very helpful. :)

**Comment by abagshaw** [comment]
@thtrieu Maybe I'm wrong - but I don't believe @jasag has had his issue fully resolved (issues with getting prediction boxes from the trained model)..so maybe the issue shouldn't be closed just yet? I could be missing something though.

**Comment by thtrieu** [comment]
I think no bounding boxes should be a separate issue, **after** previous issues discussion on the same problem does not solve it. Namely, see https://github.com/thtrieu/darkflow/issues/80

**Comment by jasag** [comment]
Thank you anyway. I'm going to review that issue.

**Comment by krydm** [comment]
@thtrieu could you please advise? I'm using darkflow now, tried to train it with yolo-tiny weights and my own top layer, followed the instructions, and everything was running ok. However, the generic yolo/tiny-yolo is trained for lots of classes while I need just one or two(cars, maybe tracks). Yes, I've changed [region] settings and everything worked ok, but my idea was to use udacity training data, which is more specialized, and to glue my last layer there. Udacity does have a ckpt data for tiny-yolo, okay, I got it, it is consumable and I can continue -- however, the ckpt data is loaded through a different loader, and there's no such flexibility as it was with weights and cfg file: if I try to customize my cfg, the system crashes. The problem is in num parameter of [regions]. I need to make it 2, but then when I adjust correspondingly the filters parameter of the last convolutional layer(of course, I have to do it), it naturally conflicts with the data from ckpt, which was saved for a different filters number, causing shape of a different size. I wish I had a way to save ckpt data to weights -- or to train my custoimized last layer over ckpt data in the same way it's doable with weights. I'd appreciate any advise from you. TIA

**Comment by ilayoon** [comment]
@abagshaw As you mentioned above `You can load directly from that checkpoint file`, did you mean the `.meta` file? I have trained different models for example: model A to detect 2 class for 60 epoch,
