### ISSUE TITLE
AttributeError: '_Helper' object has no attribute '_get_fps'

### ISSUE THREAD

**Issue by yanmenglu** [thtrieu/darkflow#259]
@thtrieu ,Hello,when run "python flow  cfg/yolo_old.cfg  --model load/yolo.weights  ".I met this error,could you tell How to resolve it .

Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "***/flow/darkflow/darkflow/cli.py", line 3, in <module>
    from darkflow.net.build import TFNet
  File "***/flow/darkflow/darkflow/net/build.py", line 12, in <module>
    class TFNet(object):
  File "***/flow/darkflow/darkflow/net/build.py", line 26, in TFNet
    _get_fps = help._get_fps
AttributeError: '_Helper' object has no attribute '_get_fps'

**Comment by abagshaw** [comment]
@yanmenglu 

Is that actually the command you are running? Your command should look like this:
`python flow --model cfg/yolo_old.cfg --load load/yolo.weights`

`--model` is for the `.cfg`
`--load` is for the `.weights`

Please try running the above command and see if you still have issues. Also, is there a reason why you are not using `yolo.cfg` with `yolo.weights`?

**Comment by yanmenglu** [comment]
@thtrieu ,I also use the same "python flow --model cfg/yolo_old.cfg --load load/yolo.weights“，but also met the same error.

~/***/darkflow$ python flow     --model   cfg/yolo.cfg    --load  load/yolo.weights  
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/***/Desktop/flow/darkflow/darkflow/cli.py", line 3, in <module>
    from darkflow.net.build import TFNet
  File "/***/Desktop/flow/darkflow/darkflow/net/build.py", line 12, in <module>
    class TFNet(object):
  File "/***/Desktop/flow/darkflow/darkflow/net/build.py", line 26, in TFNet
    _get_fps = help._get_fps
AttributeError: '_Helper' object has no attribute '_get_fps'

**Comment by abagshaw** [comment]
@yanmenglu Can you uninstall darkflow with `pip uninstall darkflow` (if you installed it with pip in the first place) - then re-clone the repository, setup with one of the options described [here](https://github.com/thtrieu/darkflow#getting-started) and then try your command again.

**Comment by yanmenglu** [comment]
@thtrieu ,I didn't install the darkflow,I only clone the darkflow.

**Comment by abagshaw** [comment]
@yanmenglu You need to use one of the three methods outlined [here](https://github.com/thtrieu/darkflow#getting-started) before you start using darkflow. You can't just clone the repository and start using it.

**Comment by yanmenglu** [comment]
@thtrieu Thank you very much. I have resovled it. Because I don't install darkflow.By the way, in the https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU,there isn't have the yolo-voc.weights.Only have the yolo-coco.weights and yolo-voc-tiny.

**Comment by abagshaw** [comment]
The readme also links to https://pjreddie.com/darknet/yolo/ where the most up-to-date weights for YOLOv2 are. You can find the `yolo-voc.weights` link there. [Here](https://pjreddie.com/media/files/yolo-voc.weights) is the direct link. If this has resolved you problem please close this issue. Thanks!

**Comment by yanmenglu** [comment]
ok ,thank you very much .
