### ISSUE TITLE
AssertionError: labels.txt and cfg/yolo-voc.cfg indicate inconsistent class numbers

### ISSUE THREAD

**Issue by mursalal** [thtrieu/darkflow#260]
Hello! I have this error.

Lines in labels.txt = 37

Filters and classes in cfg/yolo-voc.cfg: 210 and 37

What is the problem?

**Comment by EmmanouelP** [comment]
Try making a copy of ### yolo-voc.cfg and give it a new name, e.g yolo-voc-new.cfg, and try using this model

**Comment by mursalal** [comment]
That helped! Thanks @EmmanouelP
