### ISSUE TITLE
preblem of training own classes

### ISSUE THREAD

**Issue by BoXiao123** [thtrieu/darkflow#263]
@thtrieu Hi, thanks for your contribution. I tried to train a new tiny-yolo-voc network with VOC dataset. But I found even I changed the label.txt to one class, such as person. The darkflow still trained all 20 classes. 

Enter training ...
cfg/tiny-yolo-voc.cfg parsing train/Annotations
Parsing for ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor'] 
[====================>]100%  000292.xml
When I tried to modify the "classes" of tiny-yolo-voc.cfg, there was an error
AssertionError: expect 63451056 bytes, found 63471556
 Is there a way to train a specific class or add new classes? Thanks

**Comment by abagshaw** [comment]
I believe what you need to do is create a new configuration file that is a copy of `tiny-yolo-voc.cfg` (leave the original `tiny-yolo-voc.cfg` file unchanged).

Then make the following modifications to your new file (say `tiny-yolo-voc-new.cfg`):
1. Change `classes` in the `[region]` layer (last layer) to the number of classes you are going to train for
2. Change `filters` in the `[convolutional]` layer (second last layer) to **num * (classes + 5)**. For example, in the original `tiny-yolo-voc.cfg` file `num` is 5 and `classes` is 20 so 5 * (20 + 5) is 125 so `filters` is set to 125.
3. Change `labels.txt` to include the label(s) you want to train on (number of labels should be the same as the number of labels you set in the new `.cfg` file).
4. Use a command like this (obviously modify it for your own use case): 
`flow --model cfg/tiny-yolo-voc-new.cfg --load bin/tiny-yolo-voc.weights --train --annotation train/Annotations --dataset train/Images`

That way when darkflow sees you loading `tiny-yolo-voc.weights` it will look for `tiny-yolo-voc.cfg` in your `cfg/` folder and compare that configuration file to the new one you have set with `--model cfg/tiny-yolo-voc-new.cfg`. In this case every layer should be the same except the last two - so it will load the weights into all layers up to the last two but no weights will be loaded for the last two layers. Then training will start.

I'm not 100% all of the above is correct - if anyone sees some mistakes please let me know. I think some explanation like the above should probably be added to the `README.md` to help out those who are getting started with training.

**Comment by BoXiao123** [comment]
@abagshaw Hi, thanks so much. This way works. I used the --model cfg/tiny-yolo-voc.cfg commend before. I saw the code and I agree with you. Thanks for your help.

**Comment by krydm** [comment]
@abagshaw hello, could you please advise? I'm in approximately the same situation, but with ckpt rather than weights. Is there any similar workaround for this case? I've followed the instructions with weights and everything worked fine, exactly like you describe -- the system sees the new cfg file and thus overwrites the top layer etc. Unfortunately, if I try to go in the same way with ckpt, there's a conflict on restore between new and old shapes(see num & classes –– filters relation). Num cannot be changed. There's a separate loader for ckpt, different from the one for weights, and it doesn't know how to work with this overwritten last layer. Have you been in this situation by any chance? TIA

**Comment by ambr89** [comment]
@abagshaw  hello,

as I ask in #522 issue, I don't understand if when I want create new network from my own dataset, I have to use
--load bin/tiny-yolo-downloaded.weights
or not in command line.
And if yes, why?
I've my custom image and annotation.

**Comment by abagshaw** [comment]
@krydm Sorry for letting this slip. Right now, partial loading of weights from checkpoints (`.ckpt`) is not supported. If this is still a feature you are interested in you might want to open a separate issue for that feature request.

@ambr89 I'll address your question in the separate issue.

**Comment by krydm** [comment]
@abagshaw I'm sorry too for missing your answer. It's actually a pretty standard situation when pretrained data needs to be tuned just within the last layer, and folks usually provide ckpt rather than weights. I'll open a feature request, thanks!
