### ISSUE TITLE
Running demo without display

### ISSUE THREAD

**Issue by halt9** [thtrieu/darkflow#269]
Hi,

I have issues with my X server, so I wanted to try running the demo without displaying the image window, just saving the results to a file. Is there an option to do this?

**Comment by abagshaw** [comment]
If by "demo" you are talking about processing a video with darkflow then I believe doing that without displaying the output window is not currently possible - however there is an open pull request (https://github.com/thtrieu/darkflow/pull/207) that directly addresses that - so you'll probably have to wait until that is merged unless you want to pull from his fork.

**Comment by Prakash19921206** [comment]
@halt9, output window is displayed by [this ](https://github.com/thtrieu/darkflow/blob/master/darkflow/net/help.py#L125) line, if you want window to be hidden, then just comment this line 
`#cv2.imshow('', postprocessed)`. I hope that helps

**Comment by halt9** [comment]
Thanks @abagshaw and @Prakash19921206 !
