### ISSUE TITLE
Data is filtered out by "if cx >= S or cy >= S: return None, None" 

### ISSUE THREAD

**Issue by Xianlei** [thtrieu/darkflow#270]
I set the batch size=48 and found that actual number of data in batch is smaller(16 or so).

And I found data is filtered out by this line:
**if cx >= S or cy >= S: return None, None**
https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolo/data.py#L46

No sure why data is filtered out..here is some debug printing:

cx >= W or cy >= H, cx:18.046527777777776, W:13, cy:6.7640625, H:13
cx >= W or cy >= H, cx:21.152083333333334, W:13, cy:6.8046875, H:13
cx >= W or cy >= H, cx:20.34861111111111, W:13, cy:6.875781249999999, H:13

I am using tiny-yolo-voc.cfg. 
(BTW, what's the difference between with tiny-yolo-voc and tiny-yolo?)

Is this because I label data incorrectly?

Thanks

**Comment by abagshaw** [comment]
Not sure about your larger problem - but in regards to the difference between `tiny-yolo-voc.cfg` and `tiny-yolo.cfg` the former is designed for the VOC dataset (20 classes) and the latter is designed for the COCO dataset (80 classes). Both perform quite a bit worse in terms of accuracy (but quite a bit faster) than their non `tiny` counterparts (i.e. `yolo-voc.cfg` and `yolo.cfg`)

**Comment by Xianlei** [comment]
hm..it turns out something wrong with my label..
