### ISSUE TITLE
Can't run flow from Windows command line.

### ISSUE THREAD

**Issue by jubjamie** [thtrieu/darkflow#271]
Hi. Not sure if i've misunderstrood but I can't seem to run darkflow from the command line. It says that `flow is not a recognised [...] command...`

On windows is the only way to run it via a python app?

Thanks

**Comment by abagshaw** [comment]
@jubjamie I use darkflow on Win 10 - the only way I've gotten it to work is use `python flow` in the root of the cloned darkflow folder. I'm not sure how to get the command to be accessible globally - maybe something needs to be added to `PATH`?

**Comment by jubjamie** [comment]
@abagshaw I just tried your suggestion but I get this error:
`ImportError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'` Which I think is because it is using this cloned version of darkflow and not the pip install version (or a similar issue). Perhaps this works better on something like Ubuntu? Or I can copy the flow file to another directory?

Help is appreciated. Thanks

**Comment by jubjamie** [comment]
By moving the flow file out of the directory to somewhere else and running it from there I had no problems. Closing.

**Comment by geroge-gao** [comment]
I met the same question,Have you ever solved the problems

**Comment by MsMansiDhruv** [comment]
I have installed Visual Studio 15. After cloning Github repo, I tried to install all the modules. But I get winerror 3, stating sdk not found in E:\\visualstudio\\lib\\sdks

**Comment by priyamehta01** [comment]
@MsMansiDhruv : Was this solved?
