### ISSUE TITLE
ImportError : No module named 'nms'

### ISSUE THREAD

**Issue by kireoxdz** [thtrieu/darkflow#279]
I'm sorry to bother you, but I'm running the program according to your steps, using Pycharm, tensorflow1.1, opencv3.0, which is wrong and can't be done. Please answer it.

File "darkflow/cython_utils/cy_yolo_findboxes.pyx", line 1, in init cy_yolo_findboxes (darkflow/cython_utils/cy_yolo_findboxes.c:17878)

import numpy as np

ImportError: No module named 'nms'

**Comment by abagshaw** [comment]
How did you install/setup darkflow (i.e. which of the three steps did you choose from [here](https://github.com/thtrieu/darkflow#getting-started))?

**Comment by kireoxdz** [comment]
pip install .

is't wrong?

**Comment by abagshaw** [comment]
No, that's correct. What command are you running (or what code are you using) that results in the error you included above?

**Comment by kireoxdz** [comment]
I run tracking_detect.py in Pycharm , and then I got this warning . The link to the program is https://github.com/ezzeldeen/Multi-Object-Tracking , is't the same program
@abagshaw

**Comment by abagshaw** [comment]
@kireoxdz That repository is using it's own modified version of darkflow. The issue you are having is not with this repository but with the Multi-Object-Tracking one (which is not the latest darkflow version). Please open this issue on their repository and close this issue here. Thanks!

**Comment by kireoxdz** [comment]
@abagshaw Thank you for your help

**Comment by lijiaze2018** [comment]
@abagshaw can you help me that how to use pycharm to run this project？
