### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by MisayaZ** [thtrieu/darkflow#28]
Hi：
    This is a fantastic project and I have read your code. I got confused when I read the part of preporcess in 
Test.py. The image were transformed using scale, translation, however, the annotations were not transformed correctly.

    fix(obj,dims,scale, offs):
        for i in range(1, 5):
            dim = dims[(i + 1) % 2]
            off = offs[(i + 1) % 2]
            obj[i] = int(obj[i]*scale-off)
            obj[i] = max(min(obj[i], dim), 0)

In the code above, you just compare the coords of transformed bounding box with the original dimension of the image, which I think is wrong. you should compare with the transformed image dimension.

**Comment by thtrieu** [comment]
Very nice that you read the code! In fact, if you look into `utils.im_transform.imcv2_affine_trans`. You can see that the original image dimension and the transformed one is the same.

Why's that? `imcv2_affine_trans` work as follows: it chooses a random scaling (bigger than one) to scale the image, and then crop this bigger image into the original size using a random offset. It also randomly decides if the image should be flipped.

I unit tested this several time in the past and they all running fine.

**Comment by MisayaZ** [comment]
Sorry, I have not noticed this line ``im = im[offy : (offy + h), offx : (offx + w)].
It seems that the data augmentation method in this project is not the same as the original YOLO version 2 which randomly crop the image and make pad if necessary.
The reason I ask this question is that I found it return None, None from _batch funchtion frequently for cx >= S or cy >= S while training. It will result in less than 16 samples in a batch.
I think it is more reasonable to remove this obj from allobj if cx >=S or cy >= S, not return None, None

**Comment by thtrieu** [comment]
Agreed. That is one decision I made a long time ago and almost forget about it since the logic is still correct. But you can certainly optimize for it (a pull request is welcomed)

Second, Yolov2's training part is not built yet, so I have no intention to reuse `im_transform` for YOLOv2 training. Since you've been this far in reading the code, I hope you can be the one contributing this part?

**Comment by MisayaZ** [comment]
In fact, the data augmentation in YOLOv2 is almost the same with YOLO v1. I will have a try to implement im_transform for YOLOv2.

**Comment by andresmafladelgado** [comment]
@MisayaZ Since the Data Augmentation is not done for this code, I was thinking of implementing data Augmentation as it is used for YOLO in the training of YOLOv2. However I was wondering if you implemented data augmentation for YOLOv2?
