### ISSUE TITLE
How to visualize feature map for each convolutional layer?

### ISSUE THREAD

**Issue by tankienleong** [thtrieu/darkflow#282]
Hi, is there any way to visualize the feature map for each convolutional layer in darkflow?

**Comment by jubjamie** [comment]
The only way I can think of is to save the model as a protobuf and then get it into stanrdard Tensorflow code to do whatever you please with it. Not sure if that will work but I don't think there's anything in Darkflow itself to do visualisations for you.

**Comment by zhyj3038** [comment]
I am also want to get the featearmap, but now not work in it.  In the predict process, we can get the layer 's output  by name.  and after some reshape, we will get feature map. maybe several days, i will start the work

**Comment by tankienleong** [comment]
@zhyj3038 I manage to visualize the feature map by using your method. Thank you very much!

**Comment by borasy** [comment]
Hi @tankienleong , can you tell me how you do it exactly? I'm trying to visualize the feature map of the last layers.
Thanks in advance

**Comment by borasy** [comment]
Hi @tankienleong, @jubjamie  , can you tell me how you do it exactly? I'm trying to visualize the feature map of the last layers.
Thanks in advance

**Comment by jubjamie** [comment]
I haven't actually done it with Yolo, but see my above comment for how it could be done. Although i'm sure there is a better way!
