### ISSUE TITLE
how to set confidence threshold

### ISSUE THREAD

**Issue by shivam-chandhok** [thtrieu/darkflow#283]
in my output,the images have many bounding boxes even for those classes for which confidence=0.
what can i do so that only those boxes appear which have high confidence above a threshold

**Comment by dimaxano** [comment]
Hi! While evaluation, set --threshold flag

**Comment by shivam-chandhok** [comment]
thankx a lot!!
It worked.

**Comment by Muntasir-mn** [comment]
Hi @shivam-chandhok 
Should I set threshold in this command and which value is best ?
python3 flow --model cfg/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc.weights --train --annotation train/Annotations --dataset train/Images
