### ISSUE TITLE
New yolo weights

### ISSUE THREAD

**Issue by EmmanouelP** [thtrieu/darkflow#285]
What are the new weights for loading with the updated yolo.cfg file? It seems that after the update the weights stored here https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU doesnt seem to match the updated yolo.cfg file.

**Comment by jubjamie** [comment]
You should be able to get the cfg files and their weights straight from https://pjreddie.com/darknet/yolo/ . I had a similar issue with the Google Drive weights so just used the original and they've been working fine for me.
