### ISSUE TITLE
Cannot capture source

### ISSUE THREAD

**Issue by EmmanouelP** [thtrieu/darkflow#287]
I am in Ubuntu and when i try to run a demo using my web cam i get the following error:

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/manolis/darkflow/darkflow/cli.py", line 25, in cliHandler
    tfnet.camera()
  File "/home/manolis/darkflow/darkflow/net/help.py", line 80, in camera
    'Cannot capture source'
AssertionError: Cannot capture source

My exact command is:python3 flow --model cfg/yolo.cfg --load bin/yolo.weights --demo camera.
The same error appears when i try to run demo on a video file.I am on double boot and while on Windows the demos run perfectly fine.Any insight on that?Sorry if this had already been answered.

**Comment by abagshaw** [comment]
Just an idea, maybe try running something like this: https://gist.github.com/tedmiston/6060034 to make sure there's no problems with your OpenCV installation and that it's able to access the camera.

**Comment by vahanhov** [comment]
I have the same issue with Ubuntu 16.04 and Tensorflow 1.4.1. Seems to be an inconsistency of OpenCV versions. After compiling OpenCV on my machines I could make it work for darknet, but not darkflow.

**Comment by onurbarut** [comment]
I have the same problem. I installed opencv first then darkflow. I guess opencv had problem with ffmpeg and didn't capture source. Then I installed opencv using this: https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

now I can reach camera in virtualenv. but when running flow in this virtualenv, still have cannot capture source. Im still trying to solve the issue.

**Comment by wangwh0204** [comment]
ref https://github.com/thtrieu/darkflow/issues/360
pip uninstall opencv-python
conda remove opencv
conda install -c anaconda opencv
fix this issue.
