### ISSUE TITLE
How to generate anchors for my dataset?

### ISSUE THREAD

**Issue by dimaxano** [thtrieu/darkflow#288]
Is it necessary generate anchors for my own dataset to improve quality of the model or won't change with new anchors?

**Comment by Savash2016** [comment]
Yes it is necessary. Yo can have a look here an try to follow this tutorial:
https://github.com/Jumabek/darknet_scripts

**Comment by dimaxano** [comment]
@Savash2016 Did you try to do it by yourself? By this script

**Comment by borasy** [comment]
I think that script is only for VOC.

**Comment by dimaxano** [comment]
Yes, it is. I've made it more general for generating anchors for my dataset. But when I put new anchors in cgf file, results became worse: bounding boxes were in the right place, but they were very small

**Comment by borasy** [comment]
so what do you think we should do? Just leave the original anchors as is?

**Comment by dimaxano** [comment]
@borasy If there are no others' experience of using their own dataset with their own anchors. These anchors works well.

**Comment by borasy** [comment]
alright.. i'll leave it as is then.. Thanks for your experiment. But later if you gain better results with your own anchors please let me know.

**Comment by abhigoku10** [comment]
@Savash2016 @dimaxano  i have a custom dataset for 6 labels is it good to generate anchors ??or by using default anchors how will the result vary any theoretical references

**Comment by dimaxano** [comment]
I would propose to try with script for generating custom anchors for your dataset. Theoretically this is a right way. But I didn't manage to get better results with custom anchors, as i think, cause of wrong use of script for anchor generating)
Summary: try custom anchors, but default are also OK

**Comment by ttorkar** [comment]
I've written a small script so that you can convert to voc labels and then generate anchors boxes based on the above code. Let me know if there is any issues
https://github.com/ttorkar/Voc_Label

**Comment by prashanth-flash** [comment]
@dimaxano have you changed the object_scale parameter in your cfg file? the bounding boxes generated by the script have a scale of 0 to 1
