### ISSUE TITLE
flow --imgdir not working

### ISSUE THREAD

**Issue by zenineasa** [thtrieu/darkflow#298]
Has there been any update in the method to specify the image directory; things aren't working as specified in the readme file. The default directory is also not sample_img/, it turns out to be test/.

Just for confirming whether I have the latest version of darkflow, how to find out the version number? flow --v isn't working either.

**Comment by mgwizdala** [comment]
Everything seems to work fine, just like in readme.

In file darkflow/defaults.py you can see that sample_img is default value for imgdir parameter (again like in documentation) 

Did you try running git status to check if you are up to date?

**Comment by zenineasa** [comment]
Perhaps I had downloaded this a while ago and tried to run it again today. Isn't it possible to keep updating the version number so that everyone could easily check it out. Its showing 1.0.0 in darkflow/version.py in the code that I have downloaded as well as in the one over here.
