### ISSUE TITLE
error when run "./flow --h"  

### ISSUE THREAD

**Issue by jiangyuguang** [thtrieu/darkflow#30]
I am trying to use ./flow --h and I got this error

Traceback (most recent call last):
  File "./flow", line 3, in <module>
    from net.build import TFNet
  File "/home/jiangyug09/jiangyuguang/darkflow-master/net/build.py", line 10, in <module>
    class TFNet(object):
  File "/home/jiangyug09/jiangyuguang/darkflow-master/net/build.py", line 16, in TFNet
    'adagradDA': tf.train.AdagradDAOptimizer,
AttributeError: 'module' object has no attribute 'AdagradDAOptimizer'

**Comment by thtrieu** [comment]
Look like your version of Tensorflow does not have this optimizer. One way to solve this is commenting out the `AdagradDAOptimizer` key in line 16 of `./net/build.py`. Or you can update your Tensorflow to the newest version (0.12 as of this writing)

**Comment by jiangyuguang** [comment]
Thank you， the problem is the version of Tensorflow.
when reinstall tensorflow ,i met error again, so i reinstall ubuntu , solve the problem.
