### ISSUE TITLE
Inquiry_Annotation

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#304]
Are there any tools to help with darkflow annotation ? I am working on udacity annotated dataset. it is in .csv

**Comment by jubjamie** [comment]
The annotation format is based on PASCAL VOC. See #281 for some more ideas and information.

**Comment by benn94** [comment]
@jubjamie finally i found the way to get the annotation working. But i wonder how should i adjust the width and height parameters of the net?

**Comment by jubjamie** [comment]
@benn94 network configurations can be adjusted in the cfg file. See the original darknet project for more info on creating those nets.
