### ISSUE TITLE
Batch size: always 16

### ISSUE THREAD

**Issue by stanifrolov** [thtrieu/darkflow#305]
How come the Batch size is always printing 16, although it is set to 64 in the cfg?

**Comment by tungalbert99** [comment]
The actual batch size is defaulted to 16 in darkflow/defaults.py. To change it, you have to set the flag.

**Comment by stanifrolov** [comment]
Thank you for the fast answer. Can you explain to me what the use of batch is in the net config?
`[net]
batch=64`

**Comment by tungalbert99** [comment]
I don't think this code uses any of it. It's probably just legacy code from the original creator of Yolo CNN who used these config files to set all the variables, but the contributors of darkflow probably deemed it easier to use flags rather than manually edit .cfg files.

**Comment by stanifrolov** [comment]
Thanks! Closing this.
