### ISSUE TITLE
What's the contents of the '.index' and '.data' file in 'ckpt/' folder?

### ISSUE THREAD

**Issue by crazylyf** [thtrieu/darkflow#309]
Hi, what's the contents stored in the `.index` and `.data` files under `ckpt` folder, and how to loader them? I have found how to load `.profile` and `.meta`, but not those two.

**Comment by tungalbert99** [comment]
This is a tensorflow specific attribute that the package uses to store its checkpoints: https://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model
