### ISSUE TITLE
Recommended parameters for training from scratch

### ISSUE THREAD

**Issue by crazylyf** [thtrieu/darkflow#311]
Hi all, has anyone succeed in training yolov2 or tiny-yolov2 from scratch? How to set the parameters?

**Comment by jubjamie** [comment]
See the [readme](https://github.com/thtrieu/darkflow#training-new-model) for information on training with darkflow. You'll need your images and a set of annotations in the darkflow format for your dataset.

**Comment by crazylyf** [comment]
@jubjamie many thanks. I have succeed in training tiny-yolo from scratch, although it is worse than that fine-tuned on pre-trained model.

**Comment by jubjamie** [comment]
That's expected. Glad you got the problem sorted. Please close the issue if your issue has been resolved. :)
