### ISSUE TITLE
Annotation parsing issue

### ISSUE THREAD

**Issue by bestar60** [thtrieu/darkflow#316]
Hi guys

I ran a tiny-yolo model with different datasets (datasets that I made). I constantly get 
`ZeroDivisionError: float division by zero` error.
After reading multiple past issues, I realized that it has something to do with annotation parsing and tried to fix it by deleting the file `net/yolo/parse-history.txt` but it doesn't exist iny my folder.

Any suggestion?

**Comment by bestar60** [comment]
FYI, I'm currently using labels that are not in the label list of COCO or VOC dataset. If I change the labels in `labels.txt` to any labels in those datasets, there are no errors even though my own dataset does not have such labels on.

**Comment by jubjamie** [comment]
Can you reference any past issues you are talking about. Are you creating your datasets correctly and have your labels.txt set properly? Without more information it's hard to help.

**Comment by bestar60** [comment]
I was referrencing to #115 #121. At #115 he also had zero division error so I thought I'm having a similar issue. I have five images all in jpg format in my dataset and I put two labels "coldnoodle" and "hotnoodle" in labels.txt
I made annotations with `labelImg`

`<annotation>
  <folder>100</folder>
  <filename>000001.jpg</filename>
  <path>C:\Users\JK\Documents\your_image_dir\100\000001.jpg</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>970</width>
    <height>545</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>coldnoodle</name>
    <pose>Unspecified</pose>
    <truncated>1</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>368</xmin>
      <ymin>152</ymin>
      <xmax>812</xmax>
      <ymax>545</ymax>
    </bndbox>
  </object>
</annotation>
`

I checked all the annotation files and I found nothing wrong for now.

**Comment by jubjamie** [comment]
So are you getting an error saying you have 0 instances or zero labels or similar?

**Comment by bestar60** [comment]
![error](https://user-images.githubusercontent.com/29770604/27857450-af3ae1f6-61ac-11e7-93f4-a9ca5db02549.jpg)
This is the error I'm getting.
sometimes training works for very few steps and same error occurs.

**Comment by jubjamie** [comment]
Are your config files set up correctly?

**Comment by bestar60** [comment]
[net]
batch=64
subdivisions=8
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
max_batches = 40200
policy=steps
steps=-1,100,20000,30000
scales=.1,10,.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=35
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=2
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=1

I changed the classes to 2 and number of filters of last conv layer to 35.

**Comment by jubjamie** [comment]
The place where you are getting your zero error suggests that you data is at fault. Are you sure your annotations are correct and that none of your images are corrupt?

**Comment by bestar60** [comment]
I realized that few annotation files had size of image as 0. I don't know why this happened...but thanks for the help!

**Comment by EKELE-NNOROM** [comment]
Hi bestar60, how did you find out that the image size was 0
