### ISSUE TITLE
process.py decode lines as unicode and causes exceptions using python2.7

### ISSUE THREAD

**Issue by tammyyang** [thtrieu/darkflow#32]
Hi,

I was using python2.7 and trying to run the flow program on yolo v2 (cfg/yolo.cfg and bin/yolo.weights). However, I always get the following exception:

```
Parsing ./cfg/yolo.cfg
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/tammy/SOURCES/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/tammy/SOURCES/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/home/tammy/SOURCES/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/home/tammy/SOURCES/darkflow/cfg/process.py", line 294, in cfg_yielder
    lx = layers[x]; xtype = lx['type']
TypeError: list indices must be integers, not unicode
```

Then, I realize it was because 
```
[route]
layers=-1,-3
```
in the yolo.cfg causes the problem. 

In line 20, process.py decode lines as unicode. However, it checks `if type(routes) is str` instead of unicode. 

I fixed it in [my branch](https://github.com/tammyyang/darkflow/blob/master/cfg/process.py) by trying to convert routes into integer and handle the exception if the line includes more than one number separated by comma.

**Comment by thtrieu** [comment]
Sorry the code in this repo is in Python 3, should have state that in the README.
