### ISSUE TITLE
Ending training process properly

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#323]
Rather than Ctrl + C, are there any ways to end the training process while it is still training? Could I load the most recent checkpoint from that training?

**Comment by jubjamie** [comment]
I think there is meant to be a max number of training steps but you should be fine to ctrl+c. Then you can load the most recent checkpoint when training for doing inference. Use `"load": -1` to load the most recently trained checkpoint.

**Comment by benn94** [comment]
@jubjamie it seems like it's the only way. thank you.
