### ISSUE TITLE
savepb fails after training with more than 14000 stages

### ISSUE THREAD

**Issue by Savash2016** [thtrieu/darkflow#330]
Hi,
first of all, this is an incredible project. I hope you keep going!!!
I found an error and i hope you fix it soon.

You can  test your "training state" in 2 ways:
1)Directly with this line:
./flow --imgdir sample_img/  --model cfg/yolo-new.cfg --load 1500
or
2) You can first save your training and after this show the result direct from the .pb file. Like this:
flow --model cfg/yolo-new.cfg --load 1500 --savepb
flow --pbLoad built_graph/yolo-new.pb --metaLoad built_graph/yolo-new.meta --imgdir sample_img/

The second way only works if you have .pb files with less than 14000 stages!
If you for example create an .pb file after 40000 stages ( or 300k stages) you see no more boxes in the pridicted pictures. You can try to decrease the Thresh to 0.0000001 you also see nothing.
But the first way always works!!!

This is a big problem because the .pb file have an error!
This is why darkflow does not work anymore in Android if you have a .pb file that ist well trained!!!

I hope i could help you bro and you will fix it soon!

**Comment by lpnueg4** [comment]
Not fix yet, 2018 will coming.

**Comment by lpnueg4** [comment]
@Savash2016 Hi guys, you closed issue, have any solution? help me.

**Comment by teamtoshare** [comment]
Hi, 

has this issue been solved? 

I am facing the same problem after training 37000 stages as mentioned 
 by @Savash2016. When I load my model from the *.pb file I can't predict anything but when using the *.ckpt file it works totally fine.

I think [#297](https://github.com/thtrieu/darkflow/issues/297) and [#597](https://github.com/thtrieu/darkflow/issues/597) are dealing with a similar problem.

Any help much appreciated!

**Comment by alexanderfrey** [comment]
+1

**Comment by janchk** [comment]
49000 steps. load from .pb .meta works fine. Load from  .ckpt works fine too.

**Comment by amirpr24** [comment]
@janchk How did you fix it? plz help me
