### ISSUE TITLE
recall and bound box is not good

### ISSUE THREAD

**Issue by zhyj3038** [thtrieu/darkflow#334]
I have trained my own dataset for 60000 steps, but found the recall is not satisified, only 60% somehow.  and box is not as good also. The lowest  moving average loss is about 1.5,. can not decrease anymore.

I wonder does anyone compared this tensorflow version with the original darnet version?  can darkflow get an counterpart recall or accuracy with the original darknet version YOLO2?  Emotinally I like darkflow. but  I have to emply darflow in my production environment, so I have to ensure which is better, darnet or darflow?

**Comment by tungalbert99** [comment]
Might be related to #104

**Comment by zhyj3038** [comment]
@
