### ISSUE TITLE
Annotation file structure inquiry

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#335]
#281  My annotation file is structured like so. It doesn't have the exact same structure like pascal voc. I wonder whether if my annotation is okay for learning process ?

![xml annotation](https://user-images.githubusercontent.com/8393985/28003275-7926a4fa-6577-11e7-9def-5077e650b54d.png)

**Comment by stanifrolov** [comment]
I recommend to simply try it and check whether the structure of the returned dump is the same. It has to be some kind of list with a nested object list if I remember correctly. Maybe you will need to adapt the `pascal_voc_clean_xml.py` parser or write your own.

**Comment by benn94** [comment]
@stanifrolov thank you. i will look more into it.

**Comment by benn94** [comment]
@stanifrolov I have tried to print out the returned dump in `pascal_voc_clean_xml.py`

here is the output

`[['1479498371963069978.jpg', [1920, 1200, [['Truck', 456, 523, 549, 616], ['Truck', 549, 523, 626, 606]]]], ['1479498372942264998.jpg', [1920, 1200, [['Truck', 369, 529, 469, 625], ['Truck', 473, 529, 551, 612]]]], ['1479498373462797835.jpg', [1920, 1200, [['Truck', 344, 534, 449, 635], ['Truck', 451, 533, 532, 623]]]], ['1479498373962951201.jpg', [1920, 1200, [['Truck', 418, 535, 510, 641], ['Truck', 307, 545, 422, 654]]]], ['1479498374962942172.jpg', [1920, 1200, [['Truck', 48, 564, 166, 667], ['Truck', 171, 564, 262, 658]]]]]`

could you help verifying me whether this is correct ?

**Comment by stanifrolov** [comment]
I believe the reason is that your annotations are not in the same structure as the annotations from the pascal voc dataset. The parser looks for a fixed structure. The simplest way would be to adapt it. Have a look at the code and you will see what I mean.

**Comment by benn94** [comment]
@stanifrolov thanks. Again i would like to verify whether the output of the dataset 2 is the preferred structure?

**Comment by stanifrolov** [comment]
@benn94 Yes, seems good to me.
