### ISSUE TITLE
Prediction: generating bounding box and json files at once

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#336]
How could I generated bb and json files for prediction at once?

**Comment by jubjamie** [comment]
What do you mean? Can you please add more information so we can understand the issue? Do you mean how to get the json file? Are you using command line or inline code?

**Comment by tungalbert99** [comment]
Go in /net/yolov2/predict.py: 
```
if self.FLAGS.json:
		textJSON = json.dumps(resultsForJSON)
		textFile = os.path.splitext(img_name)[0] + ".json"
		with open(textFile, 'w') as f:
			f.write(textJSON)
		return
```
Delete the ```return```. That way if you pass in the --json flag, it will do both.

**Comment by neelkadia** [comment]
How to generate bounding box? I'm using python test.py file from the README

`[{'topleft': {'y': 0, 'x': 0}, 'confidence': 0.50314873, 'bottomright': {'y': 253, 'x': 495}, 'label': 'textbox'}, {'topleft': {'y': 208, 'x': 43}, 'confidence': 0.5031442, 'bottomright': {'y': 374, 'x': 499}, 'label': 'textbox'}]`

**Comment by jubjamie** [comment]
Where is the test.py file? I'm confused as to what you're doing. Can you give full details so I can understand the issue?

**Comment by neelkadia** [comment]
@jubjamie  I was referring to [this]( https://github.com/thtrieu/darkflow#using-darkflow-from-another-python-application) Anyways I've did it myself. I'll add pull request later. I was looking at issues, there are lot of issues where people want to draw bounding box.

**Comment by jubjamie** [comment]
If you are using from your own python program then you should draw the boxes yourself. Darkflow is primarily a port to run the yolo models on Tensorflow. It outputs the data just fine. You can use a couple of lines of openCV to draw the boxes using the output from darkflow. I think there is a misunderstanding of what work people need to do alongside using this project.

**Comment by neelkadia** [comment]
I was expecting output which is shown in Homepage..  But ya I guess you're right. Anyways thanks much :)

**Comment by jubjamie** [comment]
That is available via the demo functions. You can give it an image or a video (and I think a custom model but i've not tried it) and use the --demo flag. This will create some bounding boxes and display them in an openCV viewer.
