### ISSUE TITLE
Adding new class in the trainset

### ISSUE THREAD

**Issue by dimaxano** [thtrieu/darkflow#337]
I've trained a model with `n` classes. Now I want to add one more class. I've changed number of classes in .cfg file (`n+1`). Also changed number of filters on the last layer according to the formula in README.md
And now, i have the next issue
`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [60] rhs shape= [55]`
Is there any variants, how to solve this problem? Thank you!

**Comment by abagshaw** [comment]
Unfortunately I don't think you are able to do what you are trying to do with darkflow right now.

See https://github.com/thtrieu/darkflow/issues/117

**Comment by dimaxano** [comment]
@abagshaw I am very interested in implementing such feature as increasing number of classes and using pretrained model. Could you help me please with pointing the place in the sources where i may start from?

**Comment by abagshaw** [comment]
@dimaxano Unfortunately I have very little expertise in that area. @thtrieu may be able to point you in the right direction - but I think he's pretty busy right now. I don't think adding this functionality is trivial...although I could be wrong.
