### ISSUE TITLE
How to generate .pb file of yolo.cfg

### ISSUE THREAD

**Issue by hank5000** [thtrieu/darkflow#34]
Hi Thtrieu,
    I meet the issue when I using darkflow to generate pb file of yolo.cfg

$ ./flow --model cfg/yolo.cfg --load ../darknet/yolo-voc_final.weights --savepb

and i get the following error:

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
/home/hankwu/DeepLearning/darkflow/dark/darknet.py:54: UserWarning: ./cfg/yolo-voc_final.cfg not found, use cfg/yolo.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/yolo.cfg
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/hankwu/DeepLearning/darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "/home/hankwu/DeepLearning/darkflow/dark/darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "/home/hankwu/DeepLearning/darkflow/dark/darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "/home/hankwu/DeepLearning/darkflow/cfg/process.py", line 294, in cfg_yielder
    lx = layers[x]; xtype = lx['type']
TypeError: list indices must be integers, not unicode

How can I fix it :)

Thank you :)

**Comment by thtrieu** [comment]
The main problem is that my code is written in Python3, please have a look at https://github.com/thtrieu/darkflow/issues/32

**Comment by hank5000** [comment]
Hi Thtrieu,
    Many Thanks about your help :)

Thanks
