### ISSUE TITLE
Error using flow command

### ISSUE THREAD

**Issue by ManojPabani** [thtrieu/darkflow#341]
I was running the code and install flow by:
C:\darknet>pip install flow
After than i tried:
C:\darknet>flow --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights
Its giving me this error :
'flow' is not recognized as an internal or external command,operable program or batch file.
I am using win 7.My steps to use darkflow was:
-I downloaded the code from here.Place it in C:\darknet\
-I downloaded and ran VS C++ 2014 which is required to install darkflow
-Now I was about to test the flow commands to get a json output.
After this I will need to train my own set of images which are of traffic sign.Please guide me

**Comment by isaacdchan** [comment]
Hello Manoj. I am encountering the same error. How did you manage to solve this?

**Comment by mghildiy** [comment]
I try to execute 'flow --h' and I get error:
'flow' is not recognized as an internal or external command,
operable program or batch file.

Anyone could help here?

**Comment by shu-iro** [comment]
After an update of nodeJS, I encountered the same problem.
`npm i flow`, again solve it.

**Comment by thurussian** [comment]
same issue ... anyone found a workaround ?  I really want to make this work now after spending many hours.  

the flow command.  anyhow you slice it flow -h or ./flow -h will return unrecognized command.  However python3 ./flow will just do nothing at all.  I edited flow file to python3 in the first line and took the suggestion of using miniconda env but still not working?!
