### ISSUE TITLE
Output json array is empty

### ISSUE THREAD

**Issue by ManojPabani** [thtrieu/darkflow#345]
I have made my data set which has two type of images of traffic sign
1. motorway 2.Double bend first to left
I have generated annotation using labelImg of each image I have 20,20 images of both sign.
My Steps:
1.I made new config file tiny-yolo-voc-3c.cfg by copy the tiny-yolo-voc.cfg and changed classes=2 and filter=35.
2.I change label.txt removed all existing label and added motorway ,Double bend first to left
3.I downloaded the tiny-yolo-voc.weight from given link and trained my dataset using:
`flow --model cfg/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc.weights --train --annotation train/Annotations --dataset train/Images`
3.After training I put one image which has motor way sign and ran this command:
```
C:\dark>python flow --imgdir sample_img/ --model cfg/tiny-yolo-voc-3c.cfg --load
 bin/tiny-yolo-voc.weights --json
```

It made out>Test.json but it has empty array.
What have i done wrong please guide me.I have attached cmd information file may it will help you to find the issue.
[Tested_Commands.txt](https://github.com/thtrieu/darkflow/files/1159266/Tested_Commands.txt)

**Comment by jubjamie** [comment]
1) You're aware that you hit an error there aren't you?  Looks like you are loading the wrong weights for a different model. Although I think you realised this.

2) You are loading the weights for a different model. Those are not the weights that you trained. You've just loaded the defaults again so you will not get any detections. You'll need to load in a trained checkpoint. You can learn more about loading from training here: https://github.com/thtrieu/darkflow#training-new-model

Try again but loading the model and weights that you've trained and see if you get any more detections.

**Comment by ManojPabani** [comment]
I got error of different **divide by zero** which which was cause by width,height was 0 of one of my image.I removed that image and trained it again.The training reach up to loss 0.423 it got around 7hours then i cancelled the training and tested it again but still got null array.

-Is my step#3 is correct in which i used the downloaded weights?do i need to make my own weights?

-If weight file makes auto then after training where the trained weight saves?I checked every directory but could'nt find the my model's weights.

-Weight did'nt create is this because I stopped the training?if it is how can i limit my epoch(es) to run?as only for 40 images it tooks more than 7hours.

**Comment by jubjamie** [comment]
When you train you don't make a .weights file but you train into a tensorflow checkpoint. If you read the link I posted you will see how it works. A useful shorthand to load the latest generated checkpoint is to use `load=-1`. 

Checkpoints are created every 250 steps I think. You can monitor convergence by tracking the error or using Tensorboard.
You then load the checkpoint into the model and infer with that.

Your training is slow because you are using CPU only. CPU training is slow. Are you taking 7 hours to converge?

**Comment by ManojPabani** [comment]
Ok I tried my checkpoint 1250 with:
C:\dark>python flow --model cfg/tiny-yolo-voc-3c.cfg --load 1250
![double band first 9](https://user-images.githubusercontent.com/9715027/28417870-1ce4595e-6d73-11e7-9a16-535dfccbd0ab.jpg)
it saved the image in sample folder with box how do i get the json with checkpoints?

**Comment by jubjamie** [comment]
did you pass --json?

**Comment by ManojPabani** [comment]
It worked,Thanks.
So when i need to retrain my data i just need to start it from a checkpoint and it will retrain my data.And as i got the checkpoints is working as weight for my dataset right?

**Comment by jubjamie** [comment]
If you want to retrain then you're better off making a new model and getting new checkpoints. The checkpoints are basically your weights. You can freeze them into protobuf files if you require.

**Comment by ManojPabani** [comment]
Can I find a documents about the flow of code  regarding using algorithm to localize and classify the image?

**Comment by jubjamie** [comment]
Not sure what you mean sorry. Do you mean the Yolo paper? If so the Arxiv page is here: https://arxiv.org/abs/1506.02640

**Comment by ManojPabani** [comment]
I meant the flow of darkflow(this code) that how its classifying and localizing the images.What is the start point and where is it algorithm its using.

**Comment by ManojPabani** [comment]
In addition how can I retain my model e.g I have trained a model with 3 classes and stopped at checkpoint 1250.And now i intend to add some more images,annotations and classes to be train with my trained data.Which command i can use to do that.

**Comment by jubjamie** [comment]
This isn't a general discussion thread. I suggest that you file your issues separately so you can get better support.

If you're original issue regarding json is solved, please close it. I will come and help you on new threads if required.

**Comment by RushNuts** [comment]
ManojPabani, do you can resolve your problem? I've problems too
