### ISSUE TITLE
Running darkflow from python and real time video

### ISSUE THREAD

**Issue by arevel190** [thtrieu/darkflow#346]
Hi all,

I would like to know if it is possible to run real-time predictions thru a python script (using a similar structure to the one used with images).

Also, I wanted to know if it is possible to extract predictions live, or having a print statement with all current predictions live.

Thank you very much!

**Comment by jubjamie** [comment]
If you read the front page of this project you will see that this is possible: https://github.com/thtrieu/darkflow#cameravideo-file-demo

**Comment by arevel190** [comment]
@jubjamie Thanks :) , but I was talking about extracting this data to a txt or csv file. Just in case someone wants to do this in the future it can be done by processing each frame being produced by the Open CV camera. Even on CPU it was fairly fast and accurate.
