### ISSUE TITLE
Can it work on Windows?

### ISSUE THREAD

**Issue by caizh666** [thtrieu/darkflow#353]

**Comment by jubjamie** [comment]
Yes

**Comment by VashStampede** [comment]
And how...?

**Comment by caizh666** [comment]
But I can not use the command 'flow' on Windows.

**Comment by jubjamie** [comment]
You need to be running `python flow etc.` in the directory with the flow file. Make sure you install darkflow correctly and it will work fine.

**Comment by caizh666** [comment]
The problem is solved，thanks a lot !!!

**Comment by jubjamie** [comment]
Close the issue if it's solved. You're welcome.
