### ISSUE TITLE
Can I use darkflow to convert darknet.cfg to pb ? (or other classify models)

### ISSUE THREAD

**Issue by hank5000** [thtrieu/darkflow#36]
Hi thtrieu,
    I meet a problem, when i use darkflow to convert darknet.cfg & darknet.weights to pb.

The following is my log:

./flow --model …/darknet/cfg/darknet.cfg --load …/darknet/darknet.weights --savepb --verbalise=True
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
/home/hankwu/DeepLearning/darkflow/dark/darknet.py:54: UserWarning: ./cfg/darknet.cfg not found, use …/darknet/cfg/darknet.cfg instead
cfg_path, FLAGS.model))
Parsing …/darknet/cfg/darknet.cfg
Loading …/darknet/darknet.weights …
Successfully identified 29293936 bytes
Finished in 0.00332188606262s
Traceback (most recent call last):
File “./flow”, line 42, in <module>
tfnet = TFNet(FLAGS)
File “/home/hankwu/DeepLearning/darkflow/net/build.py”, line 41, in init
self.framework = create_framework(*args)
File “/home/hankwu/DeepLearning/darkflow/net/framework.py”, line 43, in create_framework
return this(meta, FLAGS)
File “/home/hankwu/DeepLearning/darkflow/net/framework.py”, line 8, in init
self.constructor(*args)
AttributeError: ‘framework’ object has no attribute ‘constructor’

Many Thanks,
Hank

**Comment by thtrieu** [comment]
I did not pay much attention to implementations of other models besides YOLO. However, I did a quick fix, please pull the new code and retry your command.
