### ISSUE TITLE
Stop Darkflow producing a summary

### ISSUE THREAD

**Issue by jubjamie** [thtrieu/darkflow#365]
Is there a flag to prevent Darkflow from producing a events summary every time it is run?

**Comment by jamesdsmith** [comment]
I've been able to accomplish this by setting the "summary" option to None when initializing the TFNet:

```
from darkflow.net.build import TFNet
options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1, "summary": None}
tfnet = TFNet(options)
```

**Comment by jubjamie** [comment]
I call it through TFNet so that might be perfect! Thanks. I'll check it works before I close it.

**Comment by jubjamie** [comment]
Strange. I just tried this and it still creates a huge summary!

**Comment by abagshaw** [comment]
This workaround is no longer necessary. See https://github.com/thtrieu/darkflow/issues/516#issuecomment-356489901
