### ISSUE TITLE
Parsing classes from pascal voc dataset

### ISSUE THREAD

**Issue by jameskcentrum** [thtrieu/darkflow#368]
Hello,
I want to train a net which will use only 4 classes from pascal voc dataset, so I created new yolo.cfg, change classes, filters and add own_labels. During training I can see - Parsing from xml (Cat, Cow, Dog,Horse) but the dataset size is still 4952, (number of pictures in VOC2007), shouldnt be it lower? like 800-1000pics? After 30k steps I can see some predictions while lowering treshold, but It seems like its using all 20classes but label them only with 4. Also there is no overfit with these 4 classes. Am I doing something wrong?

btw. I trained some another dataset with 5 pictures like it was suggested in different issue and got the high overfit, so train procedure should be ok. 

Thank you

**Comment by CorkyCD** [comment]
I trained it again and its ok now, even after 2k steps I got some reasonable detections, dunno what was wrong before. 

Anyway Darkflow = very nice work! 👍

**Comment by jameskcentrum** [comment]
I trained it again and its ok now, even after 2k steps I got some reasonable detections, dunno what was wrong before.

Anyway Darkflow = very nice work! 👍
