### ISSUE TITLE
How to modify training batch size?

### ISSUE THREAD

**Issue by tankienleong** [thtrieu/darkflow#375]
The training batch size in yolo-voc.cfg file is 64 but I saw the training statistics displayed on terminal is 16 . Which training batch size (64 or 16) is used during the training process?

**Comment by leoxiao2012** [comment]
try using command line args: --batch 64

**Comment by leoxiao2012** [comment]
@tankienleong try using command line args: --batch 64

**Comment by tankienleong** [comment]
@leoxiao2012 thank you very much!
Do you know what is the meaning of subdivisions inside the cfg file? Is there any relationship between the batch size and subdivisions?

**Comment by leoxiao2012** [comment]
@tankienleong as far as i can see, `subdivisions` is unused in the whole program. just leave it there.

**Comment by tankienleong** [comment]
thank you

**Comment by onurbarut** [comment]
@leoxiao2012 hi, to check if your info is up-to-date, is darkflow still not using subdivisions?

**Comment by kilsen512** [comment]
@onurbarut  @leoxiao2012 I opened a new issue #569, have you found out more?
