### ISSUE TITLE
How to use darkflow with checkpoint from another python application?

### ISSUE THREAD

**Issue by SuperMokusn** [thtrieu/darkflow#385]
Hello.
I trained on my own dataset. Then I will use darkflow with the checkpoint file from another python application.
But this dosen't work because of error.
My code is as shown below. The error is " '{} not found'.format(FLAGS.load) AssertionError: -1 not found"

from darkflow.net.build import TFNet
import cv2
options = {"model": "cfg/yolo.cfg", "load": "-1", "threshold": 0.1}
tfnet = TFNet(options)
imgcv = cv2.imread("./sample_img/0.png")
result = tfnet.return_predict(imgcv)
print(result)

What should I input as "load" option?

**Comment by jubjamie** [comment]
You'll need to load an actual checkpoint file but otherwise that should work as you intend.

**Comment by SuperMokusn** [comment]
Thank you for comments.
An actual checkpoint is ckpt/.meta file? I tried to rewrite load option to "load": "ckpt/yolo-2250.meta".(My .meta file name is ckpt/yolo-2250.meta)
But I get another error. The error is "raise IOError("File %s does not exist." % filename) OSError: File ckpt/yolo-2250.meta.meta does not exist."
Why darkflow don't recognize the .meta file...

**Comment by SuperMokusn** [comment]
I notice my mistake!
"load":-1 is correct input. Double quotation is useless.
thank you!

**Comment by jubjamie** [comment]
Didn't spot that. Glad it's sorted!

**Comment by lzane** [comment]
I also meet the same problem, the double quote, Thx~
