### ISSUE TITLE
Should I change cfg width & height?

### ISSUE THREAD

**Issue by seaswander** [thtrieu/darkflow#388]
I'm trying to train on my own dataset, after 1000 epoches, I get no result. I changed class to 2 and last conv to 35. I didn't see anything about resolution mentioned in readme. But since yolo only work on same resolution, do I suppose to change width & height to fit my own camera?

**Comment by baristahell** [comment]
Had the same issue, my training was really bad and then i realized you could change height/width in the cfg to any multiple of 32 (so your feature map grid is always multiples of 13).

Helped A LOT for me.

**Comment by ambr89** [comment]
I've the same issue too, Can I set width and height minus 416?

**Comment by seaswander** [comment]
@baristahell Glad this thread helped you.
@ambr89 What do you mean minus 416? Negative? My memory is a little fade, I think you ought to change it according to camera resolution.
