### ISSUE TITLE
Error while running YOLO v2 demo

### ISSUE THREAD

**Issue by seongkyun** [thtrieu/darkflow#396]
i was build this thing on anaconda2 environment

os : ubuntu 16.04
python : anaconda 2 and made py35 environment

i already installed dependencies like tensorflow1.2, opencv 3 and so on.
and successfully import and run example codes.

after that, i tried to run demo 
`$ source activate py35`
`$ cd darkflow`
`$ flow --model cfg/yolo.cfg --load yolo.weights --demo sample_img/720.mp4 --gpu 1.0`

then it prints out

Traceback (most recent call last):
  File "/home/han/anaconda2/envs/py35/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/han/darkflow/flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/han/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/han/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/home/han/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/home/han/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/home/han/darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ImportError: /home/han/darkflow/darkflow/cython_utils/cy_yolo_findboxes.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

can anybody tell me how solve it?

please help me guys :)

**Comment by rlan** [comment]
Just a sanity check, did you run "python3 setup.py build_ext --inplace"?

**Comment by aggx** [comment]
How do you have your python versions configured?  I ran into what appears to be the same issue.  By default **flow** tried to run in python2.  Try changing the **flow** script from `#! /usr/bin/env python` to `#! /usr/bin/env python3`

**Comment by seongkyun** [comment]
It works. thanks.

**Comment by anuragvij264** [comment]
I am trying to run flow file in floydhub and I am getting this
ImportError: /output/darkflow/cython_utils/nms.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf 
I also changed the shebang but the same error reappears.

**Comment by kribby** [comment]
@anuragvij I incurred this problem and solved it by entering the following command:
python3 setup.py build_ext --inplace

(I assume you used the python 3 +tensorflow 1.5 instance?)
