### ISSUE TITLE
Cannot install on windows 10

### ISSUE THREAD

**Issue by j-fan** [thtrieu/darkflow#399]
I am having trouble installing on windows 10, I get the error   "The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib". 

Does it have to use visual studio 14? How would I be able to change it to use the version of visual studio I have (which is 15)

Here is the console output:
![capture](https://user-images.githubusercontent.com/18587785/30373007-3191d338-98c3-11e7-835a-75f4ed5ca1d9.PNG)

**Comment by muddassir235** [comment]
Same issue!

**Comment by j-fan** [comment]
This doesn't directly fix this issue, but if your goal is just to do object detection you might want to consider tensorflow's version instead: https://github.com/tensorflow/models/tree/master/object_detection

And matching video tutorial if you're a noob like me: https://www.youtube.com/watch?v=COlbP62-B-U

**Comment by bpradhan08** [comment]
Hey,
Did you get a solution?

**Comment by j-fan** [comment]
I used another tensorflow implementation which is listed above

**Comment by ShazidAraf** [comment]
same issue. What is the solution of this matter?

**Comment by johnny12150** [comment]
> same issue. What is the solution of this matter?

WSL2 with GPU
