### ISSUE TITLE
tensorflow-yolo demo gives negative confidence

### ISSUE THREAD

**Issue by hiroyamaeda** [thtrieu/darkflow#41]
Thank you for your repository!
I used this repo to make .pb file from .weights.
And then I put my .pb file into tensorflow-yolo detector demo(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java).
But this code gave me negative confidence in line 236!
If you know something about it, could you inform me?
What is the relationship between "threshold" in darkflow and "confidence, maxclass" in the above code?
Thank you

**Comment by thtrieu** [comment]
Please specify the steps to reproduce this error.
