### ISSUE TITLE
Changing settings in yolo.cfg

### ISSUE THREAD

**Issue by srafay** [thtrieu/darkflow#420]
The first few lines in yolo.cfg are:

```
[net]
# Testing
batch=1
subdivisions=1
# Training
# batch=64
# subdivisions=8
```

During the training, shouldn't i comment out batch=1 and subdivisions=1 and train my model with batch=64 and subdivisions=8 ?

batch=1 and subdivisions=1 is set like this only when we are testing our model right?

**Comment by johaq** [comment]
You can train with batch and subdivision equal 1. It just takes a long time.
If I remember correctly batch is the amount of images loaded into memory at once and subdivisions means how many images are processed at once. 
You should set those as high as your vram allows you for the fastest possible training. Just make sure that `batch % subdivisions = 0`

**Comment by srafay** [comment]
Alright thanks!
