### ISSUE TITLE
Questions about coordinates from json output

### ISSUE THREAD

**Issue by NaJaeMin7** [thtrieu/darkflow#424]
In json files, 
ex) [{"label":"person", "confidence": 0.56, "topleft": {"x": 184, "y": 101}, "bottomright": {"x": 274, "y": 382}}

I can`t understand how 'y coordinates of topleft' is smaller than 'y coordinates of bottomright' ???

**Comment by rlan** [comment]
The origin is at the upper left corner of an image.

**Comment by NaJaeMin7** [comment]
@rlan Thanks for your reply. but I`m still confused. You mean that the y coordinates are all negative?

**Comment by rlan** [comment]
If an image is 640 pixel wide by 480 pixel high, then the upper left corner
is (0,0). Lower right corner is (639, 479).
