### ISSUE TITLE
How can I load .meta and .profile files?

### ISSUE THREAD

**Issue by NaJaeMin7** [thtrieu/darkflow#426]
from darkflow.net.build import TFNet
import cv2
options = {"model": "cfg/my_yolo.cfg", **"load": "bin/yolo.weights"**, "labels" :"my_labels.txt", "gpu":0.0}
tfnet = TFNet(options)
imgcv = cv2.imread("./sample_img/dog.jpg")
result = tfnet.return_predict(imgcv)
print(result)

----------------------------------------------------
In this code, How can I use  .profile or .meta files from my training outputs?
I tried with "metaLoad" : ckpt/my_yolo-3100.meta" ... but it doesn`t work.
"load": -1 is working well, but I want to try with .meta and .profile data.

**Comment by Deeksha-K** [comment]
Did you manage to find a solution for this? Thanks.

**Comment by ProtossDragoon** [comment]
solved?
