### ISSUE TITLE
Producing numerous rectangle

### ISSUE THREAD

**Issue by normansiboro** [thtrieu/darkflow#437]
I already follow the steps but when forward the image inside sample_img, it produce image having numerous rectangle instead of giving rectangle only for detected object having high confidence

**Comment by nerdykamil** [comment]
Have you tried increasing threshold value?

**Comment by normansiboro** [comment]
I am sorry, my bad
I saw in tiny-yolo.cfg file that there was a default number of thresh value but I actually used yolo-tiny.cfg which didn't have default value of threshold for my detection

Thank you for your suggestion
