### ISSUE TITLE
my dataset is tfrecord,I want to know how to train my own dataset?

### ISSUE THREAD

**Issue by geroge-gao** [thtrieu/darkflow#440]
I convert a dataset to tfrecord format,I want to know how can I train it,or is the darkflow can only be used to train VOC dataset?

**Comment by omg777** [comment]
@geroge-gao Hi, Did you success on using tfrecord data ?

**Comment by geroge-gao** [comment]
@omg777 yes

**Comment by k-lyda** [comment]
@geroge-gao, could you please share the details, how you achieved this? :)
