### ISSUE TITLE
ImportError: No module named 'darkflow.cli'

### ISSUE THREAD

**Issue by mohammedjasam** [thtrieu/darkflow#446]
I have just installed darkflow using pip3 install .

when i run flow it gives me this module not found error!

**Comment by Kholio** [comment]
Same here

**Comment by tugot17** [comment]
I have "fixed" this issue by pasting darkflow folder into usr/local/bin. But this caused new problem: 
" File "darkflow/cython_utils/cy_yolo_findboxes.pyx", line 1, in init cy_yolo_findboxes
    import numpy as np
ImportError: No module named 'nms' "

**Comment by Snorfermino** [comment]
i have the same isue
