### ISSUE TITLE
(suggestion) Generate text file of predicted bounding boxes

### ISSUE THREAD

**Issue by apple2373** [thtrieu/darkflow#45]
HI, Trinh,

Thank you for providing neatly organized codes to use YOLO2 in tensorflow. 

I wanted to generate text file of predicted bounding boxes,  with original YOLO2 implementation; 
https://groups.google.com/forum/#!searchin/darknet/text$20output%7Csort:relevance/darknet/ylEWe3JUKrE/OG--eSmiCwAJ

But I gave up due to my poor knowledge on C. Then I found this implementation and made it. I did not have time to analyze your implementation, so my way is very simple. I just added a few lines. Especially something like the below around here: https://github.com/thtrieu/darkflow/blob/718e756bfad9054ea7c88ff7e52729ea3157fcfc/net/yolov2/test.py#L86
```f.write("%s,%s,%d,%d,%d,%d\n"%(im,label,left,right,top,bot))```

 I guess it's easy for you to add a flag to output json or text file instead of annotated images. When you have time, can you please do that? 

Regards,
Satoshi

**Comment by silvergasp** [comment]
Hi I have a similar need and have created a simple json marshaller see my [pull request](https://github.com/thtrieu/darkflow/pull/64).
