### ISSUE TITLE
'flow' is not recognized as in internal or external command

### ISSUE THREAD

**Issue by isaacdchan** [thtrieu/darkflow#452]
Tried to install darkflow all three ways presented in getting started. Each time I tried running ```flow --h``` I received the error in the title. All my dependencies are downloaded and up to date, I've tried running as flow and ./flow. Any help?

**Comment by ttorkar** [comment]
I assume you're running on Windows. Try running it as "python flow ...."

**Comment by isaacdchan** [comment]
This is the error I got.

```C:\Users\isaac\Documents\STEM\Self Driving League\darkflow>python flow

Parsing
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\dark\darknet.py", line 17, in __init__
    src_parsed = self.parse_cfg(self.src_cfg, FLAGS)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\dark\darknet.py", line 68, in parse_cfg
    for i, info in enumerate(cfg_layers):
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\process.py", line 66, in cfg_yielder
    layers, meta = parser(model); yield meta;
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\process.py", line 17, in parser
    with open(model, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

C:\Users\isaac\Documents\STEM\Self Driving League\darkflow>```

**Comment by ttorkar** [comment]
What is the complete command you are using?

**Comment by isaacdchan** [comment]
I have downloaded and moved the tiny yolo weights into my darkflow folder. The command I used was the ```flow --h```

**Comment by ttorkar** [comment]
Are you using Windows? If so, you'll need to preface your commands with `python` so it would be `python flow --h`

**Comment by isaacdchan** [comment]
Hey it worked! 

It's strange because I tried doing ```python flow --h``` beforehand and it didn't work. Maybe I was in the wrong directory. Thank you.

**Comment by aboodi46** [comment]
in which directory should i put tiny_yolo. weights?

**Comment by isaacdchan** [comment]
bin folder. cfg files are preloaded in the cfg folder.

**Comment by aboodi46** [comment]
thanks

**Comment by SurajDonthi** [comment]
@isaacdchan in which directory should you run the `python flow --h`.

**Comment by Invexh** [comment]
I just ran into a similar issue and solved it by executing `python flow --h` inside the darkflow-master directory.

**Comment by abhrasky** [comment]
i am trying to do inside darkflow master folder but it is not working :(

**Comment by shaneburns111** [comment]
Hi. I am getting the exact same issue running on Ubuntu 16.04. Any ideas on the fix for this?

**Comment by jedrendelima** [comment]
> i am trying to do inside darkflow master folder but it is not working :(

have you fixed this having same issue

**Comment by titustum** [comment]
If you start with the python command things will be better.

> `python flow --h`
