### ISSUE TITLE
Change labels?

### ISSUE THREAD

**Issue by dankm8** [thtrieu/darkflow#456]
I want to change the labels of the object. For example change the "person" label to "dog", but I can't seem to get it working. 
Any help ?

**Comment by ttorkar** [comment]
You might have to explain a bit more, I don't completely understand your intention.

**Comment by dankm8** [comment]
Okay. Well I want the algorithm to work normally, detecting objects, but I want to change the names of the labels. So when it sees a person, the boundary box says dog instead of person.

Hope that makes sense ? :D
