### ISSUE TITLE
Loading different checkpoints for different nets

### ISSUE THREAD

**Issue by ilayoon** [thtrieu/darkflow#457]
For example, I have two different networks trained separately Model A is trained first then Model B .
Model A: after training for 60 epoch => I've got : yolo-voc-A-15000
Model B: after training for 60 epoch => I've got : yolo-voc-B-15000

`--load [checkpoint_num]`
how should I load the checkpoint of Model A ?

**Comment by billyes** [comment]
If you want to load for saving meta and pb
flow --model cfg/model A --load 15000 --savepb

If you want to continue your training at this step
change --load bin/weight to --load 15000 and keep the rest of training command the same

**Comment by ilayoon** [comment]
thank you i got it now.
