### ISSUE TITLE
Rename labels

### ISSUE THREAD

**Issue by dankm8** [thtrieu/darkflow#458]
Sorry for the newbie issue.

Is there a way to rename the labels of the pretrained datasets ?

**Comment by abagshaw** [comment]
Do you mean map existing labels to new ones, i.e. `person` -> `human` or something like that?

**Comment by dankm8** [comment]
Yes and thanks for the reply, but I found out that renaming the labels in misc.py did the trick when using the normal tiny-yolo.
Or changing the labels-txt, when using tiny-yolo-c4.
