### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xunkaixin** [thtrieu/darkflow#46]
I am trying to train the darkflow :
    python3 ./flow.py --model cfg/tiny-yolo-4c.cfg --train --trainer adam
I get this error
Parsing cfg/tiny-yolo-4c.cfg
Loading None ...
Finished in 4.506111145019531e-05s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | sele 1x1p0_1    linear           | (?, 13, 13, 45)
-------+--------+----------------------------------+---------------
Running entirely on CPU
cfg/tiny-yolo-4c.cfg loss hyper-parameters:
	H       = 13
	W       = 13
	box     = 5
	classes = 4
	scales  = [1.0, 5.0, 1.0, 1.0]
Traceback (most recent call last):
  File "./flow.py", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/qkj/projects/darkflow/net/build.py", line 51, in __init__
    self.setup_meta_ops()
  File "/home/qkj/projects/darkflow/net/build.py", line 94, in setup_meta_ops
    if self.FLAGS.train: self.build_train_op()
  File "/home/qkj/projects/darkflow/net/help.py", line 15, in build_train_op
    self.framework.loss(self.out)
  File "/home/qkj/projects/darkflow/net/yolov2/train.py", line 61, in loss
    coords = tf.concat(3, [adjusted_coords_xy, adjusted_coords_wh])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 1053, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by thtrieu** [comment]
@ryansun1900  please check this out.

**Comment by xunkaixin** [comment]
thank you!

**Comment by ryansun1900** [comment]
./flow --model cfg/tiny-yolo-4c.cfg --train --trainer adam
This command works for me. Could you check this issue again?

**Comment by xunkaixin** [comment]
I will try to debug the code,and solve the problem.As more info surfaces about this, I will keep you informed

**Comment by thtrieu** [comment]
I also cannot reproduce your error. Are you using Python3 and Tensorflow 0.12?

**Comment by xunkaixin** [comment]
yes. Python3  Tensorflow 0.12.1  opencv3.  I did not specify the training data, I do not know whether this problem. I can test and produce the right results, but can not train.

**Comment by xunkaixin** [comment]
"pythonPath": "/usr/bin/python3",
            "program": "/home/qkj/projects/darkflow/flow.py",
            "args": ["--model=/home/qkj/projects/darkflow/cfg/tiny-yolo-voc.cfg",
             "--train",
             "--trainer=adam",
             "--annotation=/home/qkj/projects/SSD/data/VOCdevkit/VOC2012/Annotations",
             "--dataset=/home/qkj/projects/SSD/data/VOCdevkit/VOC2012/JPEGImages"
![2017-02-08 10 10 53](https://cloud.githubusercontent.com/assets/11584137/22720952/f0e7e5dc-ede8-11e6-88c7-ed6acc18595f.png)

**Comment by xunkaixin** [comment]
the running problems code   "coords = tf.concat(3, [adjusted_coords_xy, adjusted_coords_wh]) "
i cannot resolve it

**Comment by xunkaixin** [comment]
qkj@qkj-HP:~/projects/darkflow$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'0.12.head'

**Comment by thtrieu** [comment]
I suspect you are using the wrong version of Tensorflow, please confirm the following code returns the correct version:
```
python3 -c "import tensorflow as tf; print(tf.__version__)"
```
If it does, then I suggest trying the following concat instead:
```python
coords = tf.concat([adjusted_coords_xy, adjusted_coords_wh], 3) 
```

**Comment by xunkaixin** [comment]
qkj@qkj-HP:~/projects/darkflow$ python3 -c "import tensorflow as tf; print(tf.__version__)"
0.12.head
qkj@qkj-HP:~/projects/darkflow$

**Comment by xunkaixin** [comment]
the code "coords = tf.concat([adjusted_coords_xy, adjusted_coords_wh], 3) "  works well

**Comment by xunkaixin** [comment]
all of code about "tf.concat" need to change....   Why can't I execute that code "coords = tf.concat(3, [adjusted_coords_xy, adjusted_coords_wh])"?

**Comment by thtrieu** [comment]
I believe there is a change in API in the tensorflow `0.12.head` you pulled. Updating tensorflow might certainly help.

**Comment by xunkaixin** [comment]
thank you very much, i will try to updating tensorflow.

**Comment by xunkaixin** [comment]
i have try to update tensorflow. the version is 0.12.1, which is the same as before. the print is 0.12.head.
i think the version you are using is relatively old. i have change the code, as follows
tf.concat(3,A) -> tf.concat(A, 3)   
tf.mul -> tf.multiply 
it works well now , and can train.

And i have try the  tensorflow 1.0, it does not work.

I suggest you specify the specific version number,  such as tensorflow 0.12.0...

Thank you very much for your work, I will continue to pay attention to your work

**Comment by thtrieu** [comment]
Official documentation from tensorflow [here](https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#concat) shows `tf.concat(3, list_of_tensor)` is the correct syntax.

Nevertheless, we'll consider moving on to tensorflow `1.0` when it goes mainstream. Thanks for your suggestion.
