### ISSUE TITLE
What about images with no labels?

### ISSUE THREAD

**Issue by dkermany** [thtrieu/darkflow#478]
If you want to train on images with no objects from your classes present and therefore do not have any XML annotations with them, how does the model update from these images? 

My desire is to have the model learn to recognize better when objects are actually present by including cases where they are absent. In order to do this, do I need to make an XML file framework for each of these images and just not include any objects, Don't include an XML at all, or would I need to code my thang?

**Comment by HebaAladdin** [comment]
did you find an answer for this as i have the same issue ?

**Comment by sheerun** [comment]
I have the same question

**Comment by Ridhwanluthra** [comment]
I had to do the same thing, just make an XML framework for each of the images just dont add any objects it works fine

**Comment by sheerun** [comment]
The question is not how to do it, but how darkflow reacts for such examples i.e. if it introduces penalty if there are bounding boxes created on image that has no bounding boxes.

**Comment by rauar** [comment]
@sheerun I think the OP really asked if you need to create an XML file if there's none of the classes on an image. And I think that was a valid question (I had/have it too and it's not obvious what darkflow expects in that case). I think creating XML without objects being listed is the safest approach. In case it's possible to completely omit an XML and darkflow still considered the image (without XML annotations) during training I'd be glad to hear that as it makes life easier.

W.r.t to your question with penalty: I think the loss is the gap between boxes and their dimensions. If there's something detected which is actually not present then loss is higher (what you described as penalty).
