### ISSUE TITLE
Use pretrained with custom output class

### ISSUE THREAD

**Issue by pribadihcr** [thtrieu/darkflow#48]
Hi,

When I was training the new model using tiny-yolo-voc with custom dataset  with five number of class, and also using tiny-yolo-voc.weights, I got the following error:

Loading bin/tiny-yolo-voc.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "darkflow/utils/loader.py", line 76, in load
    walker.offset, walker.size)
AssertionError: expect 63164056 bytes, found 63471556

**Comment by thtrieu** [comment]
Make sure you edit the `.cfg` correctly. Namely 

- In the last layer, `classes` should be `5`
- In the penultimate layer, number of channels is `num * (classes + 5)`.

**Comment by pribadihcr** [comment]
I have edited it before.
[net]
batch=64
subdivisions=8
width=96
height=96
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
max_batches = 40100
policy=steps
steps=-1,100,20000,30000
scales=.1,10,.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=50
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=5
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .5
random=1

**Comment by thtrieu** [comment]
What is the bash command? Please identify the steps to reproduce this error, otherwise it is going to cost a lot of time debugging a potentially small error.

**Comment by pribadihcr** [comment]
..$./flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --train --gpu 1.0
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Parsing ./cfg/tiny-yolo-voc.cfg
Parsing cfg/tiny-yolo-voc.cfg
Loading bin/tiny-yolo-voc.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "../darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "../darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "../darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "../darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "../darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "../darkflow/utils/loader.py", line 76, in load
    walker.offset, walker.size)
AssertionError: expect 63164056 bytes, found 63471556

**Comment by thtrieu** [comment]
This is simply because `tiny-yolo-voc.weights` does not correspond to `tiny-yolo-voc.cfg`. You must rename the `.cfg` to `tiny-yolo-voc-5c.cfg` or something else, so that the program will understand you are doing a partial load.

**Comment by pribadihcr** [comment]
I have the same error:
..$./flow --model cfg/tiny-yolo-voc-5c.cfg --load bin/tiny-yolo-voc.weights --train --gpu 1.0
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Parsing ./cfg/tiny-yolo-voc.cfg
Parsing cfg/tiny-yolo-voc-5c.cfg
Loading bin/tiny-yolo-voc.weights ...
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "../darkflow/net/build.py", line 34, in __init__
    darknet = Darknet(FLAGS)
  File "../darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "../darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "../darkflow/utils/loader.py", line 104, in create_loader
    return load_type(path, cfg)
  File "../darkflow/utils/loader.py", line 18, in __init__
    self.load(*args)
  File "../darkflow/utils/loader.py", line 76, in load
    walker.offset, walker.size)
AssertionError: expect 63164056 bytes, found 63471556

**Comment by thtrieu** [comment]
make sure your `./cfg/tiny-yolo-voc.cfg` is still the same 20 class configuration.

**Comment by pribadihcr** [comment]
Thanks. it works
