### ISSUE TITLE
Can't fine tune to reduce the number of labels

### ISSUE THREAD

**Issue by GuimExc** [thtrieu/darkflow#483]
Hi,

first of all, thanks for this repo, it has been extremely useful.

I'm having the popular `AssertionError: expect x bytes, found y` when trying to reduce the number of output classes for `yolo.cfg` and `yolo.weights`. Basically, I want to retrain the model to reduce the number of labels from 80 to 13. I have followed the instructions in the README.md, which are:

1. Modify `labels.txt` with the labels I want to train with (13 in total).
2. Make a copy of `yolo.cfg` called `yolo_label_subset.cfg` and:
   2.1 Modify `classes` in the `[region]` layer from to 80 to 13.
   2.2 Modify `filters` in the last `[convolutional]` layers to 90 (`num * (classes + 5)`)

And then I would call:

`./flow --model cfg/yolo_label_subset.cfg --load bin/yolo.weights --train --dataset "/COCO_dataset/train2017" --annotation "/COCO_dataset/annotations"`

For which I get: `AssertionError: expect 202560760 bytes, found 203934260`

I've also taken a look at similar posted issues. Issue https://github.com/thtrieu/darkflow/issues/39 specifically is very similar, but after following the steps mentioned there, it still doesn't work. These steps are:

1. Change my weight file name so it matches my cfg file name: I rename `yolo.weights` to `yolo_label_subset.weights`.
2. Add `--config cfg/` parameter.

The input command then is: 
`./flow --model cfg/yolo_label_subset.cfg --load bin/yolo_label_subset.weights --config cfg/ --train --dataset "/COCO_dataset/train2017" --annotation "/COCO_dataset/annotations"`

And I get exactly the same error as before: `AssertionError: expect 202560760 bytes, found 203934260`

I have also tried to change the `offset` from 16 to 20, as suggested in https://github.com/thtrieu/darkflow/issues/338. This, however, doesn't work either.

Thanks for taking the time to read this. Any help would be appreciated :)

**Comment by kilsen512** [comment]
Hi @GuimExc , 
so I had a similar problem. I solved it by making sure that I have the correct config file matching the weight file name in the cfg folder. 
So instead of renaming the weights to match your current config, rename it so that the weight file name matches the config it was created originally created with.

Hope it was clear.
Happy holidays!

**Comment by gangooteli** [comment]
I also faced this issue.
There is no need for renaming weights file.
First decide which base cfg file you need to use and will make changes in future according to your classes.
Lets say you decided on "X.cfg" file (lets assume it X )
Now first check which pre-trained weights are working with base cfg "X.cfg" file
There are various weights file which you can download uploaded by thtrieu.
Check by trying each of those weights with X.cfg file.

Now you got correct weights for X.cfg file( lets assume its name is Y.weights)
Now you can make your desired changes in X.cfg and save as X_modified.cfg
Now use it with Y.weights. It should work.

**Comment by nxy** [comment]
Change your command to

./flow --model cfg/yolo_label_subset.cfg --load bin/yolo.weights --config cfg/ --train --dataset "/COCO_dataset/train2017" --annotation "/COCO_dataset/annotations"

Make sure your "yolo_label_subset.cfg" came from "yolo,cfg" (modified of course with the correct classes/filters)

**Comment by GuimExc** [comment]
Thanks for the comments.

I already tried the solutions proposed here, none of them work, unfortunately. The error is the same:

`AssertionError: expect 202560760 bytes, found 203934260`

I also made sure that the original unchanged config file could train with the weights file. That is, I can train without problems with this command:

`--model cfg/yolo.cfg --load models/yolo.weights --train --dataset "/disk2/COCO_dataset/train2017" --annotation "/disk2/COCO_dataset/annotations"`

But not this one, with my customized config file derived from `yolo.cfg`:

`--model cfg/yolo_label_subset.cfg --load models/yolo.weights --train --dataset "/disk2/COCO_dataset/train2017" --annotation "/disk2/COCO_dataset/annotations"`

**Comment by gangooteli** [comment]
could you send the snapshot of difference between yolo.cfg and yolo_label_subset.cfg using yolo_label_subset.cfg. 
One more thing you need to keep original yolo.cfg as it is. And make a copy of that and then make changes.

**Comment by GuimExc** [comment]
> One more thing you need to keep original yolo.cfg as it is. And make a copy of that and then make changes.

Yep, this is something I have done from the beginning.

Here's the screenshot of the difference between yolo.cfg (left) and yolo_label_subset.cfg (right):
![yolo cfg_vs_yolo_label_subset](https://user-images.githubusercontent.com/29301768/34681508-ff8efd20-f493-11e7-8395-f900146e20ee.png)

**Comment by gangooteli** [comment]
I don't find any error in cfg file. 
One more thing which I can tell is I downloaded weights from this link https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU
and tried for **yolo-full.weights** and **yolo.weights**. One of them was working fine. Then I changed the .cfg file. I didn't made changes in architecture. Only made changes in filters and classes

This is my modified cfg file for your reference:

**Comment by GuimExc** [comment]
`yolo.weights` is the correct file in my case. I tried to run your config file (I name it `yolo_modified.cfg`) and I have the exact same problem.

`AssertionError: expect 202314760 bytes, found 203934260`

 This is the command I use:

`./flow --model cfg/yolo_random.cfg --load models/yolo.weights --train --dataset "/disk2/COCO_dataset/train2017" --annotation "/disk2/COCO_dataset/annotations"`

Are you able to train with `yolo.weights` using the config file you shared?

**Comment by GuimExc** [comment]
Turns out I changed some pieces of the original code and that was the reason it was not working. The program runs fine now.
