### ISSUE TITLE
Tensorflow . module error

### ISSUE THREAD

**Issue by antimlgpro** [thtrieu/darkflow#491]
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/Users/Ludvig/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/Users/Ludvig/darkflow/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by Ridhwanluthra** [comment]
do you have tensorflow installed on your system?

**Comment by nxy** [comment]
you need to install tenslow with pip

**Comment by zboinek** [comment]
I neeed to refresh subject.
I have tensorflow 1.9.0 for python3 installed od my machine
`jadsfsad@jdsdP:~/darkflow$ python3 -c "import tensorflow as tf; print(tf.__version__)"
1.9.0`
do I need it for python2? I can see that there is problem with that. And even after installation with pip I can't import TF in python 2.7.

**Comment by Maria-UET** [comment]
Try running flow like:
`python flow --help`
instead of:
`flow --help`
