### ISSUE TITLE
flow not working correctly

### ISSUE THREAD

**Issue by IvanReznikov** [thtrieu/darkflow#492]
After installing everything that is necessary, I launch flow --h and a file opens with the following code: 
#!c:\python36\python.exe
# EASY-INSTALL-DEV-SCRIPT: 'darkflow==1.0.0','flow'
__requires__ = 'darkflow==1.0.0'
__import__('pkg_resources').require('darkflow==1.0.0')
__file__ = 'D:\\MarkProject\\Camera\\darknet\\darkflow\\flow'
exec(compile(open(__file__).read(), __file__, 'exec'))

What may be the problem?

**Comment by IvanReznikov** [comment]
ok, it seems it makes sense to include python before flow

**Comment by abagshaw** [comment]
Has this issue been resolved?

**Comment by thurussian** [comment]
it has not.  the flow command.  anyhow you slice it flow -h or ./flow -h will return unrecognized command.  However python3 ./flow will just do nothing at all.  I edited flow file to python3 in the first line and took the suggestion of using miniconda env but still not working?!
