### ISSUE TITLE
How to get Json output with the video mode of the Yolo

### ISSUE THREAD

**Issue by BillCai06** [thtrieu/darkflow#505]
I try to get the X and Y reading of the detected objects in the a video or live cam. It that possible without farm by farm

**Comment by abagshaw** [comment]
Currently only two output modes are supported for video processing: save annotated video to file _or_ view the annotated video live.

For now, you could build a small python wrapper script that invokes [`return_predict()`](https://github.com/thtrieu/darkflow#using-darkflow-from-another-python-application) for each frame of your video and saves the resulting data in a JSON file.

**Comment by rauar** [comment]
I patched locally the logic as well due to similar needs.

I think the right approach would be to have a flag per prediction result. Something like this:

./flow --outputJSON ...
./flow --outputImage ...
./flow --outputImage --outputJSON ...
./flow --outputImage --outputJSON --outputSomethingElseInTheFuture ...

Each option does not impact the other so you can have e.g. json results and image results at the same time.

**Comment by kumarvvin** [comment]
# @rauar is is possible to share the logic to output json from Video file? it would help.

**Comment by Midhun-Angathil** [comment]
I didn't get it exactly like how you would for an image. However, I was able to write the prediction related info (label, confidence and coordinates) to a text file. 

**Edit the predict.py file (file path:  /content/darkflow/darkflow/net/yolov2/predict.py) and add the _custom code_ mentioned below:**

`   
    import numpy as np
    import math
    import cv2
    import os
    import json
    #from scipy.special import expit
    #from utils.box import BoundBox, box_iou, prob_compare
    #from utils.box import prob_compare2, box_intersection
    from ...utils.box import BoundBox
    from ...cython_utils.cy_yolo2_findboxes import box_constructor

   def expit(x):
            return 1. / (1. + np.exp(-x))

   def _softmax(x):
        e_x = np.exp(x - np.max(x))
        out = e_x / e_x.sum()
        return out

    def findboxes(self, net_out):
            # meta
            meta = self.meta
            boxes = list()
            boxes=box_constructor(meta,net_out)
            return boxes

    def postprocess(self, net_out, im, save = True):
            """
            Takes net output, draw net_out, save to disk
            """
            boxes = self.findboxes(net_out)

            # meta
            meta = self.meta
            threshold = meta['thresh']
            colors = meta['colors']
            labels = meta['labels']
            if type(im) is not np.ndarray:
                    imgcv = cv2.imread(im)
            else: imgcv = im
            h, w, _ = imgcv.shape
        
            resultsForJSON = []
            for b in boxes:
                    boxResults = self.process_box(b, h, w, threshold)
                    if boxResults is None:
                            continue
                    left, right, top, bot, mess, max_indx, confidence = boxResults                

                    thick = int((h + w) // 300)
                    if self.FLAGS.json:
                            resultsForJSON.append({"label": mess, "confidence": float('%.2f' % confidence), "topleft": {"x": left, "y": top}, 
    "bottomright": {"x": right, "y": bot}})


 
 
 
 #========================================================================================================================================================================================

    #Custom code:

                ### Added by me to store prediction related info

                #Store prediction info in a list and append it per video frame
                Pred = [left, right, top, bot, mess, max_indx, confidence]
                Pred_append = []
                Pred_append.append(Pred) 

                #Store the prediction info for each video frame in a text file
                with open('Prediction.txt', 'a') as f:
                  for item in Pred_append:
                    f.write("%s\n" % item)

 
 
 
 #========================================================================================================================================================================================


                cv2.rectangle(imgcv,
                        (left, top), (right, bot),
                        colors[max_indx], thick)
                cv2.putText(imgcv, mess, (left, top - 12),
                        0, 1e-3 * h, colors[max_indx],thick//3)

        if not save: return imgcv

        outfolder = os.path.join(self.FLAGS.imgdir, 'out')
        img_name = os.path.join(outfolder, os.path.basename(im))
        if self.FLAGS.json:
                textJSON = json.dumps(resultsForJSON)
                textFile = os.path.splitext(img_name)[0] + ".json"
                with open(textFile, 'w') as f:
                        f.write(textJSON)
                return

        cv2.imwrite(img_name, imgcv)`

**After this, run this command (If you are using colab):**

`!./flow --model cfg/yolo.cfg --load bin/yolov2.weights --demo <your_video.mp4> --gpu 1 --saveVideo`

You will then find a text file called "Prediction.txt" in your darkflow directory which has label, confidence and coordinates of all the predicted bounding boxes throughout the video. 

Hope this helps!
