### ISSUE TITLE
Summary Folder

### ISSUE THREAD

**Issue by sharma-ji** [thtrieu/darkflow#508]
There is summary folder, what is it for?

Also I have another question: I just want to run tiny-yolo-voc.cfg along with pretrained tiny-yolo-voc.weights, what is the straight forward command?

Actually it is taking a hell lot of time om my 4gb RAM Laptop..

**Comment by abagshaw** [comment]
The `summary` folder is where [TensorBoard](https://www.tensorflow.org/get_started/summaries_and_tensorboard) logs are stored. As of https://github.com/thtrieu/darkflow/pull/518, however, TensorBoard logs are disabled by default.

To get started with inference using one of the provided models with weights, please refer to [this](https://github.com/thtrieu/darkflow#flowing-the-graph-using-flow) part of the readme.

In terms of speed, the amount of RAM you have will most likely not impact the speed of inference. Running inference on a GPU will provide a considerable performance boost compared to CPU speeds.
