### ISSUE TITLE
Minimum Requirements

### ISSUE THREAD

**Issue by sharma-ji** [thtrieu/darkflow#509]
What are the minimum system requirements to run Yolo?

A Tedx video show that it can be run on mobiles as well buton my pc (4gb Ram, i3) its only 0.27fps

**Comment by abagshaw** [comment]
There are no specific "minimum system requirements". But if you can get any inference working clearly you have met the bare minimum requirements. You might want to refer to [this](https://www.quora.com/Which-hardware-components-CPU-RAM-GC-etc-are-needed-for-a-machine-learning-deep-learning-home-PC-computer-to-run-fast) question regarding recommended system specs for ML tasks.

I'm assuming you are referring to [this](https://www.ted.com/talks/joseph_redmon_how_a_computer_learns_to_recognize_objects_instantly) TED talk by Joseph Redmon about [Darknet](https://github.com/pjreddie/darknet). Firstly, darkflow is not exactly the same as Darknet (it ports necessary features to use YOLO models with TensorFlow). Secondly his demo running YOLO on mobile is using a special optimized version of the network that isn't open source (see [xnor.ai](https://xnor.ai/)). Don't expect that kind of performance with an unoptimized model running on the CPU.

For realtime inference with darkflow you're doing to need a decent GPU.
