### ISSUE TITLE
question about the implemenetation of darkflow

### ISSUE THREAD

**Issue by xslittlegrass** [thtrieu/darkflow#52]
I'm trying to learn darknet and this project is fantastic! Thanks for sharing it.
I have a few questions about the implementation details for the darkflow.
1. What are the design considerations for the classes `net.build.TFNet` and `dark.darknet.Darknet`? It seems to me that `dark.darknet.Darknet` is used to hold the structure and data from cfg and weights files, and `net.build.TFNet` builds the tensorflow network from dark.darknet.Darknet. Is this understanding correct?
2. Are the `net.yolo` and `net.yolov2` classes share the same operators and preprocessing processes? What are the differences between the two versions of tiny-yolo (`darkflow/cfg/tiny-yolo.cfg` VS `darkflow/cfg/v1/tiny-yolo.cfg`) in terms of the network structure and implementation in darkflow?

Thanks.

**Comment by thtrieu** [comment]
1. That's correct, it's a two-stage process: load cfg & weights, and then build tensorflow graph
2. That's correct too, they are sharing **some** of the procedures (image pre-processing, etc). The difference is that `cfg/` is YOLO version 2, while `cfg/v1/` is YOLO version 1. You can found out more by reading the papers. 

`Darkflow` is not a YOLO implementation, it is an implementation of darknet. YOLO is decoupled completely into `net/yolo/`.

**Comment by xslittlegrass** [comment]
What do you mean by "decouple"? YOLO still uses the `dark.darknet.Darknet` and `net.build.TFNet` to construct the network, right?

I guess I'm confused about the how the process works. For instance, when I run the command `./flow --model cfg/v1/yolo-tiny.cfg --load bin/yolo-tiny.weights`, what are the procedures that happen in a general picture? It seems to me that there are these steps:

1. Load cfg & weights to `dark.darknet.Darknet`
2. Build tensorflow network using `net.build.TFNet`
3. Feed the images to the tensorflow network and get the output vector.
4. Generate the boxes and labels from the output vector.

Are these correct? Thanks.

**Comment by thtrieu** [comment]
`darknet` is a framework that builds feed-forward nets from `.cfg` and `.weights` file. So does `darkflow`. Feed-forward nets can be specialized into many things, YOLOv1, YOLOv2, lenet, alexnet, etc. They are specialized by defining the pre-process, post-process, loss building, etc. For YOLO, these functions are all grouped into `net/yolo` - what I mean by decoupled.

The steps are correct.
