### ISSUE TITLE
How to remove all the files and footprints of darkflow

### ISSUE THREAD

**Issue by onurbarut** [thtrieu/darkflow#521]
Hi,

I am facing the issue #512 and can't get rid of it. I installed darkflow in other location, but it uses the libraries in the previous location even though I run the terminal in the new location. So re-setuping didn't work.

I want to remove all the files and changes that darkflow does, and make a fresh installation. Can anybody help?

**Comment by abagshaw** [comment]
Have you tried `pip uninstall darkflow`

**Comment by onurbarut** [comment]
yes I did, no work. But I solved #512

**Comment by abagshaw** [comment]
If for some reason `pip uninstall darkflow` doesn't remove all installed files, can you try manually navigating to the path where pip installs packages to and see if there are any files that appear to be associated with darkflow that you can remove manually?

**Comment by onurbarut** [comment]
Hi,

Since we need and use python3, shouldn't we type `pip3 `instead of `pip`?

**Comment by abagshaw** [comment]
@onurbarut That depends if you have both python2 and python3 installed. If you only have python3 installed `pip` is just an alias for `pip3`. See a more detailed explanation [here](https://stackoverflow.com/questions/40832533/pip-or-pip3-to-install-packages-for-python-3).
