### ISSUE TITLE
Should I use the .weights file for a new own train?

### ISSUE THREAD

**Issue by ambr89** [thtrieu/darkflow#522]
I don't understand if when I want create new network from my own dataset, I have to use 
` --load bin/tiny-yolo-downloaded.weights`
or not in command line.
Anyone have an idea?
And if yes, why?

**Comment by abagshaw** [comment]
I'm not entirely sure what your question is. If you're wondering what the purpose is of loading weights in when training - this isn't necessary, but significantly decreases training time as you essentially have a head start in training the lower layers rather than having all weights initialized with random values (from my understanding).

**Comment by ambr89** [comment]
So, you said that 

./flow --model cfg/tiny-yolo-my.cfg --load bin/tiny-yolo-voc.weights --train --dataset "./ImageFolder" --annotation "./AnnotationFolder" --labels labels_my.txt --gpu 0.8 --trainer adam 

is same at

./flow --model cfg/tiny-yolo-my.cfg  --train --dataset "./ImageFolder" --annotation "./AnnotationFolder" --labels labels_brav.txt --gpu 0.8 --trainer adam 

the second will take more time, right?

**Comment by abagshaw** [comment]
Well they aren't the _same_ technically. Both should work, but the second one should initialize the weights with random values (from my understanding) whereas the first would initialize the common layers between `tiny-yolo.my.cfg` and `tiny-yolo-voc.cfg` with the existing weights from `tiny-yolo-voc.weights` and initialize the remaining layers with random weights.

You should see your model converge much faster when using the first command and initializing earlier weights with pre-set values.

**Comment by ambr89** [comment]
yes, probably you're right!

In my case, I try both case and both converge, but the first work very well, the second is terrible!
Probably for the second, I need more data, I don't know.

**Comment by abagshaw** [comment]
@ambr89 Glad it's working. I'm going to close this for now.
