### ISSUE TITLE
Can't see the boxes with even sample images and the original weight file.

### ISSUE THREAD

**Issue by openedhardware** [thtrieu/darkflow#523]
I just cloned this repo downloaded the tiny-yolo weight file with `wget https://pjreddie.com/media/files/tiny-yolo-voc.weights` command.

After installing, I tried this:

    flow --imgdir sample_img/ --model cfg/tiny-yolo-voc.cfg --load tiny-yolo-voc.weights --json --threshold .1

But sadly there is no JSON output at all!
![image](https://user-images.githubusercontent.com/16890683/34812988-1a3d9b80-f6e3-11e7-8a3a-e9dbce00faf7.png)

Please help me!

Thanks.

**Comment by abagshaw** [comment]
As written [here](https://github.com/thtrieu/darkflow#flowing-the-graph-using-flow)

> JSON output can be generated with descriptions of the pixel location of each bounding box and the pixel location. Each prediction is stored in the sample_img/out folder by default.

Have you checked the `sample_img/out` folder to see if the predictions are showing up there?

**Comment by openedhardware** [comment]
Yeah, @abagshaw 
All json files have a blank list.
![image](https://user-images.githubusercontent.com/16890683/34844119-63e585dc-f74b-11e7-8833-36053bc109ae.png)

Cheers.

**Comment by ginger0106** [comment]
I have the same problem, so have you solve that?

**Comment by ssusie** [comment]
Have you fixed this problem?

**Comment by buckyball99** [comment]
Running into the same exact problem.

**Comment by pranit-vyas** [comment]
Running into the same problem, it was working back in April, I downloaded the repo again and now its not working
