### ISSUE TITLE
How to convert darknet model to tensorflow model

### ISSUE THREAD

**Issue by ysh329** [thtrieu/darkflow#527]
Excuse me, I wanna ask how to convert darknet yolov2 model to tensorflow format. Of course, I read readme but found how to train using darknet config file. I only want to convert darkent model (cfg and its params) to tensorflow's format. 

Thanks in advance🙇

**Comment by abagshaw** [comment]
@ysh329 To convert the darknet `.weights` and `.cfg` to a TensorFlow `.pb` (along with some darkflow metadata contained in `.meta`) try the instructions detailed [here](https://github.com/thtrieu/darkflow#save-the-built-graph-to-a-protobuf-file-pb), specifically the second line pertaining to _Saving graph and weights to protobuf file._

Your command should look something like this:

```
flow --model cfg/yolo.cfg --load bin/yolo.weights --savepb
```

**Comment by ysh329** [comment]
@abagshaw Thanks a lot, my big brother 👍 I'll have a try right now~

**Comment by vvkv** [comment]
Thank you for that response @abagshaw and thanks for asking @ysh329 . Where in the darkflow directory is the .pb file saved after this command is run ? Thanks

**Comment by maxadda** [comment]
Thank you very much for your contribution，I  use your code to normally generate yolov2 network files and models,But in the test, the first layer of batchnorm output Nan. Do you have a test?

**Comment by keides2** [comment]
Hi,

I have AssertionErrors below:

$./flow --model cfg/yolov2-voc.cfg --load backup/yolov2-voc_34000.weights --savepb
AssertionError: labels.txt and cfg/yolov2-voc.cfg indicate inconsistent class numbers

$./flow --model cfg/yolov2-tiny-voc.cfg --load bin/yolov2-tiny-voc_10000.weights --savepb
AssertionError: Over-read bin/yolov2-tiny-voc_10000.weights

Can darkflow convert yolov 2-voc or yolov2-tiny-voc weights to pb?

Thank you,

**Comment by prateethvnayak** [comment]
This cannot convert yolov3 model to Tensorflow
Issue is still open

**Comment by zrobotparking** [comment]
this issue is for yolov3 support  [#884](https://github.com/thtrieu/darkflow/issues/884)

**Comment by sjain-stanford** [comment]
@prateethvnayak @zrobotparking For coverting yolo-v3 to TensorFlow, give this a try:
https://github.com/jinyu121/DW2TF

**Comment by woaiios** [comment]
> @prateethvnayak @zrobotparking For coverting yolo-v3 to TensorFlow, give this a try:
> https://github.com/jinyu121/DW2TF

Below link also work:
https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/darknet/README.md

**Comment by erkin98** [comment]
is there any issue for yolov4?
