### ISSUE TITLE
how to run darkflow in server via php code ?

### ISSUE THREAD

**Issue by trim-inc000** [thtrieu/darkflow#528]
this repro is amazing and very useful to me. I can execute manually a script that includes `from darkflow.net.build import TFNet`. 
But when i put the script on server and try to run by calling `shell_exec("python3 test.py"`, it not work. This is kind of final step of my work. Im sure that this issue because of importing `from darkflow.net.build import TFNet`.  Any suggestion will be appreciated. Thanks in advance!

**Comment by macro-dadt** [comment]
make sure that you install darkflow globally.

**Comment by trim-inc000** [comment]
@macro-dadt yes! you right, thank you very much

**Comment by Wanderish** [comment]
Hey @macro-dadt  
I'm trying to run the same script on django. I'm getting 
Assertion Error: bin/yolo.weights not found
I did install darkflow globally. Any ideas how to overcome this?
