### ISSUE TITLE
Are weights transferable to darknet?

### ISSUE THREAD

**Issue by kieferselmon** [thtrieu/darkflow#548]
Is there a way to use weights trained using darkflow on the original darknet framework?

**Comment by abagshaw** [comment]
Unfortunately not at the moment.

**Comment by pbabbicola** [comment]
Check #198 which explains how to do it. If you can code it you could send a PR.

**Comment by abagshaw** [comment]
Closing as duplicate of https://github.com/thtrieu/darkflow/issues/198
