### ISSUE TITLE
how to create checkpoints file?

### ISSUE THREAD

**Issue by harshiddhmania** [thtrieu/darkflow#550]
Hi, 
I am beginner, and i want to convert the darkflow weights into the Tensorflow .pb file. And while running below command, i am getting error message.
"flow --model cfg/yolo.cfg --load -1 --savepb"

NOTE: I am using pre-trained model.

Error logs :
Traceback (most recent call last):
  File "/usr/local/bin/flow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/media/sf_DL_ML/darkflow/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/media/sf_DL_ML/darkflow/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/media/sf_DL_ML/darkflow/darkflow/net/build.py", line 76, in __init__
    self.setup_meta_ops()
  File "/media/sf_DL_ML/darkflow/darkflow/net/build.py", line 151, in setup_meta_ops
    if self.FLAGS.load != 0: self.load_from_ckpt()
  File "/media/sf_DL_ML/darkflow/darkflow/net/help.py", line 23, in load_from_ckpt
    with open(os.path.join(self.FLAGS.backup, 'checkpoint'), 'r') as f:
IOError: [Errno 2] No such file or directory: '**ckpt/checkpoint**'

So please help me in creating checkpoint to create .pb file.

Thanks!

**Comment by abagshaw** [comment]
@harshiddhmania checkpoints are created during training. You haven't done any training so you won't have any checkpoints to use. You are trying to convert a pre-trained model to a `.pb` so you should use the second command listed [here](https://github.com/thtrieu/darkflow#save-the-built-graph-to-a-protobuf-file-pb) to load the weights from a `.weights` file:

```
flow --model cfg/yolo.cfg --load bin/yolo.weights --savepb
```

**Comment by harshiddhmania** [comment]
@abagshaw Thanks for help. Second commands works. 

I have one more question, Once the .pb file gets generated, how would i verify the tensorflow model?
