### ISSUE TITLE
Change color of bounding box

### ISSUE THREAD

**Issue by debiff** [thtrieu/darkflow#566]
Hi, 
in which file I can set the color for the bounding box of the classes ?
Thank you

**Comment by raulincze** [comment]
Hello,

Here's where the color assignment takes place:
https://github.com/thtrieu/darkflow/blob/master/darkflow/net/yolo/__init__.py#L27

You can also modify the colors in the .meta file of a saved graph.

**Comment by debiff** [comment]
@raulincze Thank's, very helpfull.
Regards

**Comment by koutini** [comment]
Hello ,
can i change color of detection box in yolo darknet ??

**Comment by Ali3220** [comment]
how to hide object name when this object is detecting on video and I also wonder how to change bounding box color and size darknet yolov. not darkflow
