### ISSUE TITLE
Using darkflow from another python application to save image with predictions and bounding boxes

### ISSUE THREAD

**Issue by Khobzer** [thtrieu/darkflow#571]
Is there anyway to save the image with the predictions and their bounding boxes after printing the result ?

from darkflow.net.build import TFNet
import cv2

options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1}

tfnet = TFNet(options)

imgcv = cv2.imread("./sample_img/sample_dog.jpg")
result = tfnet.return_predict(imgcv)
print(result)

**Comment by SkullPirateTK** [comment]
You will have to write your own function to draw the boxes and write the image after parsing the json output.

**Comment by Adnation** [comment]
You can use code like this

```
cv2.rectangle(imgcv,
              (result["topleft"]["x"], result["topleft"]["y"]),
              (result["bottomright"]["x"],
               result["bottomright"]["y"]),
              (0, 255, 0), 4)
text_x, text_y = result["topleft"][
    "x"] - 10, result["topleft"]["y"] - 10

cv2.putText(imgcv, result["label"], (text_x, text_y),
            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2, cv2.LINE_AA)
```


Where result in single element from list of results returned by return predict method and imgcv is the original image

**Comment by Khobzer** [comment]
Thank you !

**Comment by idhamhalim** [comment]
First of all sorry, I know the issue is closed, but when i tried to run the code by @Adnation , it gives me an error` TypeError: list indices must be integers or slices, not str`

**Comment by zanny0713** [comment]
@Khobzer what is this line of code doing
" result = tfnet.return_predict(imgcv)"

**Comment by abhishek795jha** [comment]
> Is there anyway to save the image with the predictions and their bounding boxes after printing the result ?
> 
> from darkflow.net.build import TFNet
> import cv2
> 
> options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1}
> 
> tfnet = TFNet(options)
> 
> imgcv = cv2.imread("./sample_img/sample_dog.jpg")
> result = tfnet.return_predict(imgcv)
> print(result)

I am having an issue while executing this code. Can you please tell me about "load" parameter.

**Comment by ankitAMD** [comment]
> > Is there anyway to save the image with the predictions and their bounding boxes after printing the result ?
> > from darkflow.net.build import TFNet
> > import cv2
> > options = {"model": "cfg/yolo.cfg", "load": "bin/yolo.weights", "threshold": 0.1}
> > tfnet = TFNet(options)
> > imgcv = cv2.imread("./sample_img/sample_dog.jpg")
> > result = tfnet.return_predict(imgcv)
> > print(result)
> 
> I am having an issue while executing this code. Can you please tell me about "load" parameter.

@abhishek795jha  "load" parameter is  your weight files .......initial we take yolo weight file  after training you create .pb file for testing as a weight file . In training time you have to use comand "--savepb" to save .pb file using with flow command .
