### ISSUE TITLE
Error: Annotation directory not found ../pascal/VOCdevkit/ANN/

### ISSUE THREAD

**Issue by datamonday** [thtrieu/darkflow#578]
when I train ：python ./flow --model cfg/yolo-voc.2.0.cfg --load bin/yolo-voc_18000.weights --train --gpu 0
I get this error：Error: Annotation directory not found ../pascal/VOCdevkit/ANN/ 
what should I do？

**Comment by Peddz24** [comment]
You should give the path to your annotation and dataset directory with --dataset and --annotation. Right now it is looking in the default location ../paccal/VOCdevkit/ANN/

**Comment by datamonday** [comment]
@Ｐｅｄｄｚ24　yeah!
