### ISSUE TITLE
How to plot the loss from every batch?

### ISSUE THREAD

**Issue by davie890** [thtrieu/darkflow#580]
In what file and where does the loss data get sent out to the cmd prompt, I would like to store these values and use it to plot a graph, but I am unsure of where this action occurs.

**Comment by kribby** [comment]
@davie890 Did you manage to solve this issue? If so could you share the solution?

Thanks 

K

**Comment by davie890** [comment]
@kribby It gets printed in the flow.py from darkflow/net folder. More specifically in the train function. The loss and the loss_mva contains the data that gets printed to the screen. I put those two data into a list as a tuple pair, then exported that list into another file which I graphed separately. The data only saved into the list when the training completed 100% if you ctrl+c to stop the training early the data won't be saved.

**Comment by senisna** [comment]
@kribby  could please share the code
