### ISSUE TITLE
Where is the output stored?

### ISSUE THREAD

**Issue by RohitSiga95** [thtrieu/darkflow#591]
when running the demo file through command prompt in win10, it is compiling and running and showing ~2 FPS. But i am unable to locate the location where the output is stored. Pls help

**Comment by idhamhalim** [comment]
have you used the --saveVideo option, if yes, i think it saved at video.avi at the root of darkflow folder

**Comment by abagshaw** [comment]
@RohitSiga95 has your issue been resolved?

**Comment by RohitSiga95** [comment]
Got it. Thanks.
