### ISSUE TITLE
is it possible to output frames with only object that have bounding boxes?

### ISSUE THREAD

**Issue by idhamhalim** [thtrieu/darkflow#595]
i have setup the darkflow. The demo runs well. However, if i run with the `--saveVideo` option, the output will be a video file with avi format. Is it possible to only output frames that the bounding box is present, instead of the full video.

**Comment by abagshaw** [comment]
@idhamhalim This is currently not supported. I think the best way to achieve this would be to write your own wrapper script that loads the video and passes each frame to [`return_predict()`](https://github.com/thtrieu/darkflow#using-darkflow-from-another-python-application). Then you can deal with the output however you wish (in your case selectively saving frames to the output video based on the presence of a detection).
