### ISSUE TITLE
input from http/rtsp

### ISSUE THREAD

**Issue by PradiptaPN** [thtrieu/darkflow#602]
hi, first of all thank you for the project.

is there any way to run darkflow when the input is http/rtsp/url? 
i tried using command like

flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --demo http://10.5.30.240:8080/shot.jpg

but got assertion error, file not exist. i've also read similar topic in pull request but still not working.

**Comment by abagshaw** [comment]
This functionality is not currently supported as darkflow currently expects a local video file (for use with `--demo`). Please stay tuned to https://github.com/thtrieu/darkflow/pull/511 as this functionality may soon be added.
