### ISSUE TITLE
Show training results in tensorboard

### ISSUE THREAD

**Issue by Peddz24** [thtrieu/darkflow#603]
Is there a way to show the training loss, for example, in tensorboard during training with darkflow? This gives very nice graphs I can use as research. To show it in tensorboard you need event files that generate during training.

**Comment by Peddz24** [comment]
I have found it. It is a option in the commands. --summary

**Comment by senisna** [comment]
sir could please give some details on how you managed to do it and where do i finde the event fles

**Comment by mpky** [comment]
> I have found it. It is a option in the commands. --summary

What does this --summary produce? Is it just a log file that TensorBoard can read?

**Comment by senisna** [comment]
@mpky yes that's it
it's called the TF event file 
but u need to specify the folder name (it shouldn't be an existing one) so it is --summary folder name
