### ISSUE TITLE
I have all annotations in ".mat" file....How to Convert those annotations into Darkflow format? 

### ISSUE THREAD

**Issue by SrikanthVelpuri** [thtrieu/darkflow#606]
Hii guys...
I downloaded standford cars dataset(standard dataset) which has all the images and annotations.
The only problem is that all the annotations are in ".mat" format(Matlab File)
Please give me some guidance about how to convert these annotations into darkflow xml format.
I opened the .mat file in matlab.
I will upload the screen shot of how the bounding boxes are present.
Please help me convert these annotation file into darkflow annotations format.
![screenshot 7](https://user-images.githubusercontent.com/19996897/36931774-433460c8-1ee3-11e8-856e-32adb5366fa3.png)

I copied all those columns into excel and tried to convert them into darflow format..But still finding it difficult.

![screenshot 8](https://user-images.githubusercontent.com/19996897/36931796-bd90823e-1ee3-11e8-981a-fe0e0e844809.png)

If you find solution about converting these annotations into darkflow format...please help...
Thanks in advance...

**Comment by rucsacman** [comment]
For annotation you need .xml file you want create xml file for each image

**Comment by SrikanthVelpuri** [comment]
@rucsacman I know that I have to convert those annotations into xml file...Since many standard datasets have .mat file annotations...and many of them dont know the code for converting it into xml file.Writing the process or suggesting the software which do this would be helpful.

**Comment by rucsacman** [comment]
Yes using python you can write a script read .csv file you can create xml file

**Comment by SrikanthVelpuri** [comment]
If you have the code please post it...Im finding it difficult to solve this issue @rucsacman

**Comment by apuayush** [comment]
@SrikanthVelpuri did you found any way to convert .mat files to .xml

**Comment by jatinmandav** [comment]
Here is a Python script to create Annotations in XML Format for Darkflow. Let me know if you are stuck somewhere!
[createAnnotations-XMLFormat.py](https://github.com/jatinmandav/darkflow/blob/master/createAnnotations-XMLFormat.py)

**Comment by SrikanthVelpuri** [comment]
I will try that code and let you know about that...

**Comment by SrikanthVelpuri** [comment]
Code is working fine....Close this issue..And thanks for solving my problem @jatinmandav

**Comment by SrikanthVelpuri** [comment]
@apuayush First copy all the columns into excel file and save it as a csv file.Now load the csv file in python and modify the code provided @jatinmandav..His code is working fine.

**Comment by lobbie** [comment]
Hi, 

Sorry to bump this thread.  I read in[ Darknet YOLO site](https://pjreddie.com/darknet/yolo/) that for training, YOLO requires the annotation files in text format and not XML format using the `voc_label.py` to convert.

> Where x, y, width, and height are relative to the image's width and height. To generate these file we will run the voc_label.py script in Darknet's scripts/ directory. 

Is this XML requirement specific to Darkflow?

Thanks,
Lobbie

**Comment by jatinmandav** [comment]
Hi Lobbie!
Yes, for Darkflow, annotations are required in XML format and for Dark-net its TXT file!

**Comment by srhtyldz** [comment]
Can someone please help to convert .mat file to .txt file ?

**Comment by jatinmandav** [comment]
Hi!
Here is the code: https://github.com/jatinmandav/darkflow/blob/master/generateXML_CSV.py

Let me know if the code has some bugs I will update the file
Thanks.

**Comment by giridhar13** [comment]
Thank you for uploading it.could u let me know how to pass the values to the function write_xml().

**Comment by jatinmandav** [comment]
I have mentioned everything in the comments on top of the file.

**Comment by giridhar13** [comment]
LISA traffic light ds has multiple annotations on the same image.ie the CSV file has multiple entries with the same filename field,when I modit your script only the first entry is saved.could you let me know how to modify this script for that

**Comment by srhtyldz** [comment]
@jatinmandav  Can you share for .mat to txt not xml ?

**Comment by mekong0404** [comment]
@jatinmandav hi, i was going through the thread saw the link for. Mat to. Xml conversion script link. But unfortunately the link is not working. Will you help me in this, atleast the link or something for the actual script u shared? I am stuck at this and i really need tour help. Thnx

**Comment by Gajurel-web** [comment]
> Code is working fine....Close this issue..And thanks for solving my problem @jatinmandav

I have also same issues. i really need your help. 
As you say First copy all the columns into excel file and save it as a csv file...So which tools can i use to open the .mat file and copy the related column?
