### ISSUE TITLE
How if running this program using ipwebcam camera

### ISSUE THREAD

**Issue by mursyidinadnan** [thtrieu/darkflow#616]
Any one kno, how if i try to running this program using camera webcam and the camera changin using third part of camera like ipwebcam maybe?
Please if you have answer. Thankyou

**Comment by troydeng** [comment]
There is a simple but crude way, check the darkflow/net/help.py file, modify the camera function as below:  
```
def camera(self):
    file = self.FLAGS.demo
    SaveVideo = self.FLAGS.saveVideo

    if file == 'camera':
        file = 0
    else:
        assert os.path.isfile(file), \
            'file {} does not exist'.format(file)

    # modified by me#############################
    # camera = cv2.VideoCapture(file)
    # source is your ipwebcam source, e.g. this is `mine`
    source = 'rtsp://admin:bitadhoc12345678@195.0.4.11//Streaming/Channels/1'
    camera = cv2.VideoCapture(source)
    # ##########################################

    if file == 0:
        self.say('Press [ESC] to quit demo')
    ```

**Comment by mursyidinadnan** [comment]
@troydeng it works thaks and this my modified code.
``def camera(self):
    file = self.FLAGS.demo
    SaveVideo = self.FLAGS.saveVideo
    
    if file == 'camera':
        file = 0
    else:
        assert os.path.isfile(file), \
        'file {} does not exist'.format(file)
        
    #camera = cv2.VideoCapture(file)
    source = 'http://192.168.43.1:8080/video?dummy=param.mjpg'
    camera = cv2.VideoCapture(source)
    
    if file == 0:
        self.say('Press [ESC] to quit demo')

**Comment by mursyidinadnan** [comment]
@troydeng its works thankyou so much and this is my code
`def camera(self):
    file = self.FLAGS.demo
    SaveVideo = self.FLAGS.saveVideo
    
    if file == 'camera':
        file = 0
    else:
        assert os.path.isfile(file), \
        'file {} does not exist'.format(file)
        
    #camera = cv2.VideoCapture(file)
    source = 'http://192.168.43.1:8080/video?dummy=param.mjpg'
    camera = cv2.VideoCapture(source)
    
    if file == 0:
        self.say('Press [ESC] to quit demo')`
