### ISSUE TITLE
Import issue of tensorflow even it is installed

### ISSUE THREAD

**Issue by amit2rockon** [thtrieu/darkflow#626]
```
./flow
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/Users/xyz/Downloads/darkflow-master/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/Users/xyz/Downloads/darkflow-master/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow


```

even i have already pip installed tensorflow.

**Comment by idhamhalim** [comment]
I am also having the same error. I installed darkflow on Raspberry Pi 2 model B (have same problem as above). I have successfully set it on my Ubuntu laptop,though

**Comment by ssusie** [comment]
I fixed this by creating a new conda environment by cloning the "root" and installing darknet there. Make sure that python and tensorflow are installed in conda.
