### ISSUE TITLE
Change Bounding Box thickness

### ISSUE THREAD

**Issue by stch72** [thtrieu/darkflow#638]
Hello :)
I am using darkflow with the Basic tiny yolo weights and let it flow over my avi test Video. This works fine but would like  to change the thickness of the bounding boxes. In case of small objects I couldnt even see the objects, because the box is that thick. So I want to change it to e.g. 1-2 pxl thickness.

Anyone got an idea? 

Thanks a lot !

**Comment by sabhiram** [comment]
https://github.com/thtrieu/darkflow/blob/60c785550f775a31f4f784aa07e4a1c7a81a0542/darkflow/net/yolov2/predict.py#L49

This line defines the thickness of a box as the `(h+w)/300` - you can adjust this here and special case smaller boxes as you see fit.

**Comment by stch72** [comment]
Great, thank you :) !!!!!
