### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by todayes** [thtrieu/darkflow#669]
can anyone tell me how to use tensorboard in darkflow? 
thanks

**Comment by sandeeprepakula** [comment]
Use the command line parameter --tensorboard DIR

This will create a log of events under the directory DIR. 
You can use the below terminal command to start tensorboard for viewing the events logged.
tensorboard --logdir DIR

Follow the IP and port given by above command to open tensorboard events in browser.

**Comment by ismaelfer** [comment]
Thanks!!
