### ISSUE TITLE
Error:running the demo without  output window

### ISSUE THREAD

**Issue by ChunPuXu** [thtrieu/darkflow#673]
Hi，
When I  process a video with darkflow，I use the command "flow --model cfg/yolo.cfg --load bin/yolo.weights --demo VID.mp4 --gpu 0.9”，there is nothing output.Why?

> (tensorflow) dell@dell:~/darkflow$ flow --model cfg/yolo.cfg --load bin/yolo.weights --demo VID.mp4 --gpu 0.9
> /home/dell/.conda/envs/tensorflow/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
>   return f(*args, **kwds)
> 
>  Parsing

> ./cfg/yolo.cfg
> Parsing cfg/yolo.cfg
> Loading bin/yolo.weights ...
> Successfully identified 203934260 bytes
> Finished in 0.007088899612426758s
> Model has a coco model name, loading coco labels.
> 
> Building net ...
> Source | Train? | Layer description                | Output size
> -------+--------+----------------------------------+---------------
>        |        | input                            | (?, 608, 608, 3)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 608, 608, 32)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 304, 304, 32)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 304, 304, 64)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 152, 152, 64)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 152, 152, 128)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 152, 152, 64)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 152, 152, 128)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 76, 76, 128)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 76, 76, 256)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 76, 76, 128)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 76, 76, 256)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 38, 38, 256)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 256)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 256)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 38, 38, 512)
>  Load  |  Yep!  | maxp 2x2p0_2                     | (?, 19, 19, 512)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 19, 19, 512)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 19, 19, 512)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | concat [16]                      | (?, 38, 38, 512)
>  Load  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 38, 38, 64)
>  Load  |  Yep!  | local flatten 2x2                | (?, 19, 19, 256)
>  Load  |  Yep!  | concat [27, 24]                  | (?, 19, 19, 1280)
>  Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 19, 19, 1024)
>  Load  |  Yep!  | conv 1x1p0_1    linear           | (?, 19, 19, 425)
> -------+--------+----------------------------------+---------------
> GPU mode with 0.9 usage
> 2018-03-27 16:13:40.244174: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2018-03-27 16:13:40.351892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-03-27 16:13:40.352171: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.835
> pciBusID: 0000:01:00.0
> totalMemory: 7.92GiB freeMemory: 7.55GiB
> 2018-03-27 16:13:40.352184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> Finished in 2.0977280139923096s
> 
> Press [ESC] to quit demo
> 24.337 FPS
> End of Video
> 
> Demo stopped, exit

When I use the command  "flow --model cfg/yolo.cfg --load bin/yolo.weights --demo VID.mp4 --gpu 0.9  --saveVideo",a video is stored and there is still no output window.
So  what's the problem?Thanks.

**Comment by linydf** [comment]
后面加一个--saveVideo

**Comment by ChunPuXu** [comment]
@linydf 请问，运行   flow --model cfg/yolo.cfg --load bin/yolo.weights --demo VID.mp4 --gpu 0.9，没有任何窗口显示处理过的视频是正常的？需要加--saveVideo，才能看到处理完有标记框的视频？

**Comment by linydf** [comment]
是的 没有显示窗口，处理完之后直接保存到本地

**Comment by ChunPuXu** [comment]
@linydf 好的，多谢解答

**Comment by melonetern** [comment]
@linydf  @ChunPuXu   请问上面的 --demo VID.mp4 是已经存在的吗，然后测试好以后就会有标记框，复制还是在原文件上带框。 如果不是，那是不是摄像头取画面保存为VID.mp4

**Comment by ChunPuXu** [comment]
@melonetern VID.mp4是我自己拍摄好的本地视频，我测试的时候（即没有--saveVideo），终端只会显示帧率，测试完成后，原视频还是不带框的。加了--saveVideo后，会产生带框的新视频，原视频还是不带框的

**Comment by Juankz** [comment]
I had this same problem. The culprit is this PR https://github.com/thtrieu/darkflow/pull/207 which modifies the file  `darkflow/net/help.py` to not create a window for the video processing. So I just reverted to how it was before and it worked
