### ISSUE TITLE
mAP accuracy

### ISSUE THREAD

**Issue by jwnsu** [thtrieu/darkflow#70]
Darkflow has made a lot of nice progress lately. Wondering whether we have mAP accuracy #s on Pascal VOC 2007/2012 dataset, both trained in darkflow or directly use trained model from C Yolov2. The accuracy and time performance will determine whether darkflow will be put in widespread use.

I did an informal test by taking 10 images and comparing side-by-side with Yolov2 using weights trained from Yolov2, it seems darkflow is about 15-20% less than yolov2: majority of objects are recognized within 3-4 percentage of confidence from C version, but also misses some objects that are recognized by C version.

**Comment by thtrieu** [comment]
JSON output is supported in the new commit. You can evaluate mAP or any other measures using this JSON output.

**Comment by junxuezheng** [comment]
@thtrieu 
hey,
fine-tuning net work.i train tiny-yolo-voc.cfg by loading tin-yolo-voc.weights ,training on voc2007+2012.（30epoch，batch 64),test on voc 2007.
 mAP is about 5-10% less than using tiny-yolo-weights. why the result became worse with fine-tuning。

thanks
