### ISSUE TITLE
ResourceExhaustedError when using YOLOv2 model

### ISSUE THREAD

**Issue by andikira** [thtrieu/darkflow#705]
Hello, I am a newbie in computer vision. 
I have a question about training yolov2 using GPU, i've tried training 3 images (for overfit) with GPU, i use tiny-yolov2-voc model and tiny-yolov2-voc pre-train weight, the training work well but when i try to training same image with yolov2 (model and weights) some error occur says 

ResourceExhaustedError (see above for trackback):  OOM when allocationg tensor of shape [3,3,32,64] and type float

i use Nvidia GTX 750 Ti 2GB, os windows 10, anaconda3 

i have tried --gpu 0.1 and --batch 1 but same error occur, is there no any chance to use < 4GB GPU for training yolov2 model ? or any suggestion for solve this ?

Thanks in advance

**Comment by SrikanthVelpuri** [comment]
I have 4GB graphic card of Nvidia 840m Ram 8 GB Processor i7....Now I got the same error...I read in the issues that nvidia 1080 can run when batch size is changed to 12 when yolo weights are used...Yolov2 architecture needs more graphic card memory...You can use tiny-yolo-voc weights for training...It might run on your GPU..check out those in readme of darkflow.

**Comment by andikira** [comment]
Thanks for your answer @SrikanthVelpuri.

 i expect to train YOLOv2 in 0.2 to 0.5 GPU memory allocation so it just use 1 - 2 GB (i have 2GB GPU memory) but i think the minimum GPU memory is 4GB no matter how much you allocate memory for training, am i right ?

**Comment by rij12** [comment]
@andikira Correct.YOLOv2 requires at least 4GB to be allocated to it, regardless of GPU percentage allocation. 
This is my opinion, but I would get a Nvidia GTX 1070 or better. If your students you can google cloud $300 free credit and get a Nivida K80  or a similar GPU.

**Comment by andikira** [comment]
Thank you for your answer and suggestion @rij12 i'll check google cloud then.
