### ISSUE TITLE
No data augmentation?

### ISSUE THREAD

**Issue by bareblackfoot** [thtrieu/darkflow#721]
I think this code doesn't have data augmentation part while the original darknet has an "extensive data augmentation" as written in their paper. 

Should I do it on my own?

**Comment by janchk** [comment]
```
def preprocess(self, im, allobj = None):
	"""
	Takes an image, return it as a numpy tensor that is readily
	to be fed into tfnet. If there is an accompanied annotation (allobj),
	meaning this preprocessing is serving the train process, then this
	image will be transformed with random noise to augment training data,
	using scale, translation, flipping and recolor. The accompanied
	parsed annotation (allobj) will also be modified accordingly.
	"""
```
darkflow/net/yolo/predict.py line 49.
What do you think it mean?

**Comment by bareblackfoot** [comment]
@janchk Ok, thanks.

**Comment by bareblackfoot** [comment]
@janchk Ok, thanks.

**Comment by kmsravindra** [comment]
@janchk, This data augmentation code doesn't seem to appear in yolov2 folder? Could you throw some light on that?

**Comment by h-ann** [comment]
@kmsravindra, I was also interested in this question, and actually this data augmentation is present in yolov2. The function (preprocess()) is just imported from yolo folder and called in _batch() function in darkflow/darkflow/net/yolov2/data.py line 27.
