### ISSUE TITLE
Cloud service recommendation

### ISSUE THREAD

**Issue by off99555** [thtrieu/darkflow#736]
Which cloud service do you use for training `darkflow` models?
Or do you usually use your own GPU?
Any link suggested?

**Comment by bduman** [comment]
If you need GPU for training, search "google colab" that provide free gpu for 12 hours otherwise you can try google cloud compute engine.

**Comment by off99555** [comment]
But it doesn't seem like it allows installing `darkflow`. It only allows Jupyter Notebook, isn't it?

**Comment by bduman** [comment]
No, you can use this jupyter as a terminal with using '!' head of command.

Like this:
`!git clone https://github.com/pjreddie/darknet`

**Comment by off99555** [comment]
Have you ever tried `darkflow` on it?

**Comment by bduman** [comment]
no but i installed cuda and darknet on it then train my model so it must be usable.
