### ISSUE TITLE
TypeError: is_inp() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by zhengyu920** [thtrieu/darkflow#74]
I download yolo2 weights and load into cfg/extraction.cfg got following error:

Traceback (most recent call last):
  File "./flow", line 61, in <module>
    tfnet.predict()
  File "/Users/yuzheng/Desktop/darkflow-master/net/flow.py", line 71, in predict
    all_inp_ = [i for i in all_inp_ if self.framework.is_inp(i)]
  File "/Users/yuzheng/Desktop/darkflow-master/net/flow.py", line 71, in <listcomp>
    all_inp_ = [i for i in all_inp_ if self.framework.is_inp(i)]
TypeError: is_inp() takes 1 positional argument but 2 were given

This error prevents me from doing any test or training. Anyway to fix this?

Here is entire log:
----------------------------------------------------------------
darkflow-master yuzheng$ ./flow --model cfg/extraction.cfg --load bin/yolo.weights
Parsing ./cfg/yolo.cfg
Parsing cfg/extraction.cfg
Loading bin/yolo.weights ...
Successfully identified 269862452 bytes
Finished in 0.03182697296142578s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 224, 224, 3)
 Init  |  Yep!  | conv 7x7p3_2  +bnorm  leaky      | (?, 112, 112, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 56, 56, 64)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 56, 56, 192)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 28, 28, 192)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 28, 28, 128)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 256)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 28, 28, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 28, 28, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 14, 14, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 256)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 512)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 14, 14, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 14, 14, 1024)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 7, 7, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 7, 7, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 7, 7, 1024)
 Init  |  Yep!  | conv 1x1p0_1  +bnorm  leaky      | (?, 7, 7, 512)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 7, 7, 1024)
 Init  |  Yep!  | conv 1x1p0_1    leaky            | (?, 7, 7, 1000)
 Load  |  Yep!  | avgpool()                        | (?, 1000)
 Load  |  Yep!  | softmax()                        | (?, 1000)
-------+--------+----------------------------------+---------------
Running entirely on CPU
Finished in 3.9319369792938232s

Traceback (most recent call last):
  File "./flow", line 61, in <module>
    tfnet.predict()
  File "/Users/yuzheng/Desktop/darkflow-master/net/flow.py", line 71, in predict
    all_inp_ = [i for i in all_inp_ if self.framework.is_inp(i)]
  File "/Users/yuzheng/Desktop/darkflow-master/net/flow.py", line 71, in <listcomp>
    all_inp_ = [i for i in all_inp_ if self.framework.is_inp(i)]
TypeError: is_inp() takes 1 positional argument but 2 were given

**Comment by thtrieu** [comment]
You are using `extraction.cfg`, this repo does not deal with this config. If you insist on using it, please pull the new code.
