### ISSUE TITLE
Using custom model from Darknet

### ISSUE THREAD

**Issue by eweill** [thtrieu/darkflow#75]
I have previously trained a custom network using my data with Darknet and I am able to run inference there.  I would like to use my model with DarkFlow, however, I keep getting the following error: 

IOError: [Errno 2] No such file or directory: 'labels.txt'

It seems to load my .cfg and .weights file correctly; however, it is missing some labels.txt file.

Any pointers on what this label file should be and where it should be placed so that I can create my model for DarkFlow?

**Comment by thtrieu** [comment]
Just create a text file `labels.txt`, put it in the main directory. Each line is a label of your problem, like described in README.

**Comment by eweill** [comment]
Thanks, I realized that I was missing that as soon as I posted the issue.

One other question.  I successfully got detections on my image, however the label on them simply says `object`, but the label in my label file says `car`.  Is there a different place it is reading the label from to give it a label of `object`?

Thanks.

**Comment by thtrieu** [comment]
I guess you are doing single class detection (only cars) using YOLOv2? If that is the case, then it's one feature of the code, just my bad design. In `net/yolo2/test.py` line 70 and 71, replace these with `label = labels[max_indx]` then you'll have `cars` labels.

**Comment by eweill** [comment]
Awesome.  Works like a charm.

Thanks for your help.
