### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'split'

### ISSUE THREAD

**Issue by dragon28** [thtrieu/darkflow#76]
$ ./flow --test test/ --model cfg/v1/yolo-tiny.cfg --load bin/yolo-tiny.weights --demo camera 
/home/dragon/darkflow/dark/darknet.py:54: UserWarning: ./cfg/yolo-tiny.cfg not found, use cfg/v1/yolo-tiny.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg/v1/yolo-tiny.cfg
Loading bin/yolo-tiny.weights ...
Successfully identified 180357512 bytes
Finished in 0.004657268524169922s

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 448, 448, 3)
 Load  |  Yep!  | scale to (-1, 1)                 | (?, 448, 448, 3)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 448, 448, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 224, 224, 16)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 224, 224, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 112, 112, 32)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 112, 112, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 56, 56, 64)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 56, 56, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 28, 28, 128)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 28, 28, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 14, 14, 256)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 14, 14, 512)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 7, 7, 512)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 7, 7, 1024)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 7, 7, 1024)
 Load  |  Yep!  | conv 3x3p1_1    leaky            | (?, 7, 7, 1024)
 Load  |  Yep!  | flat                             | (?, 50176)
 Load  |  Yep!  | full 50176 x 256  linear         | (?, 256)
 Load  |  Yep!  | full 256 x 4096  leaky           | (?, 4096)
 Load  |  Yep!  | drop                             | (?, 4096)
 Load  |  Yep!  | full 4096 x 1470  linear         | (?, 1470)
-------+--------+----------------------------------+---------------
Running entirely on CPU
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Finished in 2.284639358520508s

Press [ESC] to quit demo
Traceback (most recent call last):
  File "./flow", line 50, in <module>
    tfnet.camera(FLAGS.demo)
  File "/home/dragon/darkflow/net/help.py", line 72, in camera
    processed = self.framework.postprocess(net_out, frame, False)
  File "/home/dragon/darkflow/net/yolo/test.py", line 130, in postprocess
    img_name = os.path.join(outfolder, im.split('/')[-1])
AttributeError: 'numpy.ndarray' object has no attribute 'split'

OS: Ubuntu 16.04.1 (64 Bits)
Tensorflow version 1.0.0
Python Version 3.5.2
pip 9.0.1 

Pip list:
appdirs (1.4.2)
apturl (0.5.2)
asgi-redis (1.0.0)
asgiref (1.0.0)
autobahn (0.17.1)
beautifulsoup4 (4.4.1)
bleach (1.5.0)
blinker (1.3)
Brlapi (0.6.4)
channels (1.0.3)
chardet (2.3.0)
checkbox-support (0.22)
command-not-found (0.3)
constantly (15.1.0)
cryptography (1.2.3)
daphne (1.0.2)
decorator (4.0.11)
defer (1.0.6)
Django (1.10.5)
entrypoints (0.2.2)
feedparser (5.1.3)
guacamole (0.9.2)
html5lib (0.9999999)
httplib2 (0.9.1)
idna (2.0)
incremental (16.10.1)
ipykernel (4.5.2)
ipython (5.2.2)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.9.5)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.1.0)
jupyter-core (4.2.1)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
mistune (0.7.3)
msgpack-python (0.4.8)
nbconvert (5.1.1)
nbformat (4.2.0)
nltk (3.2.2)
notebook (4.3.2)
numpy (1.12.0)
oauthlib (1.0.3)
onboard (1.2.0)
packaging (16.8)
padme (1.1.1)
pandas (0.19.2)
pandocfilters (1.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (9.0.1)
plainbox (0.25)
prompt-toolkit (1.0.13)
protobuf (3.2.0)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycups (1.9.73)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.1.10)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-systemd (231)
pytz (2016.10)
pyxdg (0.25)
pyzmq (16.0.2)
qtconsole (4.2.1)
redis (2.10.5)
reportlab (3.3.0)
requests (2.9.1)
scikit-learn (0.18.1)
scipy (0.18.1)
screen-resolution-extra (0.0.0)
sessioninstaller (0.0.0)
setuptools (34.3.0)
simplegeneric (0.8.1)
six (1.10.0)
system-service (0.3)
tensorflow (1.0.0)
terminado (0.6)
testpath (0.3)
tornado (4.4.2)
tqdm (4.11.2)
traitlets (4.3.1)
Twisted (16.6.0)
txaio (2.6.0)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
zope.interface (4.3.3)

**Comment by thtrieu** [comment]
Please look at https://github.com/thtrieu/darkflow/issues/71
