### ISSUE TITLE
How to generate .weight file from training 

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#77]
Hello 

Actually I train tiny-yolo with my own datasets, but i don't figure out how to generate the .weight file 

Thanks

**Comment by thtrieu** [comment]
Unless you are trying to do something with `darknet`, then there is no reason for a `.weights` file. In this repo, weights are saved using tensorflow checkpoints (see README). If you really want the `.weights`, I am sorry that the code does not support doing so, but you can certainly add that :)

**Comment by agjayant** [comment]
@kamelbouyacoub Did you find a way to generate the .weight file from training ?

**Comment by frankist** [comment]
This would be a cool feature as darknet could then be later used for inference. From what I read, darknet is much faster than tensorflow.

**Comment by manujnaman** [comment]
While training the weights files are created in the backups folder.

**Comment by frankist** [comment]
@manujnaman Not sure I understood your comment. I know we can use the ckpt files as continuation points for training and generate .pb files for tf. What I meant is to convert .ckpt files to .weights instead of .pb to use darknet directly.

**Comment by AKlent** [comment]
Any one has the answer?

**Comment by AndrejHatzi** [comment]
I woüld like to know too!!!!
