### ISSUE TITLE
ERROR : Microsoft Visual C++ 14.0 is required.

### ISSUE THREAD

**Issue by johhnry** [thtrieu/darkflow#788]
Hi guys,

I have a problem to get started with darkflow, I decided to install it with pip globally with `pip3 install .` and it says : 

`error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools`

But the link http://landinghub.visualstudio.com/visual-cpp-build-tools no longer works.
I checked other issues but I didn't found an answer.

Thanks

**Comment by ppchaigneau** [comment]
Have the same issue.
Did you find a link that works to it?
Thanks

**Comment by monupurohit** [comment]
Got the same issue..

darkflow>pip install .
................
 building 'darkflow.cython_utils.nms' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by monupurohit** [comment]
It worked !!
https://stackoverflow.com/questions/47253638/error-microsoft-visual-c-14-0-is-required-when-installing-python-package?rq=1 

Please download Visual C++ Build Tools 2015
Install the visualcppbuildtools_full from 1.


>>>>>>>>>>>
yolo\darkflow>pip install .
Processing c:\users\monpuroh\yolo\darkflow
Installing collected packages: darkflow
  Running setup.py install for darkflow ... done
Successfully installed darkflow-1.0.0

**Comment by johhnry** [comment]
@monupurohit Thanks for your answers.
Now I have another problem, it says : 

`error: [WinError 3] The specified path was not found : 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'`

and 

`Command ""c:\users\joseph henry\appdata\local\programs\python\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joseph Henry\\AppData\\Local\\Temp\\pip-req-build-vzqvjtaj\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record "C:\Users\Joseph Henry\AppData\Local\Temp\pip-record-elx9rmqr\install-record.txt" --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Joseph Henry\AppData\Local\Temp\pip-req-build-vzqvjtaj\`

Thanks again.

**Comment by rosenta** [comment]
install with complete CPP build from below link,

https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe

then it might work. I tried all solution but above one helped me.

after that, If it shows, error with exit status 1158 then do the below steps:

To fix the issue, do the next steps:

Add this to your PATH environment variables:

C:\Program Files (x86)\Windows Kits\10\bin\x64

Copy these files rc.exe & rcdll.dll from C:\Program Files (x86)\Windows Kits\8.1\bin\x86 to C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

**Comment by gcovillo** [comment]
For anyone still having this problem, download:
 https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15

During installation, it will ask you what you want to install with it. Check the first box on the left, something about build tools, then after this there will appear more check boxes on the right. Check all of them. If you just download vs without checking all these boxes, the sdk will not download with it and more errors will appear.
