### ISSUE TITLE
how using the .txt files instead of xml?

### ISSUE THREAD

**Issue by Jeongseop-Yun** [thtrieu/darkflow#789]
i was study by darknet, but now i try the darkflow.
in darknet, my custom image dataset have annotation file format is txt.
it is composed: "object-class" "x" "y" "width" "height"

so my question is 
how can i using this txt file?
if i can't this, how can i convert this file to the .xml files?

many thanks,

**Comment by Jeongseop-Yun** [comment]
i made the convert python code.
anyone need  this code, contact the jsyun@ispl.korea.ac.kr

**Comment by EinavNamer** [comment]
Hello,
I'll be happy to get the python-convertion code.
I'm sending you an email.
Cheers, Einav

**Comment by Jeongseop-Yun** [comment]
from lxml import etree
from PIL import Image
import csv

#### fw is txt file that composed train image file path
fw = open('/home/ispl/data/vandalism/train/train_augmentation.txt','r')

#### path of save xml file
save_path = '/home/ispl/data/vandalism/train/annotation/'

#### txt_folder is txt file root that using darknet rectbox
txt_folder = '/home/ispl/data/vandalism/'

def csvread(fn):
    with open(fn, 'r') as csvfile:
        list_arr = []
        reader = csv.reader(csvfile, delimiter=' ')

        for row in reader:
            list_arr.append(row)
    return list_arr

#### edit ypur label set
labels = ['brick','cutter,plier', 'drill', 'gun',
          'hammer', 'knife','powersaw','spanner','stick']

def convert_label(txt_file):
    if((txt_file[0]) == str(0)):
        label = 'brick'
    elif ((txt_file[0]) == str(1)):
        label = 'cutter,plier'
    elif ((txt_file[0]) == str(2)):
        label = 'drill'
    elif ((txt_file[0]) == str(3)):
        label = 'gun'
    elif ((txt_file[0]) == str(4)):
        label = 'hammer'
    elif ((txt_file[0]) == str(5)):
        label = 'knife'
    elif ((txt_file[0]) == str(6)):
        label = 'powersaw'
    elif ((txt_file[0]) == str(7)):
        label = 'spanner'
    elif ((txt_file[0]) == str(8)):
        label = 'stick'

    return label

### core code = convert the yolo txt file to the x_min,x_max...
def extract_coor(txt_file, img_width, img_height):
    x_rect_mid = float(txt_file[1])
    y_rect_mid = float(txt_file[2])
    width_rect = float(txt_file[3])
    height_rect = float(txt_file[4])

    x_min_rect = ((2 * x_rect_mid * img_width) - (width_rect * img_width)) / 2
    x_max_rect = ((2 * x_rect_mid * img_width) + (width_rect * img_width)) / 2
    y_min_rect = ((2 * y_rect_mid * img_height) - (height_rect * img_height)) / 2
    y_max_rect = ((2 * y_rect_mid * img_height) + (height_rect * img_height)) / 2

    return x_min_rect, x_max_rect, y_min_rect, y_max_rect


for line in fw:
    root = etree.Element("annotation")

    ###### try debug to check your path
    img_path = line[:-1]
    img_style = img_path.split('/')[7][5:-4]
    img_name = img_path.split('/')[7]
    img_style_txt_folder = '%s/%s/%s/%s'%(txt_folder, img_path.split('/')[5], img_style, img_name)

    img_txt_root = img_style_txt_folder[:-4]
    txt = ".txt"

    txt_path = img_txt_root + txt
    txt_file = csvread(txt_path)
    ######################################

    #### read the image  information
    img_size = Image.open(img_path).size

    img_width = img_size[0]
    img_height = img_size[1]
    img_depth = Image.open(img_path).layers
    ######################################

    folder = etree.Element("folder")
    folder.text = "%s"%(img_style)

    filename = etree.Element("filename")
    filename.text = "%s" % (img_name)

    path = etree.Element("path")
    path.text = "%s" % (img_path)

    source = etree.Element("source")
    ##################source - element##################
    source_database= etree.SubElement(source,"database")
    source_database.text = "Unknown"
    ####################################################

    size = etree.Element("size")
    ####################size - element##################
    image_width = etree.SubElement(size, "width")
    image_width.text = "%d"%(img_width)

    image_height = etree.SubElement(size, "height")
    image_height.text = "%d" % (img_height)

    image_depth = etree.SubElement(size, "depth")
    image_depth.text = "%d" % (img_depth)
    ####################################################

    segmented = etree.Element("segmented")
    segmented.text = "0"

    root.append(folder)
    root.append(filename)
    root.append(path)
    root.append(source)
    root.append(size)
    root.append(segmented)

    for ii in range(len(txt_file)):

        label = convert_label(txt_file[ii][0])
        x_min_rect, x_max_rect, y_min_rect, y_max_rect = extract_coor(txt_file[ii], img_width, img_height)

        object = etree.Element("object")
        ####################object - element##################
        name = etree.SubElement(object, "name")
        name.text = "%s"%(label)

        pose = etree.SubElement(object, "pose")
        pose.text = "Unspecified"

        truncated = etree.SubElement(object, "truncated")
        truncated.text = "0"

        difficult = etree.SubElement(object, "difficult")
        difficult.text = "0"

        bndbox = etree.SubElement(object, "bndbox")
                #####sub_sub########
        xmin = etree.SubElement(bndbox, "xmin")
        xmin.text = "%d"%(x_min_rect)
        ymin = etree.SubElement(bndbox, "ymin")
        ymin.text = "%d" % (y_min_rect)
        xmax = etree.SubElement(bndbox, "xmax")
        xmax.text = "%d" % (x_max_rect)
        ymax = etree.SubElement(bndbox, "ymax")
        ymax.text = "%d" % (y_max_rect)
                #####sub_sub########

        root.append(object)
        ####################################################

**Comment by Jeongseop-Yun** [comment]
sorry for late, bold text isn't code that just explain the code's role.
