### ISSUE TITLE
Cannot re-make after installing CUDA and OpenCV

### ISSUE THREAD

**Issue by SkyeYoung** [thtrieu/darkflow#79]
**After installing CUDA and OpenCV, and changing first four lines of the Makefile:**
GPU=1
CUDNN=0
OPENCV=1
DEBUG=0

**When make, I have:**
/bin/sh: nvcc: command not found
make: *** [obj/convolutional_kernels.o] Error 127

**Then I:**
export PATH=/usr/local/cuda/bin:$PATH
make

**It shows**
ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
ld: library not found for -lcuda
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [darknet] Error 1

**Could you please help suggest what to do? Thanks a lot ~**

- My macbook pro is 10.12.3
- I have Two GPU cards: Radeon Pro 450 and Intel HD Graphics 530
- I have CUDA Driver Version: 7.5.30
- I have cuda folder in /usr/local
- I have OpenCV installed
(through checking: pkg-config opencv --cflags, it shows -I/usr/local/include/opencv -I/usr/local/include)

**Comment by thtrieu** [comment]
Seems like you are asking questions about darknet
