### ISSUE TITLE
Yolo v1 first dog example doesn't work

### ISSUE THREAD

**Issue by haoyul** [thtrieu/darkflow#81]
Hi, the Yolo v2 works great here. But when I try the v1, the first dog/bike/car example doesn't work. There's no object:percentage output in the terminal and the saved picture under darknet folder also doesn't contain any box.
Is the v1 no longer supported?

**Comment by thtrieu** [comment]
I run
```
./flow --model cfg/v1/yolo-full.cfg --load bin/v1/yolo-full.weights
```
And the result is:
![dog](https://cloud.githubusercontent.com/assets/9194247/23820515/ad386286-064c-11e7-8cd2-b39540f944b2.jpg)

Make sure you got everything right: dependencies, command, etc

**Comment by haoyul** [comment]
All files are freshly downloaded, then build darknet and I run exactly the same command from yolo website:
./darknet yolo test cfg/yolov1/yolo.cfg yolov1.weights data/dog.jpg
then,
![screenshot from 2017-03-13 11 07 54](https://cloud.githubusercontent.com/assets/4164950/23860539/a603d21a-07dd-11e7-88f9-f5acf79efcce.png)
Any idea?

**Comment by thtrieu** [comment]
Why are you asking a `darknet` question? The code in this repo has nothing to do with your question. Please post it here: https://github.com/pjreddie/darknet
