### ISSUE TITLE
ImportError: /content/darkflow/darkflow/cython_utils/cy_yolo_findboxes.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by jibinmathew691993** [thtrieu/darkflow#825]
Running on colab gave me this bug 
ImportError: /content/darkflow/darkflow/cython_utils/cy_yolo_findboxes.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

though it didn't happen on my local machine

**Comment by keides2** [comment]
This is similar to #814 I posted.
Have you installed Cython?
You may try to install Cython.
After running $ pip install cython, I think that no error came out.

**Comment by jibinmathew691993** [comment]
I fixed the issue by cleaning the build.
setup.py clean --all
