### ISSUE TITLE
Drawing original bounding box together predicted bounding box

### ISSUE THREAD

**Issue by eljirg** [thtrieu/darkflow#830]
Hi all,

I am wondering if I can plot the ground truth bounding box and also prediction bounding box together (with different colors perhaps). Is there a way to do it? I have the json file of then predicted bounding box and xml file of the label bounding box. Is there also a simple way to calculate the MAP and IOU between them?

Thank you very much

**Comment by eljirg** [comment]
Done it by parsing and plotting ground-truth xml and predicted json files.

**Comment by himachalbanik40** [comment]
Can you please how have you done it?
