### ISSUE TITLE
Error while using cfg file and weight file from YOLO site. 

### ISSUE THREAD

**Issue by benn94** [thtrieu/darkflow#834]
As the topic suggested

I use cfg and weight file available from : https://pjreddie.com/darknet/yolov2/

I use this cfg : https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-voc.cfg
and their corresponding weight. 

But the after i run 

`flow --imgdir dataset/standford40/img  --model cfg/yolov2-voc.cfg  --load bin/yolov2-voc.weights --json --gpu 1.0`

I got this as a result

`AssertionError: expect 202704260 bytes, found 202704264`

Then I rename cfg and weight file and run command:

`flow --imgdir dataset/standford40/img  --model cfg/yolo-voc-standford.cfg  --load bin/yolo-voc.weights --json --gpu 1.0`

output is still the same

**Comment by benmurphy7** [comment]
Try [this solution](https://github.com/thtrieu/darkflow/issues/421#issuecomment-344708533). This fixed a similar problem I was having.

**Comment by adavoudi** [comment]
PR #836 can solve your problem
