### ISSUE TITLE
Slow training on GPU

### ISSUE THREAD

**Issue by acorovic** [thtrieu/darkflow#838]
Hi, I'm training tiny-yolov2 on bdd dataset, which conttins images with resolution 1280x720 and 10 classes. I'm using darkflow on Windows 10 and I have NVidia 1060 GPU with 6GB of RAM. I'm using batch size of 16 and gpu flag 0.75 and in the task manager GPU usage rarely jumps over 20%.

Why it uses just 20% of GPU instead of 75% which I've passed as command line argument and how can I speed it up?

**Comment by sandeeprepakula** [comment]
Can you try increasing the batch size from 16 to 32?

**Comment by acorovic** [comment]
Yes, I've tried that, now it works on 35%, but not constantly, it jumps to it every few seconds. Would it improve training speed if I manually resize images to 416x416 (net input size) and then run a training?

**Comment by sandeeprepakula** [comment]
Try increasing the batch size further to 64 which should utilise the GPU to its full. If it throws Out of memory error try reducing batch size to 48.

Not sure on the resizing part. But if you give the resized images as input, darkflow will still try to resize the image if you don't change the code. Code doesn't assume the size of the images are fixed. Hence it executes the resizing module on the already resized images. Hence I guess it should take same computation as no resizing.

**Comment by acorovic** [comment]
I also got out of the memory error on batch size 48, 32 looks like the max batch size for the yolov2-tiny cfg for my GPU

**Comment by acorovic** [comment]
Solved by moving to darknet repository by pjreddie for traning YOLO NNs.
