### ISSUE TITLE
Data preparation for custom dataset training

### ISSUE THREAD

**Issue by AndreaPisoni** [thtrieu/darkflow#85]
Hi, first of all, thanks for the hard work! 

I am looking to train a yoloV2 on some data with classes specific to my domain. 

I did read the README file and it just says this on annotation parsing: 

```
Parsing the annotations

Skip this if you are not training or fine-tuning anything (you simply want to forward flow a trained net)

For example, if you want to work with only 3 classes tvmonitor, person, pottedplant; edit labels.txt as follows
```

But how do I get yolo to use my own dataset to train?

**Comment by thtrieu** [comment]
1. Edit `labels.txt`
2. Design the `.cfg`
3. `./flow` with options `--train` to indicate you are training, and options `--dataset` points to your training set, `--annotation` points to your annotation. These should be in PASCAL VOC format. 

Again, as stated in README, all options are listed by `./flow --help`

**Comment by AndreaPisoni** [comment]
Thanks!
