### ISSUE TITLE
Missing cfg and weight files

### ISSUE THREAD

**Issue by dkarmon** [thtrieu/darkflow#87]
I'm trying to run the tutorial mentioned in the README.md - but the cfg and weight files are missing.
> 1. Load yolo-tiny.weights
> ./flow --model cfg/**yolo-tiny.cfg** --load bin/**yolo-tiny.weights**
> 
> 2. To completely initialize a model, leave the --load option
> ./flow --model cfg/**yolo-3c.cfg**
> 
> 3. It is useful to reuse the first identical layers of tiny for 3c
> ./flow --model cfg/**yolo-3c.cfg** --load bin/**yolo-tiny.weights**
> this will print out which layers are reused, which are initialized

Where can I download them? 
I tried to download similar files from [here](http://pjreddie.com/darknet/yolo/) and make the required adjustments but I can't find something that resembles the **yolo-3.cfg** file

Also, where should the "labels.txt" file be located?

Please advise

**Comment by thtrieu** [comment]
All `.weights` are downloaded from darknet website or my google drive (see README).

 `3c` is just an example, basically represent any new configuration user wants to work with, it is not a given config with trained weights.

`labels.txt` should be a text file in the main directory `./`. Leave it empty for the original configs (ones provided by darknet with trained weights)
