### ISSUE TITLE
How could I got .weights file after traing model on my own datasets?

### ISSUE THREAD

**Issue by Chencao0928** [thtrieu/darkflow#886]
I'm a beginner,hello.
I wish to test my trained model after training on my own datasets, but I can not find .weights file. the command I used when I'm training on my dataset is "flow --model cfg/tiny-yolo-voc.cfg --train --trainer adam --dataset  /VOC/images --annotation VOC/annotations --gpu 1.0". I got numbers of .cpkt when taring finished. How could I test my trained model with these data? or how could I get .weights file after traing? thanks.

**Comment by Wanderish** [comment]
Hey, @Chencao0928 were you able to find out a way to do that? 
I'm stuck at that step, too.

**Comment by leijuzi** [comment]
hi have sloved this problem?i meet this so

**Comment by mpky** [comment]
`!python flow --model cfg/tiny-yolo-voc-1c.cfg \
--load -1 \
--demo your_video.mp4 \
--gpu 1.0 \
--saveVideo`

Is what I have been using to test videos. The --load -1 will use the most recent checkpoint.
