### ISSUE TITLE
run on windows?

### ISSUE THREAD

**Issue by imian00** [thtrieu/darkflow#89]
Q : is this code possible to run on Windows??
I read and followed your readme.md manual to run DEMO but i failed
I typed ./flow --h in Windows CMD but it says '.' is not a usable command..
is there anyway to run this code on windows??

sorry for my poor english and poor question( i have little knowledge in these computer science.. sry T.T )
btw i think what you've done is so cool! thanks for your great work!

**Comment by AndreaPisoni** [comment]
If you look at flow you see it's a python script. So you will need to
install Python and set the Python path on the PATH env variable, then call
python ./flow etc...

**Comment by imian00** [comment]
@AndreaPisoni Thanks! it worked!
but one more thing.. could you please tell me why I got this result below?
yolo detected a giraffe as a person..
I used the command below
python ./flow --model cfg/v1/yolo-tiny4c.cfg --load bin/yolo-tiny.weights

![image](https://cloud.githubusercontent.com/assets/24829298/23898145/407084ae-08f3-11e7-98eb-21a9d796e57f.png)

**Comment by AndreaPisoni** [comment]
Yolo is trained on the 20 VOC 2012 classes and giraffe is not one of the
classes. So it is possible the network has never seen a giraffe before, so
it is not surprising it is mistaking it for a person

**Comment by imian00** [comment]
@AndreaPisoni  thanks! i understood.
have a nice day bro :)
