### ISSUE TITLE
Segmentation fault (core dumped) while running the tiny yolo command as in the README

### ISSUE THREAD

**Issue by hemavakade** [thtrieu/darkflow#92]
I am trying to walk through the Readme, and run the commands so that I can later change configs accordingly. The file naming conventions are different and are a little confusing. The darknet website seems to have separate links for weights and cfgs of VOC and COCO datasets. Which weight file are we using and which is the cfg used in the script in README.
<img width="730" alt="screen shot 2017-03-14 at 4 06 49 pm" src="https://cloud.githubusercontent.com/assets/16784667/23926236/44161c7c-08d0-11e7-8115-876150f5ece4.png">

These are the commands in the README I am trying to execute,
```
./flow --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights
./flow --test test/ --model cfg/yolo-tiny.cfg --load bin/yolo-tiny.weights --gpu 0.4
```
I used `tiny-yolo.cfg` which is in the CFG folder in this github repo.
I found `tiny-yolo-voc.weights`, `yolo.weights` on darknet, I tried the combination of these and it gave me an error every time

Error-

This is the part of message that is printed when I executed the commands,

```Total memory: 11.90GiB
Free memory: 11.22GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
Finished in 1.8043920993804932s

Forwarding 8 inputs ...
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.19GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.30GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
Total time = 0.5816457271575928s / 8 inps = 13.754076797047384 ips
Post processing 8 inputs ...
Total time = 1.594757080078125s / 8 inps = 5.0164379891689155 ips
Segmentation fault (core dumped)```

I ran into either segmentation fault error or this python error

```*** Error in python: free(): invalid pointer: 0x0000000001acee10 ***
Aborted (core dumped)
```

IMO, there is mismatch of the weights file and cfg. Can you please advice what can I correct to run the just the test script.

Note I added the following code in `build.py` so that the memory does not utilize all the available GPU memory,

```python 
cfg['gpu_options'] = tf.GPUOptions(
				per_process_gpu_memory_fraction = utility, allow_growth = True)
```

**Comment by thtrieu** [comment]
`yolo-tiny` you used is the old version. It is no longer supported on the original darknet web page anymore, you can still find it in the google drive repository in README.

**Comment by hemavakade** [comment]
Thanks. It worked when I used `yolo.weights` from the website and `yolo.cfg` from the cfg folder

**Comment by thtrieu** [comment]
`./flow` is the command for all. You only have to match cfg and weight correctly.

**Comment by yuvvi** [comment]
Hi
Trying to train 2 classes. Please help for below error

while running YOLO V2.0
Loading weights from darknet19_448.conv.23...Done!
Learning Rate: 0.0001, Momentum: 0.9, Decay: 0.0005
Loaded: 0.236922 seconds
Segmentation fault (core dumped)

I am using system config: 3GB GPU, 32GB RAM, I5 processor, CUDA 9.0, openCV3.6
