### ISSUE TITLE
how to train on a completely new model ?

### ISSUE THREAD

**Issue by alessandroCharbonnier** [thtrieu/darkflow#928]
Not really an issue, but for a personal project I need to classify only 10 different objects, so I don't need to have the full yolo model.

I was wondering if it's possible to train a model from scratch?
Thanks

**Comment by rimoune** [comment]
Hi Alessandro, I think it is possible. 
From my understanding and from what I've been experimenting lately you need: 
--> a "labels.txt" with your list of ten objects, 
--> a folder with an .xml for each image with information about the path to the images (folder), image name (filename), width, height and depth of the image (size) and bounding box info for each object detected in the image. 
--> your version of "yolo" .cfg file adapted to your problem

Then you can run something similar to this:

flow --model   <path to your config file>  --labels <path to your .txt labels file>  --train  
 --annotation <path to your annotations folder with all the .xml> 
--dataset  <path to your image folders>  

Hope this helps
R.
