### ISSUE TITLE
detection threshold not used !!

### ISSUE THREAD

**Issue by kamelbouyacoub** [thtrieu/darkflow#93]
hello 

In the flow.py there are many flags, and one of this flags is "threshold", it is fixed to 0.1, and my question is: why in the net/yolov2/test.py the threshold is fixed to 0.6 when we test our network ?  

Thanks,

**Comment by yimintsai** [comment]
Yes, you should use **FLAGS.threshold**  instead of meta['thresh'] which is 0.6. This threshold 0.6 is used for training.

**Comment by kamelbouyacoub** [comment]
Where in the code, we use FLAGS.threshold is used ???

**Comment by abagshaw** [comment]
Yeah I think this is a bug, just replace `meta['thresh']` with `self.FLAGS.threshold` the two places it appears in `/net/yolov2/test.py` and you should be good to go. It appears that `meta['thresh']` reads from the default threshold value set in the `.cfg` file you choose but it should be reading from the user defined FLAGS one.

**Comment by abagshaw** [comment]
@thtrieu Just wondering, was that a bug...or is this intentional?
