### ISSUE TITLE
Indistinguishable objects in Train Image

### ISSUE THREAD

**Issue by shubham99bisht** [thtrieu/darkflow#940]
Is it necessary to annotate all objects in my training image? I have images in which some objects are very blur and indistinguishable.

Eg. In this image, there are many cases where I can't identify whether the driver is wearing a helmet or not. So, will it have any negative impact on training?

![image](https://user-images.githubusercontent.com/20948784/48955031-f543bc00-ef71-11e8-90e0-5430a7b6486d.png)

Or maybe if I miss labeling some bikes, will it confuse the model?

**Comment by alishibli97** [comment]
Just remove the picture from training phase.
You may use it in testing phase.
