### ISSUE TITLE
How to run frozen graph(.pb) file for object detection in python?

### ISSUE THREAD

**Issue by msarfrazcss** [thtrieu/darkflow#947]
Hey guys,

I have seen many python scripts that performs object detection by using yolov2 weights, but i want to do same thing by using frozen graph(.pb) file (not using weights).
I have trained my own dataset by using Darkflow yolov2.

Can anyone tell me please how to do so, Or can i get the python script for the same?

**Comment by Sreerag-ibtl** [comment]
https://github.com/deep-diver/Soccer-Ball-Detection-YOLOv2/issues/2#issuecomment-442443523

**Comment by msarfrazcss** [comment]
Thanks @Sreerag-ibtl ,

I found it.
