### ISSUE TITLE
Converting GraphDef(.pb) to TFLite format.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [thtrieu/darkflow#952]
I am new to tensorflow and was planning to run object detection in pi. I have trained a model to detect license plates. The saved model(.pb) size is about 202M. So i thought it will be better to reduce the size to some extent. When searched about quantizing the model, I found that, the only option is to convert it to TFLite format ( Please do comment if you know any other way ). The following code will carry out this conversion:
```
converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays)
```
Where 
 |        graph_def_file: Full filepath of file containing frozen GraphDef.
 |        input_arrays: List of input tensors to freeze graph with.
 |        output_arrays: List of output tensors to freeze graph with.
But i am confused about input_arrays and output_arrays in darkflow. Is there any way to know these attributes?

**Comment by TheSadRhino** [comment]
input_arrays = input and output_arrays = output
