### ISSUE TITLE
Using flow for converting yolov2-tiny.cfg and yolov2-tiny.weights to .pb does not work

### ISSUE THREAD

**Issue by prateethvnayak** [thtrieu/darkflow#981]
I downloaded the yolov2-tiny.cfg and yolov2-tiny.weights from official Darknet page
the commands 
`./flow --model cfg/yolov2-tiny.cfg --load weights/yolov2-tiny.weights --savepb`
gives the following error : 
`AssertionError: expect 44948596 bytes, found 44948600`

**Comment by sharived** [comment]
I'm having the same problem with a custom yolov2 model
AssertionError: expect 202663260 bytes, found 202663264

Seems to be consistently off by 4 bytes

**Comment by prateethvnayak** [comment]
It is Solved in [#802 Comment](https://github.com/thtrieu/darkflow/issues/802#issuecomment-462933956)
Closing the Issue
