### ISSUE TITLE
No bounding box found in processed video.

### ISSUE THREAD

**Issue by buckyball99** [thtrieu/darkflow#992]
Hello, I am just starting out with Darkflow, I wanted to process a video file of a car game that I recorded before hand.  I used the pair of the yolov2-tiny.weights & the recognized tiny-yolo.cfg found in the /bin folder. The video file was of 'webm' format( for future use in a web streaming application), and the output was in 'avi'.
The video was generated successfully, but there's not 1 single bounding box in the entire video. The labels.txt was also unmodified, so I didn't limit it to any number of classes. I wonder if the problem lies in the version of opencv installed. The command below used ran without any errors

This is my Conda requirements file-
[230219requirements.txt](https://github.com/thtrieu/darkflow/files/2897031/230219requirements.txt)

The Output from Anaconda terminal-
(tf15) C:\Users\harsh\Documents\CODING\YOLO\darkflow>python flow --model cfg/tiny-yolo.cfg --load bin/yolov2-tiny.weights --demo videoplayback.webm --gpu 0.7 --saveVideo

Parsing ./cfg/yolov2-tiny.cfg
Parsing cfg/tiny-yolo.cfg
Loading bin/yolov2-tiny.weights ...
Successfully identified 44948600 bytes
Finished in 0.015588760375976562s
Model has a coco model name, loading coco labels.

Building net ...
Source | Train? | Layer description                | Output size
-------+--------+----------------------------------+---------------
       |        | input                            | (?, 416, 416, 3)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 416, 416, 16)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 208, 208, 16)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 208, 208, 32)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 104, 104, 32)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 104, 104, 64)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 52, 52, 64)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 52, 52, 128)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 26, 26, 128)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 26, 26, 256)
 Load  |  Yep!  | maxp 2x2p0_2                     | (?, 13, 13, 256)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 512)
 Load  |  Yep!  | maxp 2x2p0_1                     | (?, 13, 13, 512)
 Load  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 3x3p1_1  +bnorm  leaky      | (?, 13, 13, 1024)
 Init  |  Yep!  | conv 1x1p0_1    linear           | (?, 13, 13, 425)
-------+--------+----------------------------------+---------------
GPU mode with 0.7 usage
2019-02-23 21:00:48.188448: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-02-23 21:00:49.652404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.29GiB
2019-02-23 21:00:49.677031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-02-23 21:00:50.469948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-23 21:00:50.478024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-02-23 21:00:50.483153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-02-23 21:00:50.490606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2867 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Finished in 9.694693088531494s

Press [ESC] to quit demo
31.151 FPS
End of Video

Any help would be appreciated..

**Comment by buckyball99** [comment]
UPDATE - Gave up on trying to make the yolov2-tiny.weights work with the tiny-yolo.cfg. Shifted to the yolov2 binary file and the detection works like a charm. 
With the Tiny yolo model i ran into several errors I didn't fully understand myself , I'll list the issues in which I found something resembling a proper solution.

Issue #295 - 
This was the first error, solved by renaming the cfg file to one of the recognized config files, or just by using one of the included files in the cfg directory.

Issue #802  - 
"AssertionError: expect 44948596 bytes, found 44948600" was the error, and pertaining 
to this issue, I modified the loader.py and changed the 'self.offset' value from 16 to 20 ( difference of bytes) . Solving this error, the resulting video or img directory got processed, but no bounding boxed were found.

Finally I tried the yolov2 weights as mentioned above and got another error-
     File "C:\Users\harsh\Documents\CODING\YOLO\darkflow\darkflow\utils\loader.py", line 127, in walk
    'Over-read {}'.format(self.path)
     AssertionError: Over-read bin/yolov2.weights
I changed the 'self.offset' value in loader.py back to 16, and everything worked. 
Check out @chadrick-kwag 's answer on Issue #153 to understand the above bit of code.

Still need help on getting the damn tiny-yolo model to work, need more fps :)

**Comment by ShivarajMeti** [comment]
> Hello, I am just starting out with Darkflow, I wanted to process a video file of a car game that I recorded before hand. I used the pair of the yolov2-tiny.weights & the recognized tiny-yolo.cfg found in the /bin folder. The video file was of 'webm' format( for future use in a web streaming application), and the output was in 'avi'.
> The video was generated successfully, but there's not 1 single bounding box in the entire video. The labels.txt was also unmodified, so I didn't limit it to any number of classes. I wonder if the problem lies in the version of opencv installed. The command below used ran without any errors
> 
> This is my Conda requirements file-
> [230219requirements.txt](https://github.com/thtrieu/darkflow/files/2897031/230219requirements.txt)
> 
> The Output from Anaconda terminal-
> (tf15) C:\Users\harsh\Documents\CODING\YOLO\darkflow>python flow --model cfg/tiny-yolo.cfg --load bin/yolov2-tiny.weights --demo videoplayback.webm --gpu 0.7 --saveVideo
> 
> Parsing ./cfg/yolov2-tiny.cfg
> Parsing cfg/tiny-yolo.cfg
> Loading bin/yolov2-tiny.weights ...
> Successfully identified 44948600 bytes
> Finished in 0.015588760375976562s
> Model has a coco model name, loading coco labels.
> 
> Building net ...
> Source | Train? | Layer description | Output size
> -------+--------+----------------------------------+---------------
> | | input | (?, 416, 416, 3)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 416, 416, 16)
> Load | Yep! | maxp 2x2p0_2 | (?, 208, 208, 16)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 208, 208, 32)
> Load | Yep! | maxp 2x2p0_2 | (?, 104, 104, 32)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 104, 104, 64)
> Load | Yep! | maxp 2x2p0_2 | (?, 52, 52, 64)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 52, 52, 128)
> Load | Yep! | maxp 2x2p0_2 | (?, 26, 26, 128)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 26, 26, 256)
> Load | Yep! | maxp 2x2p0_2 | (?, 13, 13, 256)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 13, 13, 512)
> Load | Yep! | maxp 2x2p0_1 | (?, 13, 13, 512)
> Load | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 13, 13, 1024)
> Init | Yep! | conv 3x3p1_1 +bnorm leaky | (?, 13, 13, 1024)
> Init | Yep! | conv 1x1p0_1 linear | (?, 13, 13, 425)
> -------+--------+----------------------------------+---------------
> GPU mode with 0.7 usage
> 2019-02-23 21:00:48.188448: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> 2019-02-23 21:00:49.652404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
> pciBusID: 0000:01:00.0
> totalMemory: 4.00GiB freeMemory: 3.29GiB
> 2019-02-23 21:00:49.677031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> 2019-02-23 21:00:50.469948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-02-23 21:00:50.478024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0
> 2019-02-23 21:00:50.483153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N
> 2019-02-23 21:00:50.490606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2867 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> Finished in 9.694693088531494s
> 
> Press [ESC] to quit demo
> 31.151 FPS
> End of Video
> 
> Any help would be appreciated..

**Comment by ShivarajMeti** [comment]
Hello, even I was facing the same problem while I was training with my own data set. One thing I tried while I was crawling through online for the issue is to tweak the ```threshold ``` value. Try reducing your detection threshold as low as possible to make bounding boxes display on your video/image output although tweaking threshold might yield you more false positives but you will be able to see the bounding boxes.

Try this : 
```python flow --model cfg/tiny-yolo.cfg --load bin/yolov2-tiny.weights --demo videoplayback.webm --gpu 0.7 --saveVideo   --threshold 0.3```

Hope this helps.

**Comment by mpky** [comment]
@buckyball99 any idea why the tiny yolo weights are worse? and does training the regular weights (and I assume you're talking about YOLOv2 model on VOC 2007+2012) take more time?

**Comment by buckyball99** [comment]
> Hello, even I was facing the same problem while I was training with my own data set. One thing I tried while I was crawling through online for the issue is to tweak the `threshold ` value. Try reducing your detection threshold as low as possible to make bounding boxes display on your video/image output although tweaking threshold might yield you more false positives but you will be able to see the bounding boxes.
> 
> Try this :
> `python flow --model cfg/tiny-yolo.cfg --load bin/yolov2-tiny.weights --demo videoplayback.webm --gpu 0.7 --saveVideo --threshold 0.3`
> 
> Hope this helps.


Thanks!   This seems the most probable solution, but the actual problem was that the cfg file I was using had some modifications which limited it to detect only a select few classes, so I downloaded the yolov2-tiny.cfg from the darknet repo, and the tiny model is working now.

**Comment by buckyball99** [comment]
> @buckyball99 any idea why the tiny yolo weights are worse? and does training the regular weights (and I assume you're talking about YOLOv2 model on VOC 2007+2012) take more time?

When I tried both the yolov2 and tiny-yolo weights on 8 input images, the tiny model took around 20 seconds lesser than the other to train the model (12 seconds total). Surprisingly, this wasn't the case while processing the actual images

Output for the tiny-yolo model-
Forwarding 8 inputs ...
Total time = 5.131803274154663s / 8 inps = 1.5589062114462682 ips
Post processing 8 inputs ...
Total time = 1.166926383972168s / 8 inps = 6.855616695175183 ips

Output for the yolov2 model-
Forwarding 8 inputs ...
Total time = 6.931561470031738s / 8 inps = 1.1541411029228554 ips
Post processing 8 inputs ...
Total time = 0.7906391620635986s / 8 inps = 10.118395829419443 ips

Accounting for the other factors, the same 8 images took 35.741s and 18.748s on the yolo and tiny-yolo weights respectively.
